In [82]:
import talib
import yfinance as yf
import pandas as pd
from pandas import Timestamp
import numpy as np

In [83]:
data = yf.download('SPY', start = '2023-01-20', end = '2024-01-22')

[*********************100%%**********************]  1 of 1 completed

In [84]:
data_5m = yf.download('SPY', start = '2023-12-20', end = '2024-01-22', interval = '5m')

[*********************100%%**********************]  1 of 1 completed

In [85]:
print(data['Close']['2023-01-23'])
print(data_5m)

400.6300048828125
                                 Open        High         Low       Close  \
Datetime
2023-12-20 09:30:00-05:00  473.970001  474.174988  473.945007  474.130005
2023-12-20 09:35:00-05:00  474.130005  474.420013  474.109985  474.404999
2023-12-20 09:40:00-05:00  474.399994  474.619995  474.269989  474.600006
2023-12-20 09:45:00-05:00  474.600006  474.640015  474.464996  474.565002
2023-12-20 09:50:00-05:00  474.570007  474.660004  474.510010  474.510010
2023-12-20 09:55:00-05:00  474.519989  474.649994  474.500000  474.620087
2023-12-20 10:00:00-05:00  474.619995  475.045013  474.559998  474.899994
2023-12-20 10:05:00-05:00  474.894989  475.190002  474.894989  475.139008
2023-12-20 10:10:00-05:00  475.140015  475.154999  474.970001  475.079010
2023-12-20 10:15:00-05:00  475.075012  475.230011  475.000000  475.059998
2023-12-20 10:20:00-05:00  475.049988  475.230011  475.029999  475.109985
2023-12-20 10:25:00-05:00  475.119995  475.174988  475.030914  475.130096
2023-12-20 10:30:00-05:00  475.135010  475.554993  475.135010  475.420105
2023-12-20 10:35:00-05:00  475.420013  475.500000  475.315002  475.350006
2023-12-20 10:40:00-05:00  475.350006  475.500000  475.165009  475.469910
2023-12-20 10:45:00-05:00  475.470001  475.589996  475.271088  475.380005
2023-12-20 10:50:00-05:00  475.399994  475.484985  475.189911  475.200012
2023-12-20 10:55:00-05:00  475.195007  475.394989  475.192108  475.359894
2023-12-20 11:00:00-05:00  475.345001  475.450012  475.230011  475.319885
2023-12-20 11:05:00-05:00  475.329987  475.390015  475.140015  475.170013
2023-12-20 11:10:00-05:00  475.154999  475.328491  475.130005  475.130005
2023-12-20 11:15:00-05:00  475.130005  475.399994  475.070007  475.385010
2023-12-20 11:20:00-05:00  475.380005  475.459991  475.320007  475.390015
2023-12-20 11:25:00-05:00  475.399902  475.421509  475.160004  475.301788
2023-12-20 11:30:00-05:00  475.309998  475.330109  475.029999  475.109985
2023-12-20 11:35:00-05:00  475.109985  475.250000  475.089996  475.168091
2023-12-20 11:40:00-05:00  475.160004  475.200012  475.049988  475.119995
2023-12-20 11:45:00-05:00  475.130005  475.290009  475.084991  475.208008
2023-12-20 11:50:00-05:00  475.195007  475.350006  475.144989  475.260101
2023-12-20 11:55:00-05:00  475.269989  475.290009  475.119995  475.171906
2023-12-20 12:00:00-05:00  475.170013  475.399994  475.170013  475.364990
2023-12-20 12:05:00-05:00  475.304993  475.380005  475.290009  475.315002
2023-12-20 12:10:00-05:00  475.315002  475.464996  475.299988  475.415009
2023-12-20 12:15:00-05:00  475.410004  475.500000  475.350006  475.470001
2023-12-20 12:20:00-05:00  475.459991  475.540009  475.390015  475.484985
2023-12-20 12:25:00-05:00  475.489990  475.554993  475.434998  475.464996
2023-12-20 12:30:00-05:00  475.470001  475.500000  475.091003  475.278503
2023-12-20 12:35:00-05:00  475.279999  475.359985  475.200012  475.329987
2023-12-20 12:40:00-05:00  475.329895  475.674988  475.317200  475.589996
2023-12-20 12:45:00-05:00  475.570007  475.649994  475.500000  475.584991
2023-12-20 12:50:00-05:00  475.584991  475.700012  475.549988  475.635010
2023-12-20 12:55:00-05:00  475.640015  475.894989  475.633606  475.795013
2023-12-20 13:00:00-05:00  475.799988  475.815002  475.519989  475.785004
2023-12-20 13:05:00-05:00  475.769989  475.795013  475.609985  475.609985
2023-12-20 13:10:00-05:00  475.600006  475.744995  475.529999  475.558197
2023-12-20 13:15:00-05:00  475.558502  475.674988  475.499695  475.640015
2023-12-20 13:20:00-05:00  475.635010  475.679993  475.540009  475.560211
2023-12-20 13:25:00-05:00  475.570007  475.614990  475.519989  475.570007
2023-12-20 13:30:00-05:00  475.570007  475.760010  475.570007  475.730011
2023-12-20 13:35:00-05:00  475.730011  475.739990  475.450012  475.476013
2023-12-20 13:40:00-05:00  475.470001  475.540009  475.244995  475.345001
2023-12-20 13:45:00-05:00  475.329987  475.434296  475.244995  475.329987
2023-12-20 13:50:00-05:00  475.339996  475.369995  475.239990  475.250000
2023-12-20 13:55:00-05:00  475.239990  475.244995  474.980011  475.059998
2023-12-20 14:00:00-05:00  475.059998  475.100006  474.665009  474.679993
2023-12-20 14:05:00-05:00  474.690002  474.859985  474.684998  474.799988
2023-12-20 14:10:00-05:00  474.790009  475.019989  474.779999  475.010010
2023-12-20 14:15:00-05:00  475.010010  475.015015  474.859985  474.869995
2023-12-20 14:20:00-05:00  474.879913  474.879913  474.704987  474.755005
2023-12-20 14:25:00-05:00  474.760010  474.799988  474.535004  474.571014
2023-12-20 14:30:00-05:00  474.579987  474.589996  474.140015  474.230011
2023-12-20 14:35:00-05:00  474.229706  474.369995  473.339996  473.480011
2023-12-20 14:40:00-05:00  473.459991  473.809998  473.200012  473.200012
2023-12-20 14:45:00-05:00  473.190002  473.399994  472.505005  472.600006
2023-12-20 14:50:00-05:00  472.609985  472.699005  470.279999  471.660004
2023-12-20 14:55:00-05:00  471.660004  471.880005  470.470001  470.494995
2023-12-20 15:00:00-05:00  470.489990  470.779999  469.660004  469.760010
2023-12-20 15:05:00-05:00  469.750000  470.029999  469.049988  469.809998
2023-12-20 15:10:00-05:00  469.790009  470.640015  469.665009  469.799988
2023-12-20 15:15:00-05:00  469.799988  471.170105  469.799988  470.815002
2023-12-20 15:20:00-05:00  470.815002  470.989990  469.970001  469.970398
2023-12-20 15:25:00-05:00  469.975006  470.290009  469.239990  469.279999
2023-12-20 15:30:00-05:00  469.279999  469.954987  469.010010  469.380005
2023-12-20 15:35:00-05:00  469.380005  469.420013  468.910004  469.010010
2023-12-20 15:40:00-05:00  469.010010  469.769989  468.989990  469.730011
2023-12-20 15:45:00-05:00  469.734985  469.839996  469.350006  469.795013
2023-12-20 15:50:00-05:00  469.809998  470.140015  468.954987  469.369995
2023-12-20 15:55:00-05:00  469.375000  469.375000  467.820007  467.980011
2023-12-21 09:30:00-05:00  471.329987  472.100006  470.980011  471.859985
2023-12-21 09:35:00-05:00  471.860107  472.299988  471.299988  472.109985
2023-12-21 09:40:00-05:00  472.109985  472.239990  471.450012  471.950012
2023-12-21 09:45:00-05:00  471.950012  472.079987  471.665009  471.839996
2023-12-21 09:50:00-05:00  471.839996  472.138489  471.709991  471.739990
2023-12-21 09:55:00-05:00  471.730011  471.839996  471.290009  471.399994
2023-12-21 10:00:00-05:00  471.410004  471.760010  471.170013  471.214996
2023-12-21 10:05:00-05:00  471.214996  471.220001  470.549988  470.630005
2023-12-21 10:10:00-05:00  470.630005  471.510010  470.559998  471.355011
2023-12-21 10:15:00-05:00  471.361511  471.769989  470.984985  471.619904
2023-12-21 10:20:00-05:00  471.619995  472.440002  471.570007  472.329987
2023-12-21 10:25:00-05:00  472.339996  472.380005  470.980011  471.170013
2023-12-21 10:30:00-05:00  471.179993  471.730011  471.170013  471.690002
2023-12-21 10:35:00-05:00  471.690002  471.799988  471.269989  471.350006
2023-12-21 10:40:00-05:00  471.359985  471.710114  471.070007  471.570007
2023-12-21 10:45:00-05:00  471.579987  471.809998  471.420013  471.484985
2023-12-21 10:50:00-05:00  471.479492  471.500000  470.910004  471.065613
2023-12-21 10:55:00-05:00  471.059998  471.179993  470.850006  471.170013
2023-12-21 11:00:00-05:00  471.160004  471.589996  470.971710  471.399994
2023-12-21 11:05:00-05:00  471.399994  471.470001  470.769989  470.929993
2023-12-21 11:10:00-05:00  470.938812  471.220001  470.734985  471.149994
2023-12-21 11:15:00-05:00  471.158905  471.190002  470.660004  470.934998
2023-12-21 11:20:00-05:00  470.924988  471.299988  470.820007  471.230011
2023-12-21 11:25:00-05:00  471.220001  471.540009  471.029999  471.510010
2023-12-21 11:30:00-05:00  471.489990  471.570007  471.109985  471.230011
2023-12-21 11:35:00-05:00  471.385010  471.690002  471.190002  471.385010
2023-12-21 11:40:00-05:00  471.380005  471.429993  471.140015  471.220001
2023-12-21 11:45:00-05:00  471.209991  471.440002  471.179993  471.341187
2023-12-21 11:50:00-05:00  471.339996  471.339996  470.940002  470.970001
2023-12-21 11:55:00-05:00  470.970001  470.989990  470.420013  470.549988
2023-12-21 12:00:00-05:00  470.549988  470.549988  469.589996  469.600006
2023-12-21 12:05:00-05:00  469.619995  470.067200  469.489990  469.515015
2023-12-21 12:10:00-05:00  469.579987  469.869995  469.459991  469.549988
2023-12-21 12:15:00-05:00  469.549988  469.859894  469.470001  469.681213
2023-12-21 12:20:00-05:00  469.684998  469.750000  469.420013  469.709991
2023-12-21 12:25:00-05:00  469.709991  469.720001  469.399994  469.540100
2023-12-21 12:30:00-05:00  469.549988  470.190002  469.480011  469.579987
2023-12-21 12:35:00-05:00  469.600006  469.880005  469.429993  469.700012
2023-12-21 12:40:00-05:00  469.700012  470.131195  469.600006  469.820007
2023-12-21 12:45:00-05:00  469.815002  469.964996  469.704987  469.779999
2023-12-21 12:50:00-05:00  469.760986  469.959991  469.390015  469.434998
2023-12-21 12:55:00-05:00  469.429993  469.569397  469.269989  469.479889
2023-12-21 13:00:00-05:00  469.480011  470.100006  469.454987  469.994995
2023-12-21 13:05:00-05:00  469.980011  470.070007  469.585999  469.779999
2023-12-21 13:10:00-05:00  469.769989  470.079987  469.600006  469.660004
2023-12-21 13:15:00-05:00  469.660004  469.690002  468.869995  468.890015
2023-12-21 13:20:00-05:00  468.899994  470.184998  468.839996  470.000000
2023-12-21 13:25:00-05:00  470.019989  470.140015  469.690002  470.095001
2023-12-21 13:30:00-05:00  470.100006  470.480011  469.989990  470.070007
2023-12-21 13:35:00-05:00  470.071014  470.179993  469.859985  469.920013
2023-12-21 13:40:00-05:00  469.928497  470.132599  469.790009  469.910004
2023-12-21 13:45:00-05:00  469.940002  470.290009  469.910004  470.129700
2023-12-21 13:50:00-05:00  470.109985  470.470001  469.989990  470.329987
2023-12-21 13:55:00-05:00  470.309998  470.589996  470.299988  470.549988
2023-12-21 14:00:00-05:00  470.559998  470.670013  470.369995  470.500000
2023-12-21 14:05:00-05:00  470.510010  470.600006  470.299988  470.359985
2023-12-21 14:10:00-05:00  470.359985  470.575012  470.160004  470.214996
2023-12-21 14:15:00-05:00  470.204987  470.850006  470.189911  470.739990
2023-12-21 14:20:00-05:00  470.744995  470.779999  470.299988  470.369995
2023-12-21 14:25:00-05:00  470.368500  470.630005  470.279999  470.619690
2023-12-21 14:30:00-05:00  470.619995  470.850006  470.429993  470.829987
2023-12-21 14:35:00-05:00  470.829987  470.910004  470.595001  470.794586
2023-12-21 14:40:00-05:00  470.790009  470.970001  470.769989  470.940002
2023-12-21 14:45:00-05:00  470.934998  471.059998  470.679993  470.690002
2023-12-21 14:50:00-05:00  470.700012  470.890015  470.608704  470.660004
2023-12-21 14:55:00-05:00  470.649994  470.699005  470.179993  470.550995
2023-12-21 15:00:00-05:00  470.570007  470.750000  470.359985  470.560303
2023-12-21 15:05:00-05:00  470.570007  470.660004  470.250000  470.379486
2023-12-21 15:10:00-05:00  470.399994  470.899994  470.329987  470.829987
2023-12-21 15:15:00-05:00  470.829987  471.019989  470.670013  470.980011
2023-12-21 15:20:00-05:00  470.980011  471.179993  470.950012  471.109985
2023-12-21 15:25:00-05:00  471.100006  471.929108  471.040009  471.894989
2023-12-21 15:30:00-05:00  471.910004  472.045013  471.630005  471.895996
2023-12-21 15:35:00-05:00  471.894989  472.410004  471.850006  472.260010
2023-12-21 15:40:00-05:00  472.260010  472.415009  472.049988  472.089996
2023-12-21 15:45:00-05:00  472.089996  472.464996  472.029999  472.339996
2023-12-21 15:50:00-05:00  472.329987  472.820007  472.220001  472.649994
2023-12-21 15:55:00-05:00  472.649994  472.975006  472.554993  472.690002
2023-12-22 09:30:00-05:00  474.000000  474.519989  473.980011  474.229889
2023-12-22 09:35:00-05:00  474.230011  474.739990  474.059998  474.630005
2023-12-22 09:40:00-05:00  474.640015  475.059998  474.559998  475.040009
2023-12-22 09:45:00-05:00  475.040009  475.170013  474.869995  475.109985
2023-12-22 09:50:00-05:00  475.109985  475.380005  475.109985  475.179993
2023-12-22 09:55:00-05:00  475.179993  475.350006  474.859985  474.910004
2023-12-22 10:00:00-05:00  474.920013  475.149994  474.600006  475.024994
2023-12-22 10:05:00-05:00  475.019989  475.269989  474.750000  475.000000
2023-12-22 10:10:00-05:00  474.989990  475.049988  474.739990  474.915009
2023-12-22 10:15:00-05:00  474.920013  474.980011  474.700012  474.850006
2023-12-22 10:20:00-05:00  474.859985  474.940002  474.609985  474.809998
2023-12-22 10:25:00-05:00  474.790009  475.219910  474.630005  475.149994
2023-12-22 10:30:00-05:00  475.149994  475.299011  475.089996  475.174988
2023-12-22 10:35:00-05:00  475.170013  475.250000  474.600006  474.845001
2023-12-22 10:40:00-05:00  474.829987  475.000000  474.825012  474.954987
2023-12-22 10:45:00-05:00  474.954987  475.014008  474.700104  474.750000
2023-12-22 10:50:00-05:00  474.750000  474.799988  474.619995  474.725006
2023-12-22 10:55:00-05:00  474.720001  474.730011  474.170013  474.200012
2023-12-22 11:00:00-05:00  474.049988  474.230011  473.910004  473.929993
2023-12-22 11:05:00-05:00  473.940002  474.140015  473.619995  474.109985
2023-12-22 11:10:00-05:00  474.119995  474.320007  474.000000  474.279999
2023-12-22 11:15:00-05:00  474.269989  474.369995  474.079987  474.339996
2023-12-22 11:20:00-05:00  474.329987  474.654999  474.230011  474.260010
2023-12-22 11:25:00-05:00  474.269989  474.464996  474.174988  474.390015
2023-12-22 11:30:00-05:00  474.380005  474.699890  474.380005  474.480011
2023-12-22 11:35:00-05:00  474.480011  474.481201  474.190002  474.309998
2023-12-22 11:40:00-05:00  474.320007  474.320007  474.036011  474.084991
2023-12-22 11:45:00-05:00  474.079987  474.179993  473.920013  473.980011
2023-12-22 11:50:00-05:00  473.980011  474.170013  473.950012  474.105011
2023-12-22 11:55:00-05:00  474.105011  474.309998  474.039886  474.065002
2023-12-22 12:00:00-05:00  474.070007  474.279999  474.049988  474.160004
2023-12-22 12:05:00-05:00  474.170013  474.449493  473.920013  473.980011
2023-12-22 12:10:00-05:00  473.969910  474.049988  473.790009  473.820007
2023-12-22 12:15:00-05:00  473.809998  473.941589  473.709991  473.850006
2023-12-22 12:20:00-05:00  473.850006  473.920013  473.661011  473.799103
2023-12-22 12:25:00-05:00  473.799988  474.190002  473.769989  474.100006
2023-12-22 12:30:00-05:00  474.109985  474.179993  473.899994  474.019989
2023-12-22 12:35:00-05:00  474.010010  474.279999  473.989990  474.260010
2023-12-22 12:40:00-05:00  474.259888  474.410004  474.234985  474.380096
2023-12-22 12:45:00-05:00  474.380005  474.545105  474.329987  474.350006
2023-12-22 12:50:00-05:00  474.354309  474.559509  474.290009  474.530090
2023-12-22 12:55:00-05:00  474.535004  474.565002  474.329987  474.549988
2023-12-22 13:00:00-05:00  474.540009  474.609985  474.390015  474.559998
2023-12-22 13:05:00-05:00  474.549988  474.695007  474.540009  474.619995
2023-12-22 13:10:00-05:00  474.611298  474.739990  474.609985  474.730011
2023-12-22 13:15:00-05:00  474.725006  474.750000  474.560089  474.600006
2023-12-22 13:20:00-05:00  474.579987  474.660004  474.575989  474.605011
2023-12-22 13:25:00-05:00  474.600006  474.690002  474.510010  474.600006
2023-12-22 13:30:00-05:00  474.589996  474.700012  474.570007  474.609985
2023-12-22 13:35:00-05:00  474.595001  474.695007  474.480011  474.515015
2023-12-22 13:40:00-05:00  474.519989  474.549988  474.244995  474.475006
2023-12-22 13:45:00-05:00  474.470001  474.559998  474.329987  474.519989
2023-12-22 13:50:00-05:00  474.519989  474.584991  474.339996  474.364014
2023-12-22 13:55:00-05:00  474.359985  474.429108  474.190002  474.220001
2023-12-22 14:00:00-05:00  474.220001  474.269989  473.859985  473.869995
2023-12-22 14:05:00-05:00  473.859985  473.920013  473.089996  473.359985
2023-12-22 14:10:00-05:00  473.350006  473.579987  473.299988  473.529999
2023-12-22 14:15:00-05:00  473.519989  473.529999  472.570007  472.980011
2023-12-22 14:20:00-05:00  472.980011  473.160004  472.100006  472.390015
2023-12-22 14:25:00-05:00  472.399994  472.454987  471.970001  472.079987
2023-12-22 14:30:00-05:00  472.089996  472.369995  471.700012  472.095001
2023-12-22 14:35:00-05:00  472.100006  472.850006  472.029999  472.579987
2023-12-22 14:40:00-05:00  472.579987  473.350006  472.575012  473.290009
2023-12-22 14:45:00-05:00  473.290009  473.649994  473.290009  473.470001
2023-12-22 14:50:00-05:00  473.460999  473.820007  473.445007  473.695007
2023-12-22 14:55:00-05:00  473.684998  473.880005  473.635010  473.880005
2023-12-22 15:00:00-05:00  473.880005  474.029999  473.609985  473.869995
2023-12-22 15:05:00-05:00  473.855011  473.920013  473.519989  473.530090
2023-12-22 15:10:00-05:00  473.619995  473.799988  473.529999  473.785004
2023-12-22 15:15:00-05:00  473.769989  473.809998  473.510010  473.719910
2023-12-22 15:20:00-05:00  473.720001  473.799988  473.440002  473.700012
2023-12-22 15:25:00-05:00  473.700012  473.980011  473.619598  473.945007
2023-12-22 15:30:00-05:00  473.940002  473.959991  473.540009  473.554993
2023-12-22 15:35:00-05:00  473.554993  473.649994  473.279999  473.285004
2023-12-22 15:40:00-05:00  473.290009  473.380005  472.975006  473.375000
2023-12-22 15:45:00-05:00  473.380005  473.510010  473.100006  473.140015
2023-12-22 15:50:00-05:00  473.119995  473.679993  473.059998  473.600006
2023-12-22 15:55:00-05:00  473.605011  473.679993  473.369995  473.619995
2023-12-26 09:30:00-05:00  474.070007  474.589996  473.989990  474.570007
2023-12-26 09:35:00-05:00  474.559998  474.654999  474.480011  474.559998
2023-12-26 09:40:00-05:00  474.570007  474.760010  474.540009  474.619995
2023-12-26 09:45:00-05:00  474.630005  474.809998  474.570007  474.609985
2023-12-26 09:50:00-05:00  474.608490  474.649994  474.359985  474.424988
2023-12-26 09:55:00-05:00  474.429993  474.690094  474.359985  474.670013
2023-12-26 10:00:00-05:00  474.679993  474.720001  474.600006  474.686005
2023-12-26 10:05:00-05:00  474.690002  474.859985  474.660004  474.769989
2023-12-26 10:10:00-05:00  474.769989  474.980011  474.760010  474.885010
2023-12-26 10:15:00-05:00  474.890015  475.000000  474.850006  474.850006
2023-12-26 10:20:00-05:00  474.859985  474.967010  474.769989  474.899994
2023-12-26 10:25:00-05:00  474.880005  475.119995  474.785004  474.864990
2023-12-26 10:30:00-05:00  474.869995  475.100006  474.869995  475.040009
2023-12-26 10:35:00-05:00  475.049896  475.140411  475.005005  475.135010
2023-12-26 10:40:00-05:00  475.130005  475.190002  474.954987  474.959991
2023-12-26 10:45:00-05:00  474.959991  475.000000  474.885010  474.915009
2023-12-26 10:50:00-05:00  474.910004  474.910004  474.529999  474.739105
2023-12-26 10:55:00-05:00  474.739990  474.920013  474.734985  474.899994
2023-12-26 11:00:00-05:00  474.910004  474.959991  474.630096  474.769989
2023-12-26 11:05:00-05:00  474.769989  474.929993  474.760010  474.910004
2023-12-26 11:10:00-05:00  474.910004  475.140015  474.799988  475.090302
2023-12-26 11:15:00-05:00  475.079987  475.109985  474.704987  474.760010
2023-12-26 11:20:00-05:00  474.750000  474.845001  474.640015  474.640015
2023-12-26 11:25:00-05:00  474.635010  474.769989  474.579987  474.750000
2023-12-26 11:30:00-05:00  474.744995  474.940002  474.730011  474.910004
2023-12-26 11:35:00-05:00  474.910004  474.977692  474.839996  474.910004
2023-12-26 11:40:00-05:00  474.904999  475.010010  474.850006  474.929993
2023-12-26 11:45:00-05:00  474.923004  475.117188  474.920013  474.971313
2023-12-26 11:50:00-05:00  474.970001  475.099915  474.959991  475.075012
2023-12-26 11:55:00-05:00  474.970001  475.130005  474.899994  475.079895
2023-12-26 12:00:00-05:00  475.079987  475.079987  474.880005  474.945007
2023-12-26 12:05:00-05:00  474.950012  474.989990  474.890015  474.959991
2023-12-26 12:10:00-05:00  474.950012  475.179993  474.950012  475.149994
2023-12-26 12:15:00-05:00  475.144989  475.230011  475.100006  475.149994

In [86]:
data_15m = yf.download('SPY', start = '2023-12-20', end = '2024-01-22', interval = '15m')
data_30m = yf.download('SPY', start = '2023-12-20', end = '2024-01-22', interval = '30m')
data_1h = yf.download('SPY', start = '2023-12-20', end = '2024-01-22', interval = '1h')

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

[*********************100%%**********************]  1 of 1 completed

In [87]:
data_60m = yf.download('SPY', start = '2023-12-20', end = '2024-01-22', interval = '60m')
pd.set_option('display.max_rows', 141)
data_60m

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2023-12-20 09:30:00,473.970001,475.230011,473.945007,475.130096,475.130096,8997403
2023-12-20 10:30:00,475.135010,475.589996,475.070007,475.301788,475.301788,5193588
2023-12-20 11:30:00,475.309998,475.554993,475.029999,475.464996,475.464996,3947108
2023-12-20 12:30:00,475.470001,475.894989,475.091003,475.570007,475.570007,5137548
2023-12-20 13:30:00,475.570007,475.760010,474.535004,474.571014,474.571014,7623651
2023-12-20 14:30:00,474.579987,474.589996,469.049988,469.279999,469.279999,29530134
2023-12-20 15:30:00,469.279999,470.140015,467.820007,467.980011,467.980011,23941933
2023-12-21 09:30:00,471.329987,472.440002,470.549988,471.170013,471.170013,18752728
2023-12-21 10:30:00,471.179993,471.809998,470.660004,471.510010,471.510010,8394982
2023-12-21 11:30:00,471.489990,471.690002,469.399994,469.540100,469.540100,9854583
2023-12-21 12:30:00,469.549988,470.190002,468.839996,470.095001,470.095001,8083555
2023-12-21 13:30:00,470.100006,470.850006,469.790009,470.619690,470.619690,6189634
2023-12-21 14:30:00,470.619995,471.929108,470.179993,471.894989,471.894989,7388693
2023-12-21 15:30:00,471.910004,472.975006,471.630005,472.690002,472.690002,13642563
2023-12-22 09:30:00,474.000000,475.380005,473.980011,475.149994,475.149994,12110420
2023-12-22 10:30:00,475.149994,475.299011,473.619995,474.390015,474.390015,8491068
2023-12-22 11:30:00,474.380005,474.699890,473.661011,474.100006,474.100006,4967328
2023-12-22 12:30:00,474.109985,474.750000,473.899994,474.600006,474.600006,5734318
2023-12-22 13:30:00,474.589996,474.700012,471.970001,472.079987,472.079987,7205040
2023-12-22 14:30:00,472.089996,474.029999,471.700012,473.945007,473.945007,9512171
2023-12-22 15:30:00,473.940002,473.959991,472.975006,473.619995,473.619995,10345331
2023-12-26 09:30:00,474.070007,475.119995,473.989990,474.864990,474.864990,7514890
2023-12-26 10:30:00,474.869995,475.190002,474.529999,474.750000,474.750000,6919823
2023-12-26 11:30:00,474.744995,475.230011,474.730011,475.070007,475.070007,4308423
2023-12-26 12:30:00,475.070007,475.459991,474.850006,475.311310,475.311310,3452801
2023-12-26 13:30:00,475.309998,475.570007,475.140015,475.524994,475.524994,3831164
2023-12-26 14:30:00,475.529999,476.579987,475.470001,476.200012,476.200012,6582092
2023-12-26 15:30:00,476.200012,476.440002,475.290009,475.589996,475.589996,12987897
2023-12-27 09:30:00,475.440002,476.140015,475.160004,475.739990,475.739990,9755062
2023-12-27 10:30:00,475.739990,475.790009,475.079987,475.470001,475.470001,5646966
2023-12-27 11:30:00,475.470001,476.070007,475.410004,475.839996,475.839996,4658326
2023-12-27 12:30:00,475.839996,476.660004,475.290009,476.239899,476.239899,6157377
2023-12-27 13:30:00,476.250000,476.489990,474.890015,475.806213,475.806213,8558557
2023-12-27 14:30:00,475.799988,475.934998,475.190002,475.644989,475.644989,9196779
2023-12-27 15:30:00,475.630005,476.570007,475.160004,476.510010,476.510010,11988444
2023-12-28 09:30:00,476.880005,477.385010,476.799988,477.268707,477.268707,6620236
2023-12-28 10:30:00,477.269989,477.500000,476.589996,476.859314,476.859314,5545977
2023-12-28 11:30:00,476.880005,477.190002,476.709991,476.904999,476.904999,3770077
2023-12-28 12:30:00,476.899994,477.410004,476.429993,477.040009,477.040009,8362425
2023-12-28 13:30:00,477.038208,477.549988,476.919708,477.350006,477.350006,7117839
2023-12-28 14:30:00,477.359985,477.500000,476.619995,476.899994,476.899994,10867672
2023-12-28 15:30:00,476.899994,477.345001,476.260010,476.670013,476.670013,16366070
2023-12-29 09:30:00,476.489990,477.029999,476.410004,476.704987,476.704987,9036139
2023-12-29 10:30:00,476.709991,476.760010,473.899994,473.950012,473.950012,18621858
2023-12-29 11:30:00,473.940002,474.559998,473.299988,473.589905,473.589905,10997530
2023-12-29 12:30:00,473.625000,475.104004,473.510010,474.500000,474.500000,8044393
2023-12-29 13:30:00,474.489990,475.459991,474.475006,475.049988,475.049988,8856547
2023-12-29 14:30:00,475.049988,475.890015,475.049988,475.779999,475.779999,15608948
2023-12-29 15:30:00,475.769989,475.779999,474.489990,475.350006,475.350006,23612806
2024-01-02 09:30:00,472.160004,472.799988,471.359985,471.760010,471.760010,19608168
2024-01-02 10:30:00,471.769989,472.450012,471.299988,472.329987,472.329987,9085308
2024-01-02 11:30:00,472.320007,473.359985,472.269989,472.975006,472.975006,9373953
2024-01-02 12:30:00,472.975006,473.670013,472.279999,472.660492,472.660492,7394613
2024-01-02 13:30:00,472.660004,472.959686,471.545013,471.880096,471.880096,9946269
2024-01-02 14:30:00,471.859985,472.059998,470.489990,470.910004,470.910004,13662376
2024-01-02 15:30:00,470.904999,472.670013,470.670013,472.600006,472.600006,24786273
2024-01-03 09:30:00,470.429993,470.959991,469.220001,469.500000,469.500000,18908272
2024-01-03 10:30:00,469.489990,469.929993,468.709991,469.709991,469.709991,14067856
2024-01-03 11:30:00,469.730011,469.790009,468.970001,469.579987,469.579987,7616562
2024-01-03 12:30:00,469.579987,470.769989,469.420502,470.329987,470.329987,6375672
2024-01-03 13:30:00,470.339996,471.190002,468.950012,470.940002,470.940002,11787244
2024-01-03 14:30:00,470.950012,471.179993,468.970001,469.260010,469.260010,12079010
2024-01-03 15:30:00,469.274994,469.795013,468.170013,468.730011,468.730011,18962548
2024-01-04 09:30:00,468.299988,470.149994,468.109985,469.765015,469.765015,12633397
2024-01-04 10:30:00,469.760010,470.959991,469.619995,470.649994,470.649994,5975815
2024-01-04 11:30:00,470.660004,470.820007,469.260010,469.609985,469.609985,6137719
2024-01-04 12:30:00,469.608795,469.619995,468.665009,469.320099,469.320099,4754153
2024-01-04 13:30:00,469.329987,469.470001,468.509613,468.579895,468.579895,7022819
2024-01-04 14:30:00,468.570007,469.040009,468.070007,468.269012,468.269012,11836489
2024-01-04 15:30:00,468.260010,468.679504,467.049988,467.269989,467.269989,19959655
2024-01-05 09:30:00,467.489990,470.420013,467.130005,469.489990,469.489990,19179429
2024-01-05 10:30:00,469.470001,470.440002,469.049988,469.122009,469.122009,9241724
2024-01-05 11:30:00,469.130005,469.399994,467.234985,467.380310,467.380310,10320504
2024-01-05 12:30:00,467.230011,467.899994,466.679993,467.859985,467.859985,9917632
2024-01-05 13:30:00,467.850098,468.980011,467.850006,468.209991,468.209991,6499628
2024-01-05 14:30:00,468.200012,468.489990,466.500000,466.929993,466.929993,10134124
2024-01-05 15:30:00,466.929993,468.290009,466.429993,467.959991,467.959991,10991713
2024-01-08 09:30:00,468.429993,470.019989,468.299988,469.950012,469.950012,13184327
2024-01-08 10:30:00,469.959991,470.744995,469.959991,470.410004,470.410004,7714603
2024-01-08 11:30:00,470.410004,471.250000,470.369995,470.730011,470.730011,7068625
2024-01-08 12:30:00,470.755005,471.720001,470.679993,471.379700,471.379700,4977673
2024-01-08 13:30:00,471.375000,473.015015,471.359985,472.970001,472.970001,6753249
2024-01-08 14:30:00,472.980011,474.000000,472.980011,473.660004,473.660004,10714299
2024-01-08 15:30:00,473.660004,474.750000,473.579987,474.559998,474.559998,16777459
2024-01-09 09:30:00,471.869995,472.950104,471.350006,472.500000,472.500000,14245354
2024-01-09 10:30:00,472.489990,473.339996,472.160004,473.285004,473.285004,8060549
2024-01-09 11:30:00,473.290009,474.375000,473.079987,474.230011,474.230011,5918919
2024-01-09 12:30:00,474.239990,474.929993,473.755005,473.799988,473.799988,5510511
2024-01-09 13:30:00,473.809998,474.669891,473.149994,473.595001,473.595001,7002378
2024-01-09 14:30:00,473.600006,474.250000,473.190002,473.779999,473.779999,6075632
2024-01-09 15:30:00,473.765015,474.200012,472.929993,473.850006,473.850006,12758416
2024-01-10 09:30:00,474.160004,475.339996,473.869995,474.700012,474.700012,9892395
2024-01-10 10:30:00,474.700012,475.274994,474.424988,474.779999,474.779999,6585072
2024-01-10 11:30:00,474.790009,475.179993,474.480011,475.119995,475.119995,4659149
2024-01-10 12:30:00,475.130005,475.929901,474.810089,475.299988,475.299988,6341304
2024-01-10 13:30:00,475.309998,476.829987,475.230103,476.619995,476.619995,6882808
2024-01-10 14:30:00,476.619995,477.448090,475.885010,476.220001,476.220001,11225715
2024-01-10 15:30:00,476.239990,476.839996,475.179993,476.519989,476.519989,10955168
2024-01-11 09:30:00,477.589996,478.119995,473.570007,475.000000,475.000000,18710378
2024-01-11 10:30:00,474.989990,475.570007,472.519989,473.049988,473.049988,10100121
2024-01-11 11:30:00,473.049988,473.618988,472.260010,472.940002,472.940002,9033453
2024-01-11 12:30:00,472.959991,475.040009,472.959991,474.750000,474.750000,8047199
2024-01-11 13:30:00,474.760010,476.230011,474.610107,476.100006,476.100006,8400846
2024-01-11 14:30:00,476.109985,476.979004,475.464996,475.910004,475.910004,8034505
2024-01-11 15:30:00,475.899994,476.700012,475.540009,476.329987,476.329987,9279987
2024-01-12 09:30:00,477.839996,478.600006,475.899994,476.529999,476.529999,14830436
2024-01-12 10:30:00,476.519989,476.910095,475.230011,476.579498,476.579498,8085545
2024-01-12 11:30:00,476.579987,476.820007,475.364990,475.920013,475.920013,5283510
2024-01-12 12:30:00,475.940002,476.739990,475.609985,476.629913,476.629913,4370521
2024-01-12 13:30:00,476.640015,477.339996,476.490112,476.910004,476.910004,5334534
2024-01-12 14:30:00,476.909912,476.929993,475.760010,476.189514,476.189514,6290298
2024-01-12 15:30:00,476.190002,476.899994,476.079987,476.660004,476.660004,8577369
2024-01-16 09:30:00,475.260010,476.260010,473.470001,475.920013,475.920013,14851461
2024-01-16 10:30:00,475.920013,476.609802,474.609985,475.880310,475.880310,12233560
2024-01-16 11:30:00,475.899994,476.440002,474.339996,474.410004,474.410004,8339328
2024-01-16 12:30:00,474.269989,475.209991,473.829987,475.005005,475.005005,8238986
2024-01-16 13:30:00,475.010010,475.200012,473.059998,473.590088,473.590088,9348411
2024-01-16 14:30:00,473.595001,474.519989,473.359985,474.039886,474.039886,9610816
2024-01-16 15:30:00,474.049988,475.059998,473.774994,474.950012,474.950012,12331974
2024-01-17 09:30:00,471.820007,472.260010,471.049988,471.839996,471.839996,16757682
2024-01-17 10:30:00,471.820007,472.779999,471.500000,472.500000,472.500000,7602095
2024-01-17 11:30:00,472.464996,472.790009,471.409790,471.519989,471.519989,5870969
2024-01-17 12:30:00,471.529999,472.040009,470.450012,470.690002,470.690002,6321864
2024-01-17 13:30:00,470.690002,471.399994,469.869995,471.214996,471.214996,8235811
2024-01-17 14:30:00,471.220001,471.765015,470.670013,470.878906,470.878906,6930241
2024-01-17 15:30:00,470.880005,472.609985,470.829987,472.279999,472.279999,9858770
2024-01-18 09:30:00,474.010010,474.470001,473.390015,474.160004,474.160004,13961495
2024-01-18 10:30:00,474.195007,474.880005,473.660004,474.686615,474.686615,10106478
2024-01-18 11:30:00,474.690002,475.029999,473.040009,473.589996,473.589996,9910600
2024-01-18 12:30:00,473.600006,473.660004,472.420013,472.730011,472.730011,8595409
2024-01-18 13:30:00,472.910004,475.660004,472.869995,475.619995,475.619995,10369612
2024-01-18 14:30:00,475.619995,476.410004,474.940002,476.410004,476.410004,12426222
2024-01-18 15:30:00,476.410004,477.059998,475.899994,476.470001,476.470001,13885751
2024-01-19 09:30:00,477.649994,478.384003,476.940002,477.950012,477.950012,16562092
2024-01-19 10:30:00,477.940002,479.279999,477.339996,478.850006,478.850006,17724693
2024-01-19 11:30:00,478.845001,479.510010,478.200012,479.350006,479.350006,7718928
2024-01-19 12:30:00,479.380005,481.000000,479.279999,480.959991,480.959991,11896576
2024-01-19 13:30:00,480.950104,482.720001,480.940002,481.970001,481.970001,13806991
2024-01-19 14:30:00,481.970001,482.549988,481.329987,482.140015,482.140015,11234076
2024-01-19 15:30:00,482.140015,482.480011,481.834991,482.420013,482.420013,15288280

In [88]:
data_1d = yf.download('SPY', start = '2023-11-09', end = '2024-01-22', interval = '1d')
data_1d

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-11-09,438.429993,438.470001,433.399994,433.839996,432.088135,83174400
2023-11-10,435.980011,440.929993,433.829987,440.609985,438.830780,89462200
2023-11-13,439.230011,441.329987,438.420013,440.190002,438.412506,52236100
2023-11-14,446.320007,450.059998,446.089996,448.730011,446.918030,97176900
2023-11-15,450.109985,451.380005,448.799988,449.679993,447.864166,77327600
2023-11-16,449.220001,450.559998,448.119995,450.230011,448.411957,66665800
2023-11-17,450.239990,451.420013,449.290009,450.790009,448.969696,83133200
2023-11-20,450.529999,455.130005,450.519989,454.260010,452.425690,69936200
2023-11-21,453.179993,454.130005,451.959991,453.269989,451.439667,49244600
2023-11-22,454.980011,456.380005,453.890015,455.019989,453.182617,59394900
2023-11-24,455.070007,455.500000,454.730011,455.299988,453.461456,29737400
2023-11-27,454.649994,455.489990,454.079987,454.480011,452.644806,50506000
2023-11-28,454.079987,456.269989,453.500000,454.929993,453.092957,62115000
2023-11-29,457.149994,458.320007,454.200012,454.609985,452.774261,63146000
2023-11-30,455.480011,456.760010,453.339996,456.399994,454.557037,79752700
2023-12-01,455.769989,459.649994,455.160004,459.100006,457.246155,89097900
2023-12-04,455.600006,459.119995,454.339996,456.690002,454.845886,72430900
2023-12-05,455.260010,457.589996,454.869995,456.600006,454.756226,69793500
2023-12-06,458.809998,458.839996,454.309998,454.760010,452.923676,69124700
2023-12-07,456.910004,458.899994,456.290009,458.230011,456.379669,66995400
2023-12-08,457.459991,460.750000,457.209991,460.200012,458.341705,83080900
2023-12-11,459.690002,462.170013,459.470001,461.989990,460.124451,65002200
2023-12-12,461.630005,464.200012,460.600006,464.100006,462.225952,68327600
2023-12-13,464.489990,470.760010,464.119995,470.500000,468.600098,93278000
2023-12-14,472.500000,473.730011,469.250000,472.010010,470.104004,119026000
2023-12-15,469.489990,470.700012,467.429993,469.329987,469.329987,141319300
2023-12-18,470.980011,472.980011,469.890015,471.970001,471.970001,70375300
2023-12-19,472.529999,474.920013,472.450012,474.839996,474.839996,55761800
2023-12-20,473.959991,475.899994,467.820007,468.260010,468.260010,102921000
2023-12-21,471.329987,472.980011,468.839996,472.700012,472.700012,86667500
2023-12-22,473.859985,475.380005,471.700012,473.649994,473.649994,67126600
2023-12-26,474.070007,476.579987,473.989990,475.649994,475.649994,55387000
2023-12-27,475.440002,476.660004,474.890015,476.510010,476.510010,68000300
2023-12-28,476.880005,477.549988,476.260010,476.690002,476.690002,77158100
2023-12-29,476.489990,477.029999,473.299988,475.309998,475.309998,122234100
2024-01-02,472.160004,473.670013,470.489990,472.649994,472.649994,123623700
2024-01-03,470.429993,471.190002,468.170013,468.790009,468.790009,103585900
2024-01-04,468.299988,470.959991,467.049988,467.279999,467.279999,84232200
2024-01-05,467.489990,470.440002,466.429993,467.920013,467.920013,86060800
2024-01-08,468.429993,474.750000,468.299988,474.600006,474.600006,74879100
2024-01-09,471.869995,474.929993,471.350006,473.880005,473.880005,65931400
2024-01-10,474.160004,477.450012,473.869995,476.559998,476.559998,67310600
2024-01-11,477.589996,478.119995,472.260010,476.350006,476.350006,77940700
2024-01-12,477.839996,478.600006,475.230011,476.679993,476.679993,57944000
2024-01-16,475.260010,476.609985,473.059998,474.929993,474.929993,85014900
2024-01-17,471.820007,472.790009,469.869995,472.290009,472.290009,68843900
2024-01-18,474.010010,477.059998,472.420013,476.489990,476.489990,91856200
2024-01-19,477.649994,482.720001,476.540009,482.429993,482.429993,110733300

In [89]:
print(len(data_5m))
print(len(data_15m))
print(len(data_30m))
print(len(data_60m))
print(len(data_1d))

1560
520
260
140
48

In [90]:
#note: data_1d starts 28 days before the time of data_5m data

In [91]:
rsis_5m = talib.RSI(data_5m['Close'], timeperiod=14)
rsis_15m = talib.RSI(data_15m['Close'], timeperiod=14)
rsis_30m = talib.RSI(data_30m['Close'], timeperiod=14)
rsis_60m = talib.RSI(data_60m['Close'], timeperiod=14)

In [92]:
pd.set_option('display.max_rows', 1560)
rsis_5m

Datetime
2023-12-20 09:30:00-05:00          NaN
2023-12-20 09:35:00-05:00          NaN
2023-12-20 09:40:00-05:00          NaN
2023-12-20 09:45:00-05:00          NaN
2023-12-20 09:50:00-05:00          NaN
2023-12-20 09:55:00-05:00          NaN
2023-12-20 10:00:00-05:00          NaN
2023-12-20 10:05:00-05:00          NaN
2023-12-20 10:10:00-05:00          NaN
2023-12-20 10:15:00-05:00          NaN
2023-12-20 10:20:00-05:00          NaN
2023-12-20 10:25:00-05:00          NaN
2023-12-20 10:30:00-05:00          NaN
2023-12-20 10:35:00-05:00          NaN
2023-12-20 10:40:00-05:00    86.848731
2023-12-20 10:45:00-05:00    82.457596
2023-12-20 10:50:00-05:00    74.352376
2023-12-20 10:55:00-05:00    76.556727
2023-12-20 11:00:00-05:00    74.823675
2023-12-20 11:05:00-05:00    68.562355
2023-12-20 11:10:00-05:00    66.951688
2023-12-20 11:15:00-05:00    71.540750
2023-12-20 11:20:00-05:00    71.624033
2023-12-20 11:25:00-05:00    67.854401
2023-12-20 11:30:00-05:00    60.410593
2023-12-20 11:35:00-05:00    61.778544
2023-12-20 11:40:00-05:00    59.932558
2023-12-20 11:45:00-05:00    62.160772
2023-12-20 11:50:00-05:00    63.456167
2023-12-20 11:55:00-05:00    59.728068
2023-12-20 12:00:00-05:00    64.627681
2023-12-20 12:05:00-05:00    62.507409
2023-12-20 12:10:00-05:00    64.982576
2023-12-20 12:15:00-05:00    66.300077
2023-12-20 12:20:00-05:00    66.668069
2023-12-20 12:25:00-05:00    65.638366
2023-12-20 12:30:00-05:00    56.820653
2023-12-20 12:35:00-05:00    58.478920
2023-12-20 12:40:00-05:00    65.653137
2023-12-20 12:45:00-05:00    65.418823
2023-12-20 12:50:00-05:00    66.698004
2023-12-20 12:55:00-05:00    70.462076
2023-12-20 13:00:00-05:00    69.929567
2023-12-20 13:05:00-05:00    61.218021
2023-12-20 13:10:00-05:00    58.880585
2023-12-20 13:15:00-05:00    61.388846
2023-12-20 13:20:00-05:00    57.692243
2023-12-20 13:25:00-05:00    58.026367
2023-12-20 13:30:00-05:00    63.145931
2023-12-20 13:35:00-05:00    52.250767
2023-12-20 13:40:00-05:00    47.680949
2023-12-20 13:45:00-05:00    47.171762
2023-12-20 13:50:00-05:00    44.448579
2023-12-20 13:55:00-05:00    38.729071
2023-12-20 14:00:00-05:00    30.324599
2023-12-20 14:05:00-05:00    35.112996
2023-12-20 14:10:00-05:00    42.554377
2023-12-20 14:15:00-05:00    39.317163
2023-12-20 14:20:00-05:00    36.838587
2023-12-20 14:25:00-05:00    33.229008
2023-12-20 14:30:00-05:00    27.793450
2023-12-20 14:35:00-05:00    20.032059
2023-12-20 14:40:00-05:00    18.010014
2023-12-20 14:45:00-05:00    14.607340
2023-12-20 14:50:00-05:00    11.076568
2023-12-20 14:55:00-05:00     8.374754
2023-12-20 15:00:00-05:00     7.184168
2023-12-20 15:05:00-05:00     8.140662
2023-12-20 15:10:00-05:00     8.122611
2023-12-20 15:15:00-05:00    26.033221
2023-12-20 15:20:00-05:00    22.161784
2023-12-20 15:25:00-05:00    19.596401
2023-12-20 15:30:00-05:00    21.022539
2023-12-20 15:35:00-05:00    19.634923
2023-12-20 15:40:00-05:00    29.400696
2023-12-20 15:45:00-05:00    30.225061
2023-12-20 15:50:00-05:00    27.928736
2023-12-20 15:55:00-05:00    22.033122
2023-12-21 09:30:00-05:00    52.301375
2023-12-21 09:35:00-05:00    53.552597
2023-12-21 09:40:00-05:00    52.601729
2023-12-21 09:45:00-05:00    51.918983
2023-12-21 09:50:00-05:00    51.267568
2023-12-21 09:55:00-05:00    49.015918
2023-12-21 10:00:00-05:00    47.786113
2023-12-21 10:05:00-05:00    44.024598
2023-12-21 10:10:00-05:00    49.346284
2023-12-21 10:15:00-05:00    51.172813
2023-12-21 10:20:00-05:00    55.776371
2023-12-21 10:25:00-05:00    47.841181
2023-12-21 10:30:00-05:00    51.193286
2023-12-21 10:35:00-05:00    48.976897
2023-12-21 10:40:00-05:00    50.471159
2023-12-21 10:45:00-05:00    49.863398
2023-12-21 10:50:00-05:00    46.865637
2023-12-21 10:55:00-05:00    47.708456
2023-12-21 11:00:00-05:00    49.604815
2023-12-21 11:05:00-05:00    45.938275
2023-12-21 11:10:00-05:00    47.880259
2023-12-21 11:15:00-05:00    46.136095
2023-12-21 11:20:00-05:00    48.887493
2023-12-21 11:25:00-05:00    51.423668
2023-12-21 11:30:00-05:00    48.815164
2023-12-21 11:35:00-05:00    50.317573
2023-12-21 11:40:00-05:00    48.679418
2023-12-21 11:45:00-05:00    49.967709
2023-12-21 11:50:00-05:00    46.146615
2023-12-21 11:55:00-05:00    42.212919
2023-12-21 12:00:00-05:00    34.955072
2023-12-21 12:05:00-05:00    34.385457
2023-12-21 12:10:00-05:00    34.855882
2023-12-21 12:15:00-05:00    36.690019
2023-12-21 12:20:00-05:00    37.108213
2023-12-21 12:25:00-05:00    35.612650
2023-12-21 12:30:00-05:00    36.262138
2023-12-21 12:35:00-05:00    38.279722
2023-12-21 12:40:00-05:00    40.313866
2023-12-21 12:45:00-05:00    39.842375
2023-12-21 12:50:00-05:00    35.939027
2023-12-21 12:55:00-05:00    36.806569
2023-12-21 13:00:00-05:00    45.865736
2023-12-21 13:05:00-05:00    43.089198
2023-12-21 13:10:00-05:00    41.576405
2023-12-21 13:15:00-05:00    33.458813
2023-12-21 13:20:00-05:00    48.936560
2023-12-21 13:25:00-05:00    50.008354
2023-12-21 13:30:00-05:00    49.712718
2023-12-21 13:35:00-05:00    47.883255
2023-12-21 13:40:00-05:00    47.756948
2023-12-21 13:45:00-05:00    50.823063
2023-12-21 13:50:00-05:00    53.502272
2023-12-21 13:55:00-05:00    56.317477
2023-12-21 14:00:00-05:00    55.495314
2023-12-21 14:05:00-05:00    53.154591
2023-12-21 14:10:00-05:00    50.766676
2023-12-21 14:15:00-05:00    58.105678
2023-12-21 14:20:00-05:00    52.199939
2023-12-21 14:25:00-05:00    55.487938
2023-12-21 14:30:00-05:00    58.101932
2023-12-21 14:35:00-05:00    57.489893
2023-12-21 14:40:00-05:00    59.382628
2023-12-21 14:45:00-05:00    54.860248
2023-12-21 14:50:00-05:00    54.325610
2023-12-21 14:55:00-05:00    52.329910
2023-12-21 15:00:00-05:00    52.490399
2023-12-21 15:05:00-05:00    49.036632
2023-12-21 15:10:00-05:00    56.683865
2023-12-21 15:15:00-05:00    58.895855
2023-12-21 15:20:00-05:00    60.765183
2023-12-21 15:25:00-05:00    69.721556
2023-12-21 15:30:00-05:00    69.731102
2023-12-21 15:35:00-05:00    73.039834
2023-12-21 15:40:00-05:00    69.233296
2023-12-21 15:45:00-05:00    71.578890
2023-12-21 15:50:00-05:00    74.204986
2023-12-21 15:55:00-05:00    74.532058
2023-12-22 09:30:00-05:00    83.305909
2023-12-22 09:35:00-05:00    84.773726
2023-12-22 09:40:00-05:00    86.120428
2023-12-22 09:45:00-05:00    86.342453
2023-12-22 09:50:00-05:00    86.573847
2023-12-22 09:55:00-05:00    80.882432
2023-12-22 10:00:00-05:00    81.442015
2023-12-22 10:05:00-05:00    80.887808
2023-12-22 10:10:00-05:00    78.921088
2023-12-22 10:15:00-05:00    77.371628
2023-12-22 10:20:00-05:00    76.377685
2023-12-22 10:25:00-05:00    78.862733
2023-12-22 10:30:00-05:00    79.037316
2023-12-22 10:35:00-05:00    70.730948
2023-12-22 10:40:00-05:00    71.794918
2023-12-22 10:45:00-05:00    66.912830
2023-12-22 10:50:00-05:00    66.320650
2023-12-22 10:55:00-05:00    55.258307
2023-12-22 11:00:00-05:00    50.584790
2023-12-22 11:05:00-05:00    53.413268
2023-12-22 11:10:00-05:00    55.976511
2023-12-22 11:15:00-05:00    56.878206
2023-12-22 11:20:00-05:00    55.253397
2023-12-22 11:25:00-05:00    57.384251
2023-12-22 11:30:00-05:00    58.845294
2023-12-22 11:35:00-05:00    55.008523
2023-12-22 11:40:00-05:00    50.331301
2023-12-22 11:45:00-05:00    48.269122
2023-12-22 11:50:00-05:00    50.851301
2023-12-22 11:55:00-05:00    49.991185
2023-12-22 12:00:00-05:00    52.064538
2023-12-22 12:05:00-05:00    48.003733
2023-12-22 12:10:00-05:00    44.668464
2023-12-22 12:15:00-05:00    45.433949
2023-12-22 12:20:00-05:00    44.313663
2023-12-22 12:25:00-05:00    51.868774
2023-12-22 12:30:00-05:00    49.928852
2023-12-22 12:35:00-05:00    55.326217
2023-12-22 12:40:00-05:00    57.778435
2023-12-22 12:45:00-05:00    56.935094
2023-12-22 12:50:00-05:00    60.638042
2023-12-22 12:55:00-05:00    61.036688
2023-12-22 13:00:00-05:00    61.249306
2023-12-22 13:05:00-05:00    62.567818
2023-12-22 13:10:00-05:00    64.924571
2023-12-22 13:15:00-05:00    60.108491
2023-12-22 13:20:00-05:00    60.230797
2023-12-22 13:25:00-05:00    60.032580
2023-12-22 13:30:00-05:00    60.313033
2023-12-22 13:35:00-05:00    56.266528
2023-12-22 13:40:00-05:00    54.604475
2023-12-22 13:45:00-05:00    56.172040
2023-12-22 13:50:00-05:00    49.756210
2023-12-22 13:55:00-05:00    44.681731
2023-12-22 14:00:00-05:00    35.267599
2023-12-22 14:05:00-05:00    26.504504
2023-12-22 14:10:00-05:00    32.523494
2023-12-22 14:15:00-05:00    25.304002
2023-12-22 14:20:00-05:00    20.139399
2023-12-22 14:25:00-05:00    18.054136
2023-12-22 14:30:00-05:00    18.494287
2023-12-22 14:35:00-05:00    31.325502
2023-12-22 14:40:00-05:00    44.981320
2023-12-22 14:45:00-05:00    47.814287
2023-12-22 14:50:00-05:00    51.197269
2023-12-22 14:55:00-05:00    53.846439
2023-12-22 15:00:00-05:00    53.676656
2023-12-22 15:05:00-05:00    48.127259
2023-12-22 15:10:00-05:00    52.124783
2023-12-22 15:15:00-05:00    51.043046
2023-12-22 15:20:00-05:00    50.696709
2023-12-22 15:25:00-05:00    54.766452
2023-12-22 15:30:00-05:00    47.977033
2023-12-22 15:35:00-05:00    43.918104
2023-12-22 15:40:00-05:00    45.571097
2023-12-22 15:45:00-05:00    42.083244
2023-12-22 15:50:00-05:00    50.129696
2023-12-22 15:55:00-05:00    50.451843
2023-12-26 09:30:00-05:00    62.763219
2023-12-26 09:35:00-05:00    62.586761
2023-12-26 09:40:00-05:00    63.253636
2023-12-26 09:45:00-05:00    63.051710
2023-12-26 09:50:00-05:00    59.284878
2023-12-26 09:55:00-05:00    62.481933
2023-12-26 10:00:00-05:00    62.687853
2023-12-26 10:05:00-05:00    63.811252
2023-12-26 10:10:00-05:00    65.349939
2023-12-26 10:15:00-05:00    64.451820
2023-12-26 10:20:00-05:00    65.187616
2023-12-26 10:25:00-05:00    64.185743
2023-12-26 10:30:00-05:00    66.923075
2023-12-26 10:35:00-05:00    68.337710
2023-12-26 10:40:00-05:00    62.992701
2023-12-26 10:45:00-05:00    61.657873
2023-12-26 10:50:00-05:00    56.606467
2023-12-26 10:55:00-05:00    59.846733
2023-12-26 11:00:00-05:00    56.195211
2023-12-26 11:05:00-05:00    59.090278
2023-12-26 11:10:00-05:00    62.524918
2023-12-26 11:15:00-05:00    53.640317
2023-12-26 11:20:00-05:00    50.815246
2023-12-26 11:25:00-05:00    53.245850
2023-12-26 11:30:00-05:00    56.605529
2023-12-26 11:35:00-05:00    56.605529
2023-12-26 11:40:00-05:00    57.052670
2023-12-26 11:45:00-05:00    58.015742
2023-12-26 11:50:00-05:00    60.414821
2023-12-26 11:55:00-05:00    60.529192
2023-12-26 12:00:00-05:00    55.738228
2023-12-26 12:05:00-05:00    56.153409
2023-12-26 12:10:00-05:00    61.132072
2023-12-26 12:15:00-05:00    61.132072
2023-12-26 12:20:00-05:00    59.482656
2023-12-26 12:25:00-05:00    57.804336
2023-12-26 12:30:00-05:00    54.923891
2023-12-26 12:35:00-05:00    50.923268
2023-12-26 12:40:00-05:00    56.646954
2023-12-26 12:45:00-05:00    64.075537
2023-12-26 12:50:00-05:00    63.040591
2023-12-26 12:55:00-05:00    52.881700
2023-12-26 13:00:00-05:00    57.079595
2023-12-26 13:05:00-05:00    56.206806
2023-12-26 13:10:00-05:00    59.158741
2023-12-26 13:15:00-05:00    56.907753
2023-12-26 13:20:00-05:00    62.086131
2023-12-26 13:25:00-05:00    57.657847
2023-12-26 13:30:00-05:00    56.441627
2023-12-26 13:35:00-05:00    54.471551
2023-12-26 13:40:00-05:00    56.624843
2023-12-26 13:45:00-05:00    58.868668
2023-12-26 13:50:00-05:00    53.683335
2023-12-26 13:55:00-05:00    52.161767
2023-12-26 14:00:00-05:00    56.480503
2023-12-26 14:05:00-05:00    58.938204
2023-12-26 14:10:00-05:00    57.624322
2023-12-26 14:15:00-05:00    60.764448
2023-12-26 14:20:00-05:00    60.764448
2023-12-26 14:25:00-05:00    62.224703
2023-12-26 14:30:00-05:00    64.442687
2023-12-26 14:35:00-05:00    67.263433
2023-12-26 14:40:00-05:00    57.028406
2023-12-26 14:45:00-05:00    60.276659
2023-12-26 14:50:00-05:00    63.266928
2023-12-26 14:55:00-05:00    65.236328
2023-12-26 15:00:00-05:00    66.351115
2023-12-26 15:05:00-05:00    61.091207
2023-12-26 15:10:00-05:00    63.285108
2023-12-26 15:15:00-05:00    63.601270
2023-12-26 15:20:00-05:00    71.098558
2023-12-26 15:25:00-05:00    73.984288
2023-12-26 15:30:00-05:00    77.297040
2023-12-26 15:35:00-05:00    61.887139
2023-12-26 15:40:00-05:00    59.303540
2023-12-26 15:45:00-05:00    54.251102
2023-12-26 15:50:00-05:00    45.355647
2023-12-26 15:55:00-05:00    47.451170
2023-12-27 09:30:00-05:00    53.958634
2023-12-27 09:35:00-05:00    54.724635
2023-12-27 09:40:00-05:00    57.245037
2023-12-27 09:45:00-05:00    56.399994
2023-12-27 09:50:00-05:00    60.312655
2023-12-27 09:55:00-05:00    57.447612
2023-12-27 10:00:00-05:00    57.556136
2023-12-27 10:05:00-05:00    54.002129
2023-12-27 10:10:00-05:00    39.513865
2023-12-27 10:15:00-05:00    42.351808
2023-12-27 10:20:00-05:00    47.103664
2023-12-27 10:25:00-05:00    49.883426
2023-12-27 10:30:00-05:00    45.039218
2023-12-27 10:35:00-05:00    45.340368
2023-12-27 10:40:00-05:00    40.558191
2023-12-27 10:45:00-05:00    38.521960
2023-12-27 10:50:00-05:00    41.022760
2023-12-27 10:55:00-05:00    43.403611
2023-12-27 11:00:00-05:00    39.924663
2023-12-27 11:05:00-05:00    40.675437
2023-12-27 11:10:00-05:00    43.618508
2023-12-27 11:15:00-05:00    46.311555
2023-12-27 11:20:00-05:00    43.479058
2023-12-27 11:25:00-05:00    47.820177
2023-12-27 11:30:00-05:00    52.111619
2023-12-27 11:35:00-05:00    56.007980
2023-12-27 11:40:00-05:00    59.924235
2023-12-27 11:45:00-05:00    56.735790
2023-12-27 11:50:00-05:00    57.311087
2023-12-27 11:55:00-05:00    55.909072
2023-12-27 12:00:00-05:00    53.297895
2023-12-27 12:05:00-05:00    54.359051
2023-12-27 12:10:00-05:00    58.874276
2023-12-27 12:15:00-05:00    59.023284
2023-12-27 12:20:00-05:00    60.051449
2023-12-27 12:25:00-05:00    56.533036
2023-12-27 12:30:00-05:00    59.285642
2023-12-27 12:35:00-05:00    49.217461
2023-12-27 12:40:00-05:00    40.371012
2023-12-27 12:45:00-05:00    46.203584
2023-12-27 12:50:00-05:00    44.011103
2023-12-27 12:55:00-05:00    45.944765
2023-12-27 13:00:00-05:00    57.113329
2023-12-27 13:05:00-05:00    67.921600
2023-12-27 13:10:00-05:00    61.898969
2023-12-27 13:15:00-05:00    63.722318
2023-12-27 13:20:00-05:00    60.304299
2023-12-27 13:25:00-05:00    60.509378
2023-12-27 13:30:00-05:00    60.006531
2023-12-27 13:35:00-05:00    61.947926
2023-12-27 13:40:00-05:00    64.770072
2023-12-27 13:45:00-05:00    62.878097
2023-12-27 13:50:00-05:00    59.408066
2023-12-27 13:55:00-05:00    50.224120
2023-12-27 14:00:00-05:00    32.600728
2023-12-27 14:05:00-05:00    38.464799
2023-12-27 14:10:00-05:00    35.158675
2023-12-27 14:15:00-05:00    42.342387
2023-12-27 14:20:00-05:00    47.225662
2023-12-27 14:25:00-05:00    50.003136
2023-12-27 14:30:00-05:00    45.648917
2023-12-27 14:35:00-05:00    44.136052
2023-12-27 14:40:00-05:00    41.658048
2023-12-27 14:45:00-05:00    44.351847
2023-12-27 14:50:00-05:00    40.802475
2023-12-27 14:55:00-05:00    46.901645
2023-12-27 15:00:00-05:00    49.880673
2023-12-27 15:05:00-05:00    51.063367
2023-12-27 15:10:00-05:00    50.422677
2023-12-27 15:15:00-05:00    53.165185
2023-12-27 15:20:00-05:00    48.497772
2023-12-27 15:25:00-05:00    49.296719
2023-12-27 15:30:00-05:00    53.205505
2023-12-27 15:35:00-05:00    54.916093
2023-12-27 15:40:00-05:00    43.919961
2023-12-27 15:45:00-05:00    44.123802
2023-12-27 15:50:00-05:00    47.245518
2023-12-27 15:55:00-05:00    63.698415
2023-12-28 09:30:00-05:00    69.889754
2023-12-28 09:35:00-05:00    70.870810
2023-12-28 09:40:00-05:00    63.571331
2023-12-28 09:45:00-05:00    65.982038
2023-12-28 09:50:00-05:00    66.294369
2023-12-28 09:55:00-05:00    67.057817
2023-12-28 10:00:00-05:00    63.102799
2023-12-28 10:05:00-05:00    61.585065
2023-12-28 10:10:00-05:00    61.132161
2023-12-28 10:15:00-05:00    61.887013
2023-12-28 10:20:00-05:00    63.709038
2023-12-28 10:25:00-05:00    66.293484
2023-12-28 10:30:00-05:00    67.225761
2023-12-28 10:35:00-05:00    64.696274
2023-12-28 10:40:00-05:00    64.456252
2023-12-28 10:45:00-05:00    68.120348
2023-12-28 10:50:00-05:00    62.608394
2023-12-28 10:55:00-05:00    56.959105
2023-12-28 11:00:00-05:00    54.534207
2023-12-28 11:05:00-05:00    54.403604
2023-12-28 11:10:00-05:00    54.638306
2023-12-28 11:15:00-05:00    46.174410
2023-12-28 11:20:00-05:00    49.493855
2023-12-28 11:25:00-05:00    51.220895
2023-12-28 11:30:00-05:00    49.920865
2023-12-28 11:35:00-05:00    51.534291
2023-12-28 11:40:00-05:00    54.218993
2023-12-28 11:45:00-05:00    54.190636
2023-12-28 11:50:00-05:00    54.480618
2023-12-28 11:55:00-05:00    50.367597
2023-12-28 12:00:00-05:00    56.807301
2023-12-28 12:05:00-05:00    56.944240
2023-12-28 12:10:00-05:00    52.469917
2023-12-28 12:15:00-05:00    54.325004
2023-12-28 12:20:00-05:00    53.943269
2023-12-28 12:25:00-05:00    50.013343
2023-12-28 12:30:00-05:00    56.658849
2023-12-28 12:35:00-05:00    57.256513
2023-12-28 12:40:00-05:00    59.130068
2023-12-28 12:45:00-05:00    54.287104
2023-12-28 12:50:00-05:00    60.672736
2023-12-28 12:55:00-05:00    60.213715
2023-12-28 13:00:00-05:00    43.847432
2023-12-28 13:05:00-05:00    50.264416
2023-12-28 13:10:00-05:00    47.500837
2023-12-28 13:15:00-05:00    53.672690
2023-12-28 13:20:00-05:00    55.594326
2023-12-28 13:25:00-05:00    50.774284
2023-12-28 13:30:00-05:00    54.289068
2023-12-28 13:35:00-05:00    57.335810
2023-12-28 13:40:00-05:00    50.874913
2023-12-28 13:45:00-05:00    48.325873
2023-12-28 13:50:00-05:00    51.345463
2023-12-28 13:55:00-05:00    49.318391
2023-12-28 14:00:00-05:00    54.886276
2023-12-28 14:05:00-05:00    53.780095
2023-12-28 14:10:00-05:00    55.806596
2023-12-28 14:15:00-05:00    54.205954
2023-12-28 14:20:00-05:00    56.614234
2023-12-28 14:25:00-05:00    57.418104
2023-12-28 14:30:00-05:00    54.689408
2023-12-28 14:35:00-05:00    57.172847
2023-12-28 14:40:00-05:00    53.115698
2023-12-28 14:45:00-05:00    55.141761
2023-12-28 14:50:00-05:00    48.081192
2023-12-28 14:55:00-05:00    50.891262
2023-12-28 15:00:00-05:00    46.584189
2023-12-28 15:05:00-05:00    47.817290
2023-12-28 15:10:00-05:00    41.726970
2023-12-28 15:15:00-05:00    49.055129
2023-12-28 15:20:00-05:00    44.701197
2023-12-28 15:25:00-05:00    43.363652
2023-12-28 15:30:00-05:00    45.807788
2023-12-28 15:35:00-05:00    51.577968
2023-12-28 15:40:00-05:00    55.952922
2023-12-28 15:45:00-05:00    46.496985
2023-12-28 15:50:00-05:00    35.854820
2023-12-28 15:55:00-05:00    41.808676
2023-12-29 09:30:00-05:00    45.474692
2023-12-29 09:35:00-05:00    46.982045
2023-12-29 09:40:00-05:00    46.757346
2023-12-29 09:45:00-05:00    44.038252
2023-12-29 09:50:00-05:00    44.329088
2023-12-29 09:55:00-05:00    44.329088
2023-12-29 10:00:00-05:00    46.580007
2023-12-29 10:05:00-05:00    44.240331
2023-12-29 10:10:00-05:00    40.502792
2023-12-29 10:15:00-05:00    43.002329
2023-12-29 10:20:00-05:00    38.968864
2023-12-29 10:25:00-05:00    45.662405
2023-12-29 10:30:00-05:00    37.394504
2023-12-29 10:35:00-05:00    35.053606
2023-12-29 10:40:00-05:00    29.963208
2023-12-29 10:45:00-05:00    24.491736
2023-12-29 10:50:00-05:00    22.984756
2023-12-29 10:55:00-05:00    27.479359
2023-12-29 11:00:00-05:00    32.741666
2023-12-29 11:05:00-05:00    28.251444
2023-12-29 11:10:00-05:00    23.192607
2023-12-29 11:15:00-05:00    22.173967
2023-12-29 11:20:00-05:00    19.712549
2023-12-29 11:25:00-05:00    17.607665
2023-12-29 11:30:00-05:00    18.180208
2023-12-29 11:35:00-05:00    23.052929
2023-12-29 11:40:00-05:00    22.888678
2023-12-29 11:45:00-05:00    31.683813
2023-12-29 11:50:00-05:00    30.284539
2023-12-29 11:55:00-05:00    28.909575
2023-12-29 12:00:00-05:00    28.675659
2023-12-29 12:05:00-05:00    25.759399
2023-12-29 12:10:00-05:00    23.307924
2023-12-29 12:15:00-05:00    28.029231
2023-12-29 12:20:00-05:00    25.395597
2023-12-29 12:25:00-05:00    25.696525
2023-12-29 12:30:00-05:00    32.839704
2023-12-29 12:35:00-05:00    36.208098
2023-12-29 12:40:00-05:00    39.352661
2023-12-29 12:45:00-05:00    38.007716
2023-12-29 12:50:00-05:00    42.955803
2023-12-29 12:55:00-05:00    49.648668
2023-12-29 13:00:00-05:00    54.571442
2023-12-29 13:05:00-05:00    56.756811

In [93]:
rsis_1d = talib.RSI(data_1d['Close'], timeperiod=14)

In [94]:
rsis_1d

Date
2023-11-09          NaN
2023-11-10          NaN
2023-11-13          NaN
2023-11-14          NaN
2023-11-15          NaN
2023-11-16          NaN
2023-11-17          NaN
2023-11-20          NaN
2023-11-21          NaN
2023-11-22          NaN
2023-11-24          NaN
2023-11-27          NaN
2023-11-28          NaN
2023-11-29          NaN
2023-11-30    90.780946
2023-12-01    91.657895
2023-12-04    83.979056
2023-12-05    83.697069
2023-12-06    77.935152
2023-12-07    80.641731
2023-12-08    81.992250
2023-12-11    83.142998
2023-12-12    84.407877
2023-12-13    87.477234
2023-12-14    88.073761
2023-12-15    80.723951
2023-12-18    82.291642
2023-12-19    83.831147
2023-12-20    69.016699
2023-12-21    72.542688
2023-12-22    73.244283
2023-12-26    74.709448
2023-12-27    75.334927
2023-12-28    75.471655
2023-12-29    72.168478
2024-01-02    66.157903
2024-01-03    58.538853
2024-01-04    55.830119
2024-01-05    56.743740
2024-01-08    64.903453
2024-01-09    63.512768
2024-01-10    66.398799
2024-01-11    65.958564
2024-01-12    66.336280
2024-01-16    62.383065
2024-01-17    56.876507
2024-01-18    62.541446
2024-01-19    68.786638
dtype: float64

In [95]:
rsismas_5m = talib.SMA(rsis_5m, timeperiod=14)
rsismas_15m = talib.SMA(rsis_15m, timeperiod=14)
rsismas_30m = talib.SMA(rsis_30m, timeperiod=14)
rsismas_60m = talib.SMA(rsis_60m, timeperiod=14)

In [96]:
rsismas_5m

Datetime
2023-12-20 09:30:00-05:00          NaN
2023-12-20 09:35:00-05:00          NaN
2023-12-20 09:40:00-05:00          NaN
2023-12-20 09:45:00-05:00          NaN
2023-12-20 09:50:00-05:00          NaN
2023-12-20 09:55:00-05:00          NaN
2023-12-20 10:00:00-05:00          NaN
2023-12-20 10:05:00-05:00          NaN
2023-12-20 10:10:00-05:00          NaN
2023-12-20 10:15:00-05:00          NaN
2023-12-20 10:20:00-05:00          NaN
2023-12-20 10:25:00-05:00          NaN
2023-12-20 10:30:00-05:00          NaN
2023-12-20 10:35:00-05:00          NaN
2023-12-20 10:40:00-05:00          NaN
2023-12-20 10:45:00-05:00          NaN
2023-12-20 10:50:00-05:00          NaN
2023-12-20 10:55:00-05:00          NaN
2023-12-20 11:00:00-05:00          NaN
2023-12-20 11:05:00-05:00          NaN
2023-12-20 11:10:00-05:00          NaN
2023-12-20 11:15:00-05:00          NaN
2023-12-20 11:20:00-05:00          NaN
2023-12-20 11:25:00-05:00          NaN
2023-12-20 11:30:00-05:00          NaN
2023-12-20 11:35:00-05:00          NaN
2023-12-20 11:40:00-05:00          NaN
2023-12-20 11:45:00-05:00    70.418200
2023-12-20 11:50:00-05:00    68.747302
2023-12-20 11:55:00-05:00    67.123765
2023-12-20 12:00:00-05:00    66.429144
2023-12-20 12:05:00-05:00    65.425621
2023-12-20 12:10:00-05:00    64.722685
2023-12-20 12:15:00-05:00    64.561094
2023-12-20 12:20:00-05:00    64.540835
2023-12-20 12:25:00-05:00    64.119237
2023-12-20 12:30:00-05:00    63.061852
2023-12-20 12:35:00-05:00    62.392175
2023-12-20 12:40:00-05:00    62.766643
2023-12-20 12:45:00-05:00    63.026662
2023-12-20 12:50:00-05:00    63.509909
2023-12-20 12:55:00-05:00    64.102859
2023-12-20 13:00:00-05:00    64.565245
2023-12-20 13:05:00-05:00    64.671670
2023-12-20 13:10:00-05:00    64.261163
2023-12-20 13:15:00-05:00    64.181266
2023-12-20 13:20:00-05:00    63.660528
2023-12-20 13:25:00-05:00    63.069548
2023-12-20 13:30:00-05:00    62.817967
2023-12-20 13:35:00-05:00    61.861710
2023-12-20 13:40:00-05:00    61.208874
2023-12-20 13:45:00-05:00    60.401220
2023-12-20 13:50:00-05:00    58.886609
2023-12-20 13:55:00-05:00    56.980198
2023-12-20 14:00:00-05:00    54.382097
2023-12-20 14:05:00-05:00    51.857163
2023-12-20 14:10:00-05:00    49.901792
2023-12-20 14:15:00-05:00    48.337445
2023-12-20 14:20:00-05:00    46.763017
2023-12-20 14:25:00-05:00    44.751600
2023-12-20 14:30:00-05:00    42.615972
2023-12-20 14:35:00-05:00    39.902093
2023-12-20 14:40:00-05:00    36.678099
2023-12-20 14:45:00-05:00    33.989282
2023-12-20 14:50:00-05:00    31.374684
2023-12-20 14:55:00-05:00    28.603469
2023-12-20 15:00:00-05:00    25.941725
2023-12-20 15:05:00-05:00    23.756839
2023-12-20 15:10:00-05:00    22.170983
2023-12-20 15:15:00-05:00    21.522427
2023-12-20 15:20:00-05:00    20.065813
2023-12-20 15:25:00-05:00    18.657188
2023-12-20 15:30:00-05:00    17.527470
2023-12-20 15:35:00-05:00    16.556464
2023-12-20 15:40:00-05:00    16.671267
2023-12-20 15:45:00-05:00    17.399339
2023-12-20 15:50:00-05:00    18.107819
2023-12-20 15:55:00-05:00    18.638232
2023-12-21 09:30:00-05:00    21.582861
2023-12-21 09:35:00-05:00    24.809850
2023-12-21 09:40:00-05:00    28.053961
2023-12-21 09:45:00-05:00    31.180984
2023-12-21 09:50:00-05:00    34.262767
2023-12-21 09:55:00-05:00    35.904388
2023-12-21 10:00:00-05:00    37.734697
2023-12-21 10:05:00-05:00    39.479568
2023-12-21 10:10:00-05:00    41.502693
2023-12-21 10:15:00-05:00    43.755399
2023-12-21 10:20:00-05:00    45.639376
2023-12-21 10:25:00-05:00    46.897671
2023-12-21 10:30:00-05:00    48.559424
2023-12-21 10:35:00-05:00    50.483980
2023-12-21 10:40:00-05:00    50.353250
2023-12-21 10:45:00-05:00    50.089736
2023-12-21 10:50:00-05:00    49.680015
2023-12-21 10:55:00-05:00    49.379263
2023-12-21 11:00:00-05:00    49.260495
2023-12-21 11:05:00-05:00    49.040663
2023-12-21 11:10:00-05:00    49.047388
2023-12-21 11:15:00-05:00    49.198209
2023-12-21 11:20:00-05:00    49.165438
2023-12-21 11:25:00-05:00    49.183356
2023-12-21 11:30:00-05:00    48.686127
2023-12-21 11:35:00-05:00    48.863013
2023-12-21 11:40:00-05:00    48.683451
2023-12-21 11:45:00-05:00    48.754223
2023-12-21 11:50:00-05:00    48.445327
2023-12-21 11:55:00-05:00    47.898864
2023-12-21 12:00:00-05:00    47.048109
2023-12-21 12:05:00-05:00    46.096467
2023-12-21 12:10:00-05:00    45.042971
2023-12-21 12:15:00-05:00    44.382382
2023-12-21 12:20:00-05:00    43.612950
2023-12-21 12:25:00-05:00    42.861275
2023-12-21 12:30:00-05:00    41.959464
2023-12-21 12:35:00-05:00    41.020611
2023-12-21 12:40:00-05:00    40.413375
2023-12-21 12:45:00-05:00    39.665147
2023-12-21 12:50:00-05:00    38.755119
2023-12-21 12:55:00-05:00    37.815038
2023-12-21 13:00:00-05:00    37.794975
2023-12-21 13:05:00-05:00    37.857566
2023-12-21 13:10:00-05:00    38.330518
2023-12-21 13:15:00-05:00    38.264330
2023-12-21 13:20:00-05:00    39.270092
2023-12-21 13:25:00-05:00    40.221402
2023-12-21 13:30:00-05:00    41.121724
2023-12-21 13:35:00-05:00    41.998195
2023-12-21 13:40:00-05:00    42.819253
2023-12-21 13:45:00-05:00    43.715206
2023-12-21 13:50:00-05:00    44.657235
2023-12-21 13:55:00-05:00    45.834028
2023-12-21 14:00:00-05:00    47.230906
2023-12-21 14:05:00-05:00    48.398622
2023-12-21 14:10:00-05:00    48.748689
2023-12-21 14:15:00-05:00    49.821294
2023-12-21 14:20:00-05:00    50.580118
2023-12-21 14:25:00-05:00    52.153627
2023-12-21 14:30:00-05:00    52.808297
2023-12-21 14:35:00-05:00    53.342692
2023-12-21 14:40:00-05:00    54.033400
2023-12-21 14:45:00-05:00    54.531757
2023-12-21 14:50:00-05:00    55.000947
2023-12-21 14:55:00-05:00    55.108579
2023-12-21 15:00:00-05:00    55.036302
2023-12-21 15:05:00-05:00    54.516242
2023-12-21 15:10:00-05:00    54.601138
2023-12-21 15:15:00-05:00    55.011229
2023-12-21 15:20:00-05:00    55.725408
2023-12-21 15:25:00-05:00    56.555113
2023-12-21 15:30:00-05:00    57.807339
2023-12-21 15:35:00-05:00    59.061046
2023-12-21 15:40:00-05:00    59.856144
2023-12-21 15:45:00-05:00    60.862501
2023-12-21 15:50:00-05:00    61.921240
2023-12-21 15:55:00-05:00    63.326370
2023-12-22 09:30:00-05:00    65.396391
2023-12-22 09:35:00-05:00    67.713807
2023-12-22 09:40:00-05:00    70.115951
2023-12-22 09:45:00-05:00    72.780653
2023-12-22 09:50:00-05:00    74.915652
2023-12-22 09:55:00-05:00    76.486121
2023-12-22 10:00:00-05:00    77.963038
2023-12-22 10:05:00-05:00    78.760627
2023-12-22 10:10:00-05:00    79.417055
2023-12-22 10:15:00-05:00    79.726469
2023-12-22 10:20:00-05:00    80.236782
2023-12-22 10:25:00-05:00    80.757057
2023-12-22 10:30:00-05:00    81.102223
2023-12-22 10:35:00-05:00    80.830715
2023-12-22 10:40:00-05:00    80.008502
2023-12-22 10:45:00-05:00    78.732723
2023-12-22 10:50:00-05:00    77.318454
2023-12-22 10:55:00-05:00    75.098157
2023-12-22 11:00:00-05:00    72.527510
2023-12-22 11:05:00-05:00    70.565427
2023-12-22 11:10:00-05:00    68.746463
2023-12-22 11:15:00-05:00    67.031491
2023-12-22 11:20:00-05:00    65.340942
2023-12-22 11:25:00-05:00    63.913272
2023-12-22 11:30:00-05:00    62.660959
2023-12-22 11:35:00-05:00    60.957086
2023-12-22 11:40:00-05:00    58.906657
2023-12-22 11:45:00-05:00    57.302241
2023-12-22 11:50:00-05:00    55.806268
2023-12-22 11:55:00-05:00    54.597579
2023-12-22 12:00:00-05:00    53.579285
2023-12-22 12:05:00-05:00    53.061101
2023-12-22 12:10:00-05:00    52.638507
2023-12-22 12:15:00-05:00    52.068555
2023-12-22 12:20:00-05:00    51.235495
2023-12-22 12:25:00-05:00    50.877678
2023-12-22 12:30:00-05:00    50.497354
2023-12-22 12:35:00-05:00    50.350351
2023-12-22 12:40:00-05:00    50.274147
2023-12-22 12:45:00-05:00    50.411759
2023-12-22 12:50:00-05:00    51.147955
2023-12-22 12:55:00-05:00    52.059924
2023-12-22 13:00:00-05:00    52.802639
2023-12-22 13:05:00-05:00    53.700970
2023-12-22 13:10:00-05:00    54.619543
2023-12-22 13:15:00-05:00    55.484169
2023-12-22 13:20:00-05:00    56.595764
2023-12-22 13:25:00-05:00    57.638523
2023-12-22 13:30:00-05:00    58.781336
2023-12-22 13:35:00-05:00    59.095461
2023-12-22 13:40:00-05:00    59.429434
2023-12-22 13:45:00-05:00    59.489850
2023-12-22 13:50:00-05:00    58.916834
2023-12-22 13:55:00-05:00    58.041593
2023-12-22 14:00:00-05:00    56.229419
2023-12-22 14:05:00-05:00    53.762834
2023-12-22 14:10:00-05:00    51.710991
2023-12-22 14:15:00-05:00    49.049289
2023-12-22 14:20:00-05:00    45.850349
2023-12-22 14:25:00-05:00    42.846466
2023-12-22 14:30:00-05:00    39.865287
2023-12-22 14:35:00-05:00    37.814781
2023-12-22 14:40:00-05:00    36.719659
2023-12-22 14:45:00-05:00    36.115927
2023-12-22 14:50:00-05:00    35.872556
2023-12-22 14:55:00-05:00    35.706441
2023-12-22 15:00:00-05:00    35.986473
2023-12-22 15:05:00-05:00    36.232582
2023-12-22 15:10:00-05:00    37.436667
2023-12-22 15:15:00-05:00    39.189420
2023-12-22 15:20:00-05:00    40.487507
2023-12-22 15:25:00-05:00    42.591967
2023-12-22 15:30:00-05:00    44.580370
2023-12-22 15:35:00-05:00    46.427796
2023-12-22 15:40:00-05:00    48.361854
2023-12-22 15:45:00-05:00    49.130264
2023-12-22 15:50:00-05:00    49.498005
2023-12-22 15:55:00-05:00    49.686402
2023-12-26 09:30:00-05:00    50.512541
2023-12-26 09:35:00-05:00    51.136850
2023-12-26 09:40:00-05:00    51.820920
2023-12-26 09:45:00-05:00    52.886952
2023-12-26 09:50:00-05:00    53.398388
2023-12-26 09:55:00-05:00    54.215451
2023-12-26 10:00:00-05:00    55.071961
2023-12-26 10:05:00-05:00    55.718019
2023-12-26 10:10:00-05:00    56.958940
2023-12-26 10:15:00-05:00    58.425634
2023-12-26 10:20:00-05:00    59.826814
2023-12-26 10:25:00-05:00    61.405564
2023-12-26 10:30:00-05:00    62.605091
2023-12-26 10:35:00-05:00    63.882653
2023-12-26 10:40:00-05:00    63.899045
2023-12-26 10:45:00-05:00    63.832696
2023-12-26 10:50:00-05:00    63.357898
2023-12-26 10:55:00-05:00    63.128971
2023-12-26 11:00:00-05:00    62.908281
2023-12-26 11:05:00-05:00    62.666019
2023-12-26 11:10:00-05:00    62.654381
2023-12-26 11:15:00-05:00    61.927886
2023-12-26 11:20:00-05:00    60.889693
2023-12-26 11:25:00-05:00    60.089267
2023-12-26 11:30:00-05:00    59.476261
2023-12-26 11:35:00-05:00    58.934817
2023-12-26 11:40:00-05:00    58.229788
2023-12-26 11:45:00-05:00    57.492505
2023-12-26 11:50:00-05:00    57.308370
2023-12-26 11:55:00-05:00    57.227750
2023-12-26 12:00:00-05:00    57.165733
2023-12-26 12:05:00-05:00    56.901924
2023-12-26 12:10:00-05:00    57.254557
2023-12-26 12:15:00-05:00    57.400400
2023-12-26 12:20:00-05:00    57.183095
2023-12-26 12:25:00-05:00    57.480525
2023-12-26 12:30:00-05:00    57.774000
2023-12-26 12:35:00-05:00    57.608101
2023-12-26 12:40:00-05:00    57.611060
2023-12-26 12:45:00-05:00    58.144632
2023-12-26 12:50:00-05:00    58.572341
2023-12-26 12:55:00-05:00    58.205623
2023-12-26 13:00:00-05:00    57.967393
2023-12-26 13:05:00-05:00    57.658651
2023-12-26 13:10:00-05:00    57.902973
2023-12-26 13:15:00-05:00    57.956855
2023-12-26 13:20:00-05:00    58.025002
2023-12-26 13:25:00-05:00    57.776843
2023-12-26 13:30:00-05:00    57.559627
2023-12-26 13:35:00-05:00    57.321571
2023-12-26 13:40:00-05:00    57.443067
2023-12-26 13:45:00-05:00    58.010596
2023-12-26 13:50:00-05:00    57.798909
2023-12-26 13:55:00-05:00    56.947925
2023-12-26 14:00:00-05:00    56.479348
2023-12-26 14:05:00-05:00    56.911955
2023-12-26 14:10:00-05:00    56.950864
2023-12-26 14:15:00-05:00    57.276410
2023-12-26 14:20:00-05:00    57.391103
2023-12-26 14:25:00-05:00    57.770885
2023-12-26 14:30:00-05:00    57.939211
2023-12-26 14:35:00-05:00    58.625324
2023-12-26 14:40:00-05:00    58.667237
2023-12-26 14:45:00-05:00    59.081887
2023-12-26 14:50:00-05:00    59.556322
2023-12-26 14:55:00-05:00    60.011155
2023-12-26 15:00:00-05:00    60.915996
2023-12-26 15:05:00-05:00    61.553814
2023-12-26 15:10:00-05:00    62.039857
2023-12-26 15:15:00-05:00    62.372933
2023-12-26 15:20:00-05:00    63.335378
2023-12-26 15:25:00-05:00    64.279653
2023-12-26 15:30:00-05:00    65.460552
2023-12-26 15:35:00-05:00    65.436440
2023-12-26 15:40:00-05:00    65.069359
2023-12-26 15:45:00-05:00    64.139906
2023-12-26 15:50:00-05:00    63.306138
2023-12-26 15:55:00-05:00    62.390031
2023-12-27 09:30:00-05:00    61.725153
2023-12-27 09:35:00-05:00    60.974318
2023-12-27 09:40:00-05:00    60.323884
2023-12-27 09:45:00-05:00    59.988797
2023-12-27 09:50:00-05:00    59.776479
2023-12-27 09:55:00-05:00    59.336932
2023-12-27 10:00:00-05:00    58.369616
2023-12-27 10:05:00-05:00    56.942319
2023-12-27 10:10:00-05:00    54.243521
2023-12-27 10:15:00-05:00    52.848140
2023-12-27 10:20:00-05:00    51.976721
2023-12-27 10:25:00-05:00    51.664744
2023-12-27 10:30:00-05:00    51.642142
2023-12-27 10:35:00-05:00    51.491370
2023-12-27 10:40:00-05:00    50.534196
2023-12-27 10:45:00-05:00    49.376862
2023-12-27 10:50:00-05:00    48.218128
2023-12-27 10:55:00-05:00    47.289815
2023-12-27 11:00:00-05:00    45.833529
2023-12-27 11:05:00-05:00    44.635517
2023-12-27 11:10:00-05:00    43.639972
2023-12-27 11:15:00-05:00    43.090645
2023-12-27 11:20:00-05:00    43.373873
2023-12-27 11:25:00-05:00    43.764471
2023-12-27 11:30:00-05:00    44.122182
2023-12-27 11:35:00-05:00    44.559650
2023-12-27 11:40:00-05:00    45.622866
2023-12-27 11:45:00-05:00    46.436825
2023-12-27 11:50:00-05:00    47.633460
2023-12-27 11:55:00-05:00    48.875397
2023-12-27 12:00:00-05:00    49.752192
2023-12-27 12:05:00-05:00    50.534723
2023-12-27 12:10:00-05:00    51.888267
2023-12-27 12:15:00-05:00    53.198828
2023-12-27 12:20:00-05:00    54.372609
2023-12-27 12:25:00-05:00    55.102715
2023-12-27 12:30:00-05:00    56.231757
2023-12-27 12:35:00-05:00    56.331563
2023-12-27 12:40:00-05:00    55.492948
2023-12-27 12:45:00-05:00    54.792634
2023-12-27 12:50:00-05:00    53.655982
2023-12-27 12:55:00-05:00    52.885194
2023-12-27 13:00:00-05:00    52.871069
2023-12-27 13:05:00-05:00    53.729106
2023-12-27 13:10:00-05:00    54.343469
2023-12-27 13:15:00-05:00    55.012273
2023-12-27 13:20:00-05:00    55.114418
2023-12-27 13:25:00-05:00    55.220568
2023-12-27 13:30:00-05:00    55.217359
2023-12-27 13:35:00-05:00    55.604137
2023-12-27 13:40:00-05:00    55.995882
2023-12-27 13:45:00-05:00    56.971642
2023-12-27 13:50:00-05:00    58.331431
2023-12-27 13:55:00-05:00    58.618612
2023-12-27 14:00:00-05:00    57.803586
2023-12-27 14:05:00-05:00    57.269302
2023-12-27 14:10:00-05:00    55.701113
2023-12-27 14:15:00-05:00    53.874026
2023-12-27 14:20:00-05:00    52.825933
2023-12-27 14:25:00-05:00    51.845991
2023-12-27 14:30:00-05:00    50.799178
2023-12-27 14:35:00-05:00    49.629655
2023-12-27 14:40:00-05:00    48.319049
2023-12-27 14:45:00-05:00    47.062186
2023-12-27 14:50:00-05:00    45.350215
2023-12-27 14:55:00-05:00    44.209040
2023-12-27 15:00:00-05:00    43.528512
2023-12-27 15:05:00-05:00    43.588458
2023-12-27 15:10:00-05:00    44.861454
2023-12-27 15:15:00-05:00    45.911482
2023-12-27 15:20:00-05:00    46.864274
2023-12-27 15:25:00-05:00    47.361013
2023-12-27 15:30:00-05:00    47.788144
2023-12-27 15:35:00-05:00    48.139070
2023-12-27 15:40:00-05:00    48.015573
2023-12-27 15:45:00-05:00    48.014698
2023-12-27 15:50:00-05:00    48.413803
2023-12-27 15:55:00-05:00    49.795700
2023-12-28 09:30:00-05:00    51.873363
2023-12-28 09:35:00-05:00    53.585446
2023-12-28 09:40:00-05:00    54.563351
2023-12-28 09:45:00-05:00    55.628970
2023-12-28 09:50:00-05:00    56.762662
2023-12-28 09:55:00-05:00    57.754993
2023-12-28 10:00:00-05:00    58.798209
2023-12-28 10:05:00-05:00    59.675948
2023-12-28 10:10:00-05:00    60.242138
2023-12-28 10:15:00-05:00    60.740061
2023-12-28 10:20:00-05:00    62.153566
2023-12-28 10:25:00-05:00    63.737115
2023-12-28 10:30:00-05:00    65.164275
2023-12-28 10:35:00-05:00    65.235551
2023-12-28 10:40:00-05:00    64.847444
2023-12-28 10:45:00-05:00    64.650982
2023-12-28 10:50:00-05:00    64.582201
2023-12-28 10:55:00-05:00    63.937706
2023-12-28 11:00:00-05:00    63.097694
2023-12-28 11:05:00-05:00    62.193822
2023-12-28 11:10:00-05:00    61.589215
2023-12-28 11:15:00-05:00    60.488454
2023-12-28 11:20:00-05:00    59.657146
2023-12-28 11:25:00-05:00    58.895281
2023-12-28 11:30:00-05:00    57.910411
2023-12-28 11:35:00-05:00    56.856183
2023-12-28 11:40:00-05:00    55.927128
2023-12-28 11:45:00-05:00    55.176726
2023-12-28 11:50:00-05:00    54.464180
2023-12-28 11:55:00-05:00    53.196127
2023-12-28 12:00:00-05:00    52.781763
2023-12-28 12:05:00-05:00    52.780701
2023-12-28 12:10:00-05:00    52.633252
2023-12-28 12:15:00-05:00    52.627638
2023-12-28 12:20:00-05:00    52.577992
2023-12-28 12:25:00-05:00    52.852202
2023-12-28 12:30:00-05:00    53.363987
2023-12-28 12:35:00-05:00    53.795103
2023-12-28 12:40:00-05:00    54.452903
2023-12-28 12:45:00-05:00    54.649532
2023-12-28 12:50:00-05:00    55.110514
2023-12-28 12:55:00-05:00    55.540734
2023-12-28 13:00:00-05:00    54.781220
2023-12-28 13:05:00-05:00    54.773850
2023-12-28 13:10:00-05:00    54.109103
2023-12-28 13:15:00-05:00    53.875421
2023-12-28 13:20:00-05:00    54.098593
2023-12-28 13:25:00-05:00    53.844970
2023-12-28 13:30:00-05:00    53.869670
2023-12-28 13:35:00-05:00    54.392704
2023-12-28 13:40:00-05:00    53.979565
2023-12-28 13:45:00-05:00    53.341662
2023-12-28 13:50:00-05:00    52.785619
2023-12-28 13:55:00-05:00    52.430711
2023-12-28 14:00:00-05:00    52.017392
2023-12-28 14:05:00-05:00    51.557848
2023-12-28 14:10:00-05:00    52.412074
2023-12-28 14:15:00-05:00    52.693613
2023-12-28 14:20:00-05:00    53.344570
2023-12-28 14:25:00-05:00    53.612099
2023-12-28 14:30:00-05:00    53.547462
2023-12-28 14:35:00-05:00    54.004502
2023-12-28 14:40:00-05:00    53.920690
2023-12-28 14:45:00-05:00    53.763972
2023-12-28 14:50:00-05:00    53.564421
2023-12-28 14:55:00-05:00    53.747663
2023-12-28 15:00:00-05:00    53.407572
2023-12-28 15:05:00-05:00    53.300350
2023-12-28 15:10:00-05:00    52.360400
2023-12-28 15:15:00-05:00    52.022902
2023-12-28 15:20:00-05:00    51.229660
2023-12-28 15:25:00-05:00    50.455209
2023-12-28 15:30:00-05:00    49.683320
2023-12-28 15:35:00-05:00    49.266168
2023-12-28 15:40:00-05:00    49.356419
2023-12-28 15:45:00-05:00    48.593857
2023-12-28 15:50:00-05:00    47.360937
2023-12-28 15:55:00-05:00    46.408574
2023-12-29 09:30:00-05:00    46.222396
2023-12-29 09:35:00-05:00    45.943166
2023-12-29 09:40:00-05:00    45.955534
2023-12-29 09:45:00-05:00    45.685603
2023-12-29 09:50:00-05:00    45.871469
2023-12-29 09:55:00-05:00    45.533894
2023-12-29 10:00:00-05:00    45.668095
2023-12-29 10:05:00-05:00    45.730715
2023-12-29 10:10:00-05:00    45.351786
2023-12-29 10:15:00-05:00    44.739241
2023-12-29 10:20:00-05:00    43.526094
2023-12-29 10:25:00-05:00    43.466481
2023-12-29 10:30:00-05:00    43.576458
2023-12-29 10:35:00-05:00    43.093953
2023-12-29 10:40:00-05:00    41.985990
2023-12-29 10:45:00-05:00    40.379540
2023-12-29 10:50:00-05:00    38.681497
2023-12-29 10:55:00-05:00    37.498719
2023-12-29 11:00:00-05:00    36.671046
2023-12-29 11:05:00-05:00    35.522643
2023-12-29 11:10:00-05:00    33.852115
2023-12-29 11:15:00-05:00    32.275946
2023-12-29 11:20:00-05:00    30.790929
2023-12-29 11:25:00-05:00    28.977024
2023-12-29 11:30:00-05:00    27.492120
2023-12-29 11:35:00-05:00    25.877157
2023-12-29 11:40:00-05:00    24.841027
2023-12-29 11:45:00-05:00    24.600327
2023-12-29 11:50:00-05:00    24.623280
2023-12-29 11:55:00-05:00    24.938840
2023-12-29 12:00:00-05:00    25.345333
2023-12-29 12:05:00-05:00    25.222478
2023-12-29 12:10:00-05:00    24.548640
2023-12-29 12:15:00-05:00    24.532767
2023-12-29 12:20:00-05:00    24.690124
2023-12-29 12:25:00-05:00    24.941735
2023-12-29 12:30:00-05:00    25.879389
2023-12-29 12:35:00-05:00    27.207991
2023-12-29 12:40:00-05:00    28.720309
2023-12-29 12:45:00-05:00    29.788509
2023-12-29 12:50:00-05:00    31.221875
2023-12-29 12:55:00-05:00    32.505079
2023-12-29 13:00:00-05:00    34.239857
2023-12-29 13:05:00-05:00    36.228946

In [97]:
rsismas_60m

Datetime
2023-12-20 09:30:00          NaN
2023-12-20 10:30:00          NaN
2023-12-20 11:30:00          NaN
2023-12-20 12:30:00          NaN
2023-12-20 13:30:00          NaN
2023-12-20 14:30:00          NaN
2023-12-20 15:30:00          NaN
2023-12-21 09:30:00          NaN
2023-12-21 10:30:00          NaN
2023-12-21 11:30:00          NaN
2023-12-21 12:30:00          NaN
2023-12-21 13:30:00          NaN
2023-12-21 14:30:00          NaN
2023-12-21 15:30:00          NaN
2023-12-22 09:30:00          NaN
2023-12-22 10:30:00          NaN
2023-12-22 11:30:00          NaN
2023-12-22 12:30:00          NaN
2023-12-22 13:30:00          NaN
2023-12-22 14:30:00          NaN
2023-12-22 15:30:00          NaN
2023-12-26 09:30:00          NaN
2023-12-26 10:30:00          NaN
2023-12-26 11:30:00          NaN
2023-12-26 12:30:00          NaN
2023-12-26 13:30:00          NaN
2023-12-26 14:30:00          NaN
2023-12-26 15:30:00    49.697259
2023-12-27 09:30:00    49.923335
2023-12-27 10:30:00    50.209169
2023-12-27 11:30:00    50.663662
2023-12-27 12:30:00    51.126897
2023-12-27 13:30:00    51.914243
2023-12-27 14:30:00    52.225976
2023-12-27 15:30:00    52.892137
2023-12-28 09:30:00    53.523493
2023-12-28 10:30:00    54.003631
2023-12-28 11:30:00    54.426299
2023-12-28 12:30:00    54.839601
2023-12-28 13:30:00    55.311756
2023-12-28 14:30:00    55.384134
2023-12-28 15:30:00    55.520864
2023-12-29 09:30:00    55.632266
2023-12-29 10:30:00    54.703867
2023-12-29 11:30:00    53.555104
2023-12-29 12:30:00    52.713076
2023-12-29 13:30:00    52.269868
2023-12-29 14:30:00    52.182047
2023-12-29 15:30:00    51.632394
2024-01-02 09:30:00    49.822599
2024-01-02 10:30:00    48.416028
2024-01-02 11:30:00    47.242647
2024-01-02 12:30:00    45.939205
2024-01-02 13:30:00    44.325129
2024-01-02 14:30:00    42.716944
2024-01-02 15:30:00    41.884645
2024-01-03 09:30:00    40.376535
2024-01-03 10:30:00    40.068399
2024-01-03 11:30:00    39.843488
2024-01-03 12:30:00    39.470334
2024-01-03 13:30:00    39.079121
2024-01-03 14:30:00    38.014727
2024-01-03 15:30:00    37.013109
2024-01-04 09:30:00    37.416455
2024-01-04 10:30:00    37.890781
2024-01-04 11:30:00    37.863623
2024-01-04 12:30:00    37.850813
2024-01-04 13:30:00    37.865315
2024-01-04 14:30:00    38.035368
2024-01-04 15:30:00    37.327981
2024-01-05 09:30:00    38.089734
2024-01-05 10:30:00    38.685435
2024-01-05 11:30:00    38.907215
2024-01-05 12:30:00    39.014944
2024-01-05 13:30:00    39.025518
2024-01-05 14:30:00    39.117732
2024-01-05 15:30:00    39.675750
2024-01-08 09:30:00    40.443803
2024-01-08 10:30:00    41.035283
2024-01-08 11:30:00    41.965280
2024-01-08 12:30:00    43.136189
2024-01-08 13:30:00    44.858691
2024-01-08 14:30:00    46.799978
2024-01-08 15:30:00    49.143011
2024-01-09 09:30:00    49.988700
2024-01-09 10:30:00    51.104658
2024-01-09 11:30:00    52.822086
2024-01-09 12:30:00    54.231156
2024-01-09 13:30:00    55.448689
2024-01-09 14:30:00    57.009951
2024-01-09 15:30:00    58.231445
2024-01-10 09:30:00    59.087217
2024-01-10 10:30:00    59.842454
2024-01-10 11:30:00    60.602758
2024-01-10 12:30:00    61.239245
2024-01-10 13:30:00    61.825352
2024-01-10 14:30:00    62.060729
2024-01-10 15:30:00    62.189860
2024-01-11 09:30:00    62.289145
2024-01-11 10:30:00    61.510034
2024-01-11 11:30:00    60.493726
2024-01-11 12:30:00    60.199115
2024-01-11 13:30:00    60.324562
2024-01-11 14:30:00    60.332997
2024-01-11 15:30:00    60.432082
2024-01-12 09:30:00    60.361796
2024-01-12 10:30:00    60.284631
2024-01-12 11:30:00    59.821233
2024-01-12 12:30:00    59.527335
2024-01-12 13:30:00    58.987690
2024-01-12 14:30:00    58.314963
2024-01-12 15:30:00    57.721275
2024-01-16 09:30:00    57.510386
2024-01-16 10:30:00    57.982580
2024-01-16 11:30:00    57.892655
2024-01-16 12:30:00    57.465908
2024-01-16 13:30:00    56.199944
2024-01-16 14:30:00    55.190375
2024-01-16 15:30:00    54.423559
2024-01-17 09:30:00    52.715298
2024-01-17 10:30:00    51.232614
2024-01-17 11:30:00    49.814017
2024-01-17 12:30:00    47.995573
2024-01-17 13:30:00    46.296470
2024-01-17 14:30:00    44.853740
2024-01-17 15:30:00    43.779725
2024-01-18 09:30:00    43.614369
2024-01-18 10:30:00    43.608614
2024-01-18 11:30:00    43.868989
2024-01-18 12:30:00    43.648638
2024-01-18 13:30:00    44.667815
2024-01-18 14:30:00    45.669188
2024-01-18 15:30:00    46.331571
2024-01-19 09:30:00    48.188644
2024-01-19 10:30:00    49.974138
2024-01-19 11:30:00    52.081636
2024-01-19 12:30:00    54.637880
2024-01-19 13:30:00    57.139730
2024-01-19 14:30:00    59.745963
2024-01-19 15:30:00    61.870144
dtype: float64

In [98]:
rsismas_1d = talib.SMA(rsis_1d, timeperiod=14)

In [99]:
rsismas_1d

Date
2023-11-09          NaN
2023-11-10          NaN
2023-11-13          NaN
2023-11-14          NaN
2023-11-15          NaN
2023-11-16          NaN
2023-11-17          NaN
2023-11-20          NaN
2023-11-21          NaN
2023-11-22          NaN
2023-11-24          NaN
2023-11-27          NaN
2023-11-28          NaN
2023-11-29          NaN
2023-11-30          NaN
2023-12-01          NaN
2023-12-04          NaN
2023-12-05          NaN
2023-12-06          NaN
2023-12-07          NaN
2023-12-08          NaN
2023-12-11          NaN
2023-12-12          NaN
2023-12-13          NaN
2023-12-14          NaN
2023-12-15          NaN
2023-12-18          NaN
2023-12-19    84.330908
2023-12-20    82.776319
2023-12-21    81.410947
2023-12-22    80.644177
2023-12-26    80.002204
2023-12-27    79.816474
2023-12-28    79.447183
2023-12-29    78.745485
2024-01-02    77.532264
2024-01-03    75.684476
2024-01-04    73.423968
2024-01-05    71.186109
2024-01-08    70.056074
2024-01-09    68.714726
2024-01-10    67.469558
2024-01-11    67.251120
2024-01-12    66.807805
2024-01-16    66.032004
2024-01-17    64.758222
2024-01-18    63.844402
2024-01-19    63.366901
dtype: float64

In [100]:
datetime_list = data_5m.index.tolist()

In [101]:
print(datetime_list[28])
print(rsis_1d[28])
print(rsismas_1d[28])

2023-12-20 11:50:00-05:00
69.01669918632277
82.77631875701641

In [102]:
print(len(rsis_5m))
print(len(rsis_15m))
print(len(rsis_30m))
print(len(rsis_60m))
print(len(rsis_1d))

1560
520
260
140
48

In [103]:
class Event:
    def __init__(self, date, close, rsi_5m, rsisma_5m, rsi_15m, rsisma_15m, 
                 rsi_30m, rsisma_30m, rsi_60m, rsisma_60m, rsi_1d, rsisma_1d):
        self.date = date
        self.close = close
        self.rsi_5m = rsi_5m
        self.rsisma_5m = rsisma_5m
        self.ratio_5m = rsi_5m / rsisma_5m
        self.rsi_15m = rsi_15m
        self.rsisma_15m = rsisma_15m
        self.ratio_15m = rsi_15m / rsisma_15m
        self.rsi_30m = rsi_30m
        self.rsisma_30m = rsisma_30m
        self.ratio_30m = rsi_30m / rsisma_30m
        self.rsi_60m = rsi_60m
        self.rsisma_60m = rsisma_60m
        self.ratio_60m = rsi_60m / rsisma_60m
        self.rsi_1d = rsi_1d
        self.rsisma_1d = rsisma_1d
        self.ratio_1d = rsi_1d / rsisma_1d

events = [Event(datetime_list[0], data_5m['Close'].get(0), rsis_5m.iloc[0], rsismas_5m.iloc[0], rsis_15m.iloc[0], 
                rsismas_15m.iloc[0], rsis_30m.iloc[0], rsismas_30m.iloc[0], rsis_60m.iloc[0], rsismas_60m.iloc[0],
               rsis_1d.iloc[27], rsismas_1d.iloc[27])]

#rsis_5m: rsi at 15:45 means rsi value at 15:50
#rsis_15m: rsi at 14:45 means rsi value at 15:00
#rsis_30m: rsi at 14:30 means rsi value at 15:00
#rsis_60m: rsi at 14:30 means rsi value at 15:30

rsi_15_counter = -2
rsi_30_counter = -5
rsi_1h_counter = -11
rsi_1d_counter = 1

for num in range(1, data_5m.shape[0]):
    current_rsi_15m = rsis_15m[int((rsi_15_counter / 3))]
    current_rsisma_15m = rsismas_15m[int((rsi_15_counter / 3))]
    current_rsi_30m = rsis_30m[int((rsi_30_counter / 6))]
    current_rsisma_30m = rsismas_30m[int((rsi_30_counter / 6))]
    current_rsi_60m = rsis_60m[int((rsi_1h_counter / 12)) + 1]
    current_rsisma_60m = rsismas_60m[int((rsi_1h_counter / 12)) + 2]
    current_rsi_1d = rsis_1d[int((rsi_1d_counter / 78)) + 27]
    current_rsisma_1d = rsismas_1d[int((rsi_1d_counter / 78)) + 27]
    
    currentEvent = Event(datetime_list[num], data_5m['Close'].get(num), rsis_5m.iloc[num - 1], 
                         rsismas_5m.iloc[num - 1], current_rsi_15m, current_rsisma_15m, current_rsi_30m,
                        current_rsisma_30m, current_rsi_60m, current_rsisma_60m, current_rsi_1d,
                        current_rsisma_1d)
    
    rsi_15_counter += 1
    rsi_30_counter += 1
    rsi_1h_counter += 1
    rsi_1d_counter += 1
    events.append(currentEvent)

#note to self: rsisma_60m starts at index 312

In [104]:
print(events[0].date)
print(events[0].rsi_1d)

2023-12-20 09:30:00-05:00
83.83114663554136

In [105]:
print(events[42].date)
print(events[42].close)
print(events[42].rsi_5m)
print(events[42].rsi_15m)
print(events[42].rsi_30m)
print(events[168].rsi_60m)
print(events[42].rsi_1d)

2023-12-20 13:00:00-05:00
475.7850036621094
70.46207618738299
nan
nan
50.05197952708197
83.83114663554136

In [106]:
print(events[data_5m.shape[0] - 1].date)
print(events[data_5m.shape[0] - 1].rsi_5m)

2024-01-19 15:55:00-05:00
63.06987478664834

In [107]:
def calculate_average(lst):
    if len(lst) == 0:
        return 0  # Handle the case where the list is empty to avoid division by zero error
    total = sum(lst)
    average = total / len(lst)
    return average

In [108]:
class ratio_profit:
    def __init__(self, entry_ratio, ratio, profit, num_trades, win_rate, average_profit, average_loss,
                greatest_profit, greatest_loss):
        self.entry_ratio = entry_ratio
        self.ratio = ratio
        self.profit = profit
        self.num_trades = num_trades
        self.win_rate = win_rate
        self.average_profit = average_profit
        self.average_loss = average_loss
        self.greatest_profit = greatest_profit
        self.greatest_loss = greatest_loss

ratio_profits = []

entry_ratio_values = np.arange(0.900, 1.100, 0.001)
ratio_values = np.arange(1.000, 1.200, 0.001)

for entry_ratio in entry_ratio_values:
    for ratio in ratio_values:
        entryIndices = []
        exitIndices = []
        trade_counter = 0
        holding_position = False
        all_profits = []
        all_losses = []
        
        for i in range(313, data_5m.shape[0]):
            min_ratio_prev = min([events[i-1].ratio_5m, events[i-1].ratio_15m, 
                                         events[i-1].ratio_30m, events[i-1].ratio_60m, events[i-1].ratio_1d])
            if holding_position == False:
                if min_ratio_prev >= entry_ratio:
                    entryIndices.append(i)
                    holding_position = True
            elif holding_position == True:
                if min_ratio_prev < ratio and events[i - 1].ratio_60m < events[i - 2].ratio_60m:
                    exitIndices.append(i)
                    trade_counter += 1
                    holding_position = False
        
        profit_multiplier = 1.00
        wins = 0
        win_rate = 0
        
        for date in range(0, len(exitIndices)):
            profit = events[exitIndices[date]].close / events[entryIndices[date]].close
            profit_multiplier *= profit
            if profit > 1.00:
                wins += 1
                all_profits.append(profit)
            else:
                all_losses.append(profit)
        if trade_counter != 0:
            win_rate = wins / trade_counter
        elif trade_counter == 0:
            win_rate = 0
        
        average_profit = 0
        average_loss = 0
        greatest_profit = 0
        greatest_loss = 0
        
        if len(all_profits) == 0:
            average_profit = 0
            greatest_profit = 0
        else:
            average_profit = calculate_average(all_profits)
            greatest_profit = max(all_profits)
        
        if len(all_losses) == 0:
            average_loss = 0
            greatest_loss = 0
        else:
            average_loss = calculate_average(all_losses)
            greatest_loss = min(all_losses)
        
        rp = ratio_profit(entry_ratio, ratio, profit_multiplier, trade_counter, win_rate,
                         average_profit, average_loss, greatest_profit, greatest_loss)
        
        if (trade_counter < 25):
            ratio_profits.append(rp)

max_profit_index = 0
for i in range(1, len(ratio_profits)):
    if ratio_profits[i].profit > ratio_profits[max_profit_index].profit:
        max_profit_index = i

print("entry ratio: ", ratio_profits[max_profit_index].entry_ratio)
print("ratio: ", ratio_profits[max_profit_index].ratio)
print("profit: ", ratio_profits[max_profit_index].profit)
print("num_trades: ", ratio_profits[max_profit_index].num_trades)
print("win_rate: ", ratio_profits[max_profit_index].win_rate)
print("average_profit: ", ratio_profits[max_profit_index].average_profit)
print("average_loss: ", ratio_profits[max_profit_index].average_loss)
print("greatest_profit: ", ratio_profits[max_profit_index].greatest_profit)
print("greatest_loss: ", ratio_profits[max_profit_index].greatest_loss)

entry ratio:  0.9440000000000001
ratio:  1.0
profit:  1.0076362850317848
num_trades:  9
win_rate:  0.4444444444444444
average_profit:  1.0031643784594952
average_loss:  0.9989966974468626
greatest_profit:  1.006800315239815
greatest_loss:  0.9977738453781639