In [1]:
import talib
import yfinance as yf
import pandas as pd
from pandas import Timestamp
import numpy as np

In [2]:
data = yf.download('SLV', start = '2023-01-20', end = '2024-01-22')

[*********************100%%**********************]  1 of 1 completed

In [3]:
data_5m = yf.download('SLV', start = '2023-12-20', end = '2024-01-22', interval = '5m')

[*********************100%%**********************]  1 of 1 completed

In [4]:
print(data['Close']['2023-01-23'])
print(data_5m)

21.579999923706055
                                Open       High        Low      Close  \
Datetime
2023-12-20 09:30:00-05:00  22.260000  22.280001  22.195000  22.230000
2023-12-20 09:35:00-05:00  22.231300  22.270000  22.205000  22.230000
2023-12-20 09:40:00-05:00  22.230000  22.235001  22.200001  22.209999
2023-12-20 09:45:00-05:00  22.219999  22.309999  22.214701  22.250000
2023-12-20 09:50:00-05:00  22.250000  22.309999  22.250000  22.299900
...                              ...        ...        ...        ...
2024-01-19 15:35:00-05:00  20.670099  20.680000  20.670099  20.672800
2024-01-19 15:40:00-05:00  20.670000  20.680000  20.660000  20.670000
2024-01-19 15:45:00-05:00  20.665001  20.680000  20.660000  20.670000
2024-01-19 15:50:00-05:00  20.669399  20.670000  20.650000  20.659901
2024-01-19 15:55:00-05:00  20.660000  20.670000  20.655001  20.660000

                           Adj Close  Volume
Datetime
2023-12-20 09:30:00-05:00  22.230000  706152
2023-12-20 09:35:00-05:00  22.230000  324069
2023-12-20 09:40:00-05:00  22.209999  231605
2023-12-20 09:45:00-05:00  22.250000  293121
2023-12-20 09:50:00-05:00  22.299900  253098
...                              ...     ...
2024-01-19 15:35:00-05:00  20.672800   19847
2024-01-19 15:40:00-05:00  20.670000  210438
2024-01-19 15:45:00-05:00  20.670000  214968
2024-01-19 15:50:00-05:00  20.659901  217759
2024-01-19 15:55:00-05:00  20.660000  293297

[1560 rows x 6 columns]

In [5]:
data_15m = yf.download('SLV', start = '2023-12-20', end = '2024-01-22', interval = '15m')
data_30m = yf.download('SLV', start = '2023-12-20', end = '2024-01-22', interval = '30m')
data_1h = yf.download('SLV', start = '2023-12-20', end = '2024-01-22', interval = '1h')

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [6]:
data_60m = yf.download('SLV', start = '2023-12-20', end = '2024-01-22', interval = '60m')
pd.set_option('display.max_rows', 141)
data_60m

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2023-12-20 09:30:00,22.260000,22.309999,22.184999,22.209999,22.209999,3810793
2023-12-20 10:30:00,22.215000,22.299999,22.195000,22.290001,22.290001,1896704
2023-12-20 11:30:00,22.290001,22.299900,22.245001,22.250299,22.250299,891798
2023-12-20 12:30:00,22.254999,22.295000,22.230000,22.268999,22.268999,867641
2023-12-20 13:30:00,22.264999,22.290001,22.252899,22.264999,22.264999,654291
2023-12-20 14:30:00,22.260099,22.275101,22.070999,22.105000,22.105000,1802979
2023-12-20 15:30:00,22.110001,22.120001,22.040001,22.045000,22.045000,2075565
2023-12-21 09:30:00,22.280001,22.420000,22.195000,22.305000,22.305000,8293610
2023-12-21 10:30:00,22.305000,22.350000,22.219999,22.329901,22.329901,2202314
2023-12-21 11:30:00,22.330000,22.334999,22.241899,22.250000,22.250000,1168253
2023-12-21 12:30:00,22.250000,22.289900,22.209999,22.245899,22.245899,1259841
2023-12-21 13:30:00,22.250000,22.280001,22.215000,22.275000,22.275000,1012195
2023-12-21 14:30:00,22.280001,22.329500,22.270000,22.299999,22.299999,1157841
2023-12-21 15:30:00,22.295000,22.330000,22.290001,22.309999,22.309999,1602124
2023-12-22 09:30:00,22.410000,22.525200,22.400000,22.420000,22.420000,5112374
2023-12-22 10:30:00,22.419500,22.424999,22.204500,22.270000,22.270000,3407064
2023-12-22 11:30:00,22.270100,22.299999,22.120001,22.235001,22.235001,3083168
2023-12-22 12:30:00,22.240000,22.254999,22.204599,22.240000,22.240000,660672
2023-12-22 13:30:00,22.230000,22.240000,22.049999,22.059999,22.059999,1799458
2023-12-22 14:30:00,22.059999,22.120001,22.049999,22.105000,22.105000,1565207
2023-12-22 15:30:00,22.105000,22.120001,22.100000,22.115000,22.115000,1304862
2023-12-26 09:30:00,22.209999,22.209999,22.040001,22.150000,22.150000,3855088
2023-12-26 10:30:00,22.149900,22.180000,22.134399,22.165001,22.165001,1371116
2023-12-26 11:30:00,22.170000,22.207500,22.150000,22.184999,22.184999,1256743
2023-12-26 12:30:00,22.184999,22.184999,22.065001,22.110001,22.110001,1535342
2023-12-26 13:30:00,22.115000,22.180000,22.110100,22.174999,22.174999,1276713
2023-12-26 14:30:00,22.174999,22.197500,22.160000,22.174999,22.174999,1321174
2023-12-26 15:30:00,22.180000,22.219999,22.170000,22.219999,22.219999,1020043
2023-12-27 09:30:00,22.100000,22.285000,22.090000,22.270000,22.270000,3993637
2023-12-27 10:30:00,22.280001,22.389999,22.260000,22.320000,22.320000,4041557
2023-12-27 11:30:00,22.320000,22.350000,22.290001,22.299999,22.299999,1545673
2023-12-27 12:30:00,22.309900,22.370001,22.290001,22.305000,22.305000,1038454
2023-12-27 13:30:00,22.309900,22.309900,22.186001,22.209900,22.209900,1302016
2023-12-27 14:30:00,22.209999,22.240000,22.180000,22.200001,22.200001,730816
2023-12-27 15:30:00,22.205000,22.240000,22.200001,22.235001,22.235001,734414
2023-12-28 09:30:00,22.170000,22.250000,22.059999,22.218000,22.218000,2689881
2023-12-28 10:30:00,22.219999,22.225000,22.080000,22.115000,22.115000,1723650
2023-12-28 11:30:00,22.113800,22.139999,22.090000,22.105000,22.105000,1115610
2023-12-28 12:30:00,22.109900,22.129999,22.037701,22.070000,22.070000,1973294
2023-12-28 13:30:00,22.070000,22.070000,21.980000,22.000000,22.000000,1049381
2023-12-28 14:30:00,21.995001,22.009899,21.959999,21.999901,21.999901,1112327
2023-12-28 15:30:00,21.995001,22.014999,21.969999,21.983999,21.983999,1184703
2023-12-29 09:30:00,21.620001,21.855301,21.559999,21.855301,21.855301,4177596
2023-12-29 10:30:00,21.860001,21.905001,21.809999,21.865000,21.865000,2570833
2023-12-29 11:30:00,21.861099,21.950001,21.860001,21.934999,21.934999,1338214
2023-12-29 12:30:00,21.940001,21.949900,21.799999,21.805401,21.805401,1401225
2023-12-29 13:30:00,21.799999,21.835300,21.790001,21.815001,21.815001,1817237
2023-12-29 14:30:00,21.809999,21.830000,21.790001,21.795900,21.795900,645145
2023-12-29 15:30:00,21.795000,21.799900,21.760000,21.780001,21.780001,1011242
2024-01-02 09:30:00,21.889999,21.990000,21.805000,21.855000,21.855000,4385199
2024-01-02 10:30:00,21.850000,21.885799,21.700001,21.815001,21.815001,3206607
2024-01-02 11:30:00,21.815001,21.840000,21.715000,21.719999,21.719999,1384090
2024-01-02 12:30:00,21.719999,21.759899,21.670000,21.725000,21.725000,907126
2024-01-02 13:30:00,21.719999,21.725000,21.650000,21.669901,21.669901,946152
2024-01-02 14:30:00,21.665001,21.679899,21.639999,21.645000,21.645000,1062093
2024-01-02 15:30:00,21.643900,21.660000,21.639999,21.650000,21.650000,1202733
2024-01-03 09:30:00,21.080000,21.219999,20.959999,21.000000,21.000000,9610866
2024-01-03 10:30:00,21.000500,21.059999,20.910000,21.030001,21.030001,5278621
2024-01-03 11:30:00,21.030001,21.049999,20.980000,20.990000,20.990000,1803864
2024-01-03 12:30:00,20.990000,21.020000,20.940001,21.010000,21.010000,1492167
2024-01-03 13:30:00,21.013201,21.110001,20.959999,21.110001,21.110001,2424056
2024-01-03 14:30:00,21.110001,21.160000,21.040001,21.080000,21.080000,3543056
2024-01-03 15:30:00,21.080000,21.100000,21.059999,21.065001,21.065001,1765407
2024-01-04 09:30:00,20.920000,21.049999,20.770000,21.040001,21.040001,5118186
2024-01-04 10:30:00,21.049999,21.070000,21.000000,21.045000,21.045000,2072755
2024-01-04 11:30:00,21.049999,21.092600,21.014999,21.014999,21.014999,1092579
2024-01-04 12:30:00,21.010000,21.069901,21.010000,21.054199,21.054199,968635
2024-01-04 13:30:00,21.055000,21.079901,21.035000,21.045000,21.045000,608875
2024-01-04 14:30:00,21.040001,21.090000,21.040001,21.070101,21.070101,865268
2024-01-04 15:30:00,21.075001,21.100000,21.070000,21.080000,21.080000,767104
2024-01-05 09:30:00,21.150000,21.530001,21.034401,21.424999,21.424999,9721058
2024-01-05 10:30:00,21.430000,21.450100,21.280001,21.315001,21.315001,3856332
2024-01-05 11:30:00,21.309999,21.340000,21.190001,21.230000,21.230000,2294001
2024-01-05 12:30:00,21.225000,21.250000,21.155001,21.219999,21.219999,1304294
2024-01-05 13:30:00,21.230000,21.329901,21.209999,21.275000,21.275000,1241791
2024-01-05 14:30:00,21.274900,21.290001,21.209999,21.219900,21.219900,781231
2024-01-05 15:30:00,21.215000,21.240000,21.193701,21.219999,21.219999,1911322
2024-01-08 09:30:00,21.070000,21.189899,21.000000,21.165001,21.165001,3567028
2024-01-08 10:30:00,21.170000,21.245001,21.150000,21.195000,21.195000,2313828
2024-01-08 11:30:00,21.198500,21.239901,21.180000,21.200001,21.200001,757027
2024-01-08 12:30:00,21.190001,21.200001,21.150000,21.159800,21.159800,863147
2024-01-08 13:30:00,21.155001,21.170000,21.120001,21.130100,21.130100,584418
2024-01-08 14:30:00,21.135000,21.169901,21.100000,21.125000,21.125000,676995
2024-01-08 15:30:00,21.125000,21.139999,21.110001,21.135000,21.135000,640405
2024-01-09 09:30:00,21.219999,21.250000,21.094999,21.110001,21.110001,2514599
2024-01-09 10:30:00,21.110001,21.139700,21.000000,21.051399,21.051399,2286869
2024-01-09 11:30:00,21.055000,21.094999,21.002501,21.020000,21.020000,1152190
2024-01-09 12:30:00,21.020000,21.029900,20.959999,20.976999,20.976999,1676472
2024-01-09 13:30:00,20.975000,21.020000,20.959999,20.990000,20.990000,824355
2024-01-09 14:30:00,20.995001,21.040001,20.969999,21.020000,21.020000,1096102
2024-01-09 15:30:00,21.025000,21.030001,21.000000,21.000000,21.000000,932214
2024-01-10 09:30:00,20.930000,21.000000,20.850000,20.910000,20.910000,4802896
2024-01-10 10:30:00,20.900000,21.009899,20.900000,20.920099,20.920099,1971310
2024-01-10 11:30:00,20.925400,21.017500,20.900000,20.971600,20.971600,894435
2024-01-10 12:30:00,20.975000,20.985001,20.934999,20.959999,20.959999,884978
2024-01-10 13:30:00,20.959999,21.000000,20.950001,20.969999,20.969999,734185
2024-01-10 14:30:00,20.975000,21.000000,20.945000,20.975000,20.975000,1101969
2024-01-10 15:30:00,20.969999,20.980000,20.920000,20.945000,20.945000,1246891
2024-01-11 09:30:00,20.969999,21.072201,20.730000,20.870001,20.870001,5832828
2024-01-11 10:30:00,20.875000,20.929899,20.590000,20.634199,20.634199,5856377
2024-01-11 11:30:00,20.629999,20.708599,20.570000,20.660000,20.660000,4592214
2024-01-11 12:30:00,20.660000,20.674999,20.600000,20.639999,20.639999,1526872
2024-01-11 13:30:00,20.639999,20.790001,20.590000,20.775000,20.775000,1157653
2024-01-11 14:30:00,20.780001,20.819901,20.754999,20.775000,20.775000,1205621
2024-01-11 15:30:00,20.774599,20.834999,20.774599,20.830000,20.830000,1131463
2024-01-12 09:30:00,21.389999,21.540001,21.370001,21.504700,21.504700,7209956
2024-01-12 10:30:00,21.510000,21.530001,21.309999,21.389999,21.389999,3418273
2024-01-12 11:30:00,21.379999,21.379999,21.150000,21.160101,21.160101,2168927
2024-01-12 12:30:00,21.160000,21.219900,21.110001,21.200001,21.200001,2001688
2024-01-12 13:30:00,21.205000,21.259899,21.180000,21.235001,21.235001,955485
2024-01-12 14:30:00,21.235001,21.240000,21.180099,21.195000,21.195000,939556
2024-01-12 15:30:00,21.195000,21.209999,21.190001,21.200001,21.200001,1533500
2024-01-16 09:30:00,21.139999,21.169800,20.959999,21.004999,21.004999,4546434
2024-01-16 10:30:00,21.004999,21.110001,20.920000,21.030001,21.030001,4789756
2024-01-16 11:30:00,21.025000,21.059999,20.920000,20.930000,20.930000,2482731
2024-01-16 12:30:00,20.930000,21.010000,20.930000,21.004999,21.004999,1469837
2024-01-16 13:30:00,21.004999,21.040001,20.930099,21.014999,21.014999,1081901
2024-01-16 14:30:00,21.011000,21.040001,20.990000,20.995001,20.995001,938238
2024-01-16 15:30:00,20.998199,21.000000,20.964899,20.969999,20.969999,1324847
2024-01-17 09:30:00,20.778999,20.795401,20.674999,20.684999,20.684999,5231251
2024-01-17 10:30:00,20.684999,20.790001,20.660000,20.685301,20.685301,3472093
2024-01-17 11:30:00,20.680000,20.705099,20.620001,20.620001,20.620001,2334792
2024-01-17 12:30:00,20.620001,20.680000,20.610001,20.655001,20.655001,2183134
2024-01-17 13:30:00,20.655001,20.670000,20.610001,20.636499,20.636499,1445737
2024-01-17 14:30:00,20.632500,20.650000,20.610001,20.610001,20.610001,1437225
2024-01-17 15:30:00,20.620001,20.660000,20.610001,20.650000,20.650000,1740743
2024-01-18 09:30:00,20.559999,20.690001,20.535000,20.689899,20.689899,3073215
2024-01-18 10:30:00,20.680000,20.769501,20.680000,20.760000,20.760000,1857546
2024-01-18 11:30:00,20.764999,20.768999,20.700001,20.730000,20.730000,1272476
2024-01-18 12:30:00,20.731001,20.795000,20.719999,20.775000,20.775000,1568313
2024-01-18 13:30:00,20.779900,20.830000,20.770000,20.800100,20.800100,912477
2024-01-18 14:30:00,20.805000,20.815001,20.790001,20.799999,20.799999,600418
2024-01-18 15:30:00,20.809999,20.840000,20.809999,20.820000,20.820000,959497
2024-01-19 09:30:00,20.770000,20.770000,20.605000,20.655001,20.655001,4553846
2024-01-19 10:30:00,20.650000,20.690001,20.590000,20.619900,20.619900,2410577
2024-01-19 11:30:00,20.619900,20.656000,20.559999,20.650000,20.650000,1462182
2024-01-19 12:30:00,20.649900,20.690001,20.629999,20.665001,20.665001,1474400
2024-01-19 13:30:00,20.660000,20.695000,20.642500,20.678301,20.678301,635507
2024-01-19 14:30:00,20.680000,20.705299,20.670000,20.674999,20.674999,829566
2024-01-19 15:30:00,20.673500,20.680000,20.650000,20.660000,20.660000,1004300

In [7]:
data_1d = yf.download('SLV', start = '2023-11-09', end = '2024-01-22', interval = '1d')
data_1d

[*********************100%%**********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close    Volume
Date
2023-11-09  20.750000  21.070000  20.650000  20.690001  20.690001  18732000
2023-11-10  20.549999  20.600000  20.340000  20.340000  20.340000  14049800
2023-11-13  20.180000  20.490000  20.100000  20.430000  20.430000  11091100
2023-11-14  20.920000  21.240000  20.870001  21.170000  21.170000  21723900
2023-11-15  21.360001  21.520000  21.240000  21.450001  21.450001  18585600
2023-11-16  21.879999  22.059999  21.730000  21.760000  21.760000  20259200
2023-11-17  21.790001  21.860001  21.680000  21.750000  21.750000  12296000
2023-11-20  21.420000  21.610001  21.379999  21.480000  21.480000   9559600
2023-11-21  21.879999  22.000000  21.740000  21.770000  21.770000  15213000
2023-11-22  21.700001  21.820000  21.570000  21.670000  21.670000  11143900
2023-11-24  22.020000  22.290001  22.000000  22.270000  22.270000  10803300
2023-11-27  22.670000  22.709999  22.500000  22.559999  22.559999  19785600
2023-11-28  22.680000  22.920000  22.590000  22.920000  22.920000  17064400
2023-11-29  22.959999  23.129999  22.820000  22.879999  22.879999  16675200
2023-11-30  22.969999  23.150000  22.850000  23.129999  23.129999  14364300
2023-12-01  23.090000  23.370001  23.049999  23.330000  23.330000  22098300
2023-12-04  22.750000  22.920000  22.360001  22.459999  22.459999  30668300
2023-12-05  22.280001  22.379999  21.950001  22.120001  22.120001  27205100
2023-12-06  22.170000  22.200001  21.870001  21.930000  21.930000  13374500
2023-12-07  21.889999  21.910000  21.600000  21.790001  21.790001  16758500
2023-12-08  21.350000  21.559999  21.020000  21.100000  21.100000  28718900
2023-12-11  20.969999  21.000000  20.809999  20.910000  20.910000  22883700
2023-12-12  20.969999  20.980000  20.780001  20.840000  20.840000  12118700
2023-12-13  20.750000  21.780001  20.610001  21.770000  21.770000  35068000
2023-12-14  21.990000  22.180000  21.990000  22.150000  22.150000  21384100
2023-12-15  21.980000  22.030001  21.750000  21.830000  21.830000  12013400
2023-12-18  21.879999  21.879999  21.660000  21.799999  21.799999  12927400
2023-12-19  21.910000  22.129999  21.889999  22.030001  22.030001  12752700
2023-12-20  22.260000  22.309999  22.040001  22.040001  22.040001  12523600
2023-12-21  22.280001  22.420000  22.200001  22.309999  22.309999  17063600
2023-12-22  22.410000  22.530001  22.049999  22.120001  22.120001  17222200
2023-12-26  22.209999  22.219999  22.040001  22.200001  22.200001  11861700
2023-12-27  22.100000  22.400000  22.090000  22.230000  22.230000  13898400
2023-12-28  22.170000  22.250000  21.959999  21.990000  21.990000  11257800
2023-12-29  21.620001  21.950001  21.559999  21.780001  21.780001  13151200
2024-01-02  21.889999  21.990000  21.639999  21.650000  21.650000  13277800
2024-01-03  21.080000  21.219999  20.910000  21.059999  21.059999  26373800
2024-01-04  20.920000  21.100000  20.770000  21.080000  21.080000  11972000
2024-01-05  21.150000  21.530001  21.030001  21.209999  21.209999  21396300
2024-01-08  21.070000  21.250000  21.000000  21.129999  21.129999   9527900
2024-01-09  21.219999  21.250000  20.959999  21.000000  21.000000  10772300
2024-01-10  20.930000  21.020000  20.850000  20.940001  20.940001  12093700
2024-01-11  20.969999  21.070000  20.570000  20.820000  20.820000  21816100
2024-01-12  21.389999  21.540001  21.110001  21.190001  21.190001  18903600
2024-01-16  21.139999  21.170000  20.920000  20.959999  20.959999  16953000
2024-01-17  20.780001  20.799999  20.610001  20.650000  20.650000  18249100
2024-01-18  20.559999  20.840000  20.540001  20.809999  20.809999  10585900
2024-01-19  20.770000  20.770000  20.559999  20.670000  20.670000  12570200

In [8]:
print(len(data_5m))
print(len(data_15m))
print(len(data_30m))
print(len(data_60m))
print(len(data_1d))

1560
520
260
140
48

In [9]:
#note: data_1d starts 28 days before the time of data_5m data

In [10]:
rsis_5m = talib.RSI(data_5m['Close'], timeperiod=14)
rsis_15m = talib.RSI(data_15m['Close'], timeperiod=14)
rsis_30m = talib.RSI(data_30m['Close'], timeperiod=14)
rsis_60m = talib.RSI(data_60m['Close'], timeperiod=14)

In [11]:
pd.set_option('display.max_rows', 1560)
rsis_5m

Datetime
2023-12-20 09:30:00-05:00          NaN
2023-12-20 09:35:00-05:00          NaN
2023-12-20 09:40:00-05:00          NaN
2023-12-20 09:45:00-05:00          NaN
2023-12-20 09:50:00-05:00          NaN
2023-12-20 09:55:00-05:00          NaN
2023-12-20 10:00:00-05:00          NaN
2023-12-20 10:05:00-05:00          NaN
2023-12-20 10:10:00-05:00          NaN
2023-12-20 10:15:00-05:00          NaN
2023-12-20 10:20:00-05:00          NaN
2023-12-20 10:25:00-05:00          NaN
2023-12-20 10:30:00-05:00          NaN
2023-12-20 10:35:00-05:00          NaN
2023-12-20 10:40:00-05:00    52.500024
2023-12-20 10:45:00-05:00    49.189300
2023-12-20 10:50:00-05:00    52.408522
2023-12-20 10:55:00-05:00    51.024220
2023-12-20 11:00:00-05:00    54.306110
2023-12-20 11:05:00-05:00    52.782432
2023-12-20 11:10:00-05:00    56.036843
2023-12-20 11:15:00-05:00    56.757495
2023-12-20 11:20:00-05:00    54.150890
2023-12-20 11:25:00-05:00    56.987488
2023-12-20 11:30:00-05:00    52.606077
2023-12-20 11:35:00-05:00    51.749326
2023-12-20 11:40:00-05:00    51.335042
2023-12-20 11:45:00-05:00    52.630977
2023-12-20 11:50:00-05:00    51.597075
2023-12-20 11:55:00-05:00    54.450123
2023-12-20 12:00:00-05:00    53.329408
2023-12-20 12:05:00-05:00    55.291726
2023-12-20 12:10:00-05:00    52.919515
2023-12-20 12:15:00-05:00    52.894780
2023-12-20 12:20:00-05:00    50.339972
2023-12-20 12:25:00-05:00    47.921945
2023-12-20 12:30:00-05:00    48.822442
2023-12-20 12:35:00-05:00    43.495937
2023-12-20 12:40:00-05:00    51.862506
2023-12-20 12:45:00-05:00    54.887834
2023-12-20 12:50:00-05:00    50.460702
2023-12-20 12:55:00-05:00    51.660192
2023-12-20 13:00:00-05:00    55.168119
2023-12-20 13:05:00-05:00    50.009610
2023-12-20 13:10:00-05:00    50.512690
2023-12-20 13:15:00-05:00    56.974520
2023-12-20 13:20:00-05:00    51.747123
2023-12-20 13:25:00-05:00    51.491104
2023-12-20 13:30:00-05:00    52.991970
2023-12-20 13:35:00-05:00    51.560666
2023-12-20 13:40:00-05:00    50.102746
2023-12-20 13:45:00-05:00    51.577261
2023-12-20 13:50:00-05:00    51.577261
2023-12-20 13:55:00-05:00    53.181231
2023-12-20 14:00:00-05:00    49.083497
2023-12-20 14:05:00-05:00    47.994051
2023-12-20 14:10:00-05:00    51.574888
2023-12-20 14:15:00-05:00    56.465288
2023-12-20 14:20:00-05:00    52.647822
2023-12-20 14:25:00-05:00    49.074791
2023-12-20 14:30:00-05:00    47.344966
2023-12-20 14:35:00-05:00    41.102710
2023-12-20 14:40:00-05:00    35.992236
2023-12-20 14:45:00-05:00    25.677880
2023-12-20 14:50:00-05:00    21.760424
2023-12-20 14:55:00-05:00    21.251624
2023-12-20 15:00:00-05:00    18.128014
2023-12-20 15:05:00-05:00    19.943836
2023-12-20 15:10:00-05:00    26.924131
2023-12-20 15:15:00-05:00    39.670020
2023-12-20 15:20:00-05:00    34.613220
2023-12-20 15:25:00-05:00    32.689805
2023-12-20 15:30:00-05:00    32.050629
2023-12-20 15:35:00-05:00    30.145819
2023-12-20 15:40:00-05:00    37.505234
2023-12-20 15:45:00-05:00    33.683561
2023-12-20 15:50:00-05:00    32.395805
2023-12-20 15:55:00-05:00    28.833714
2023-12-21 09:30:00-05:00    65.874525
2023-12-21 09:35:00-05:00    65.210062
2023-12-21 09:40:00-05:00    58.819463
2023-12-21 09:45:00-05:00    68.469550
2023-12-21 09:50:00-05:00    59.197032
2023-12-21 09:55:00-05:00    55.593604
2023-12-21 10:00:00-05:00    52.577691
2023-12-21 10:05:00-05:00    51.293286
2023-12-21 10:10:00-05:00    53.727775
2023-12-21 10:15:00-05:00    56.098683
2023-12-21 10:20:00-05:00    59.056026
2023-12-21 10:25:00-05:00    56.506980
2023-12-21 10:30:00-05:00    57.710464
2023-12-21 10:35:00-05:00    54.464461
2023-12-21 10:40:00-05:00    54.847379
2023-12-21 10:45:00-05:00    51.598490
2023-12-21 10:50:00-05:00    47.933572
2023-12-21 10:55:00-05:00    47.933572
2023-12-21 11:00:00-05:00    53.415710
2023-12-21 11:05:00-05:00    52.231205
2023-12-21 11:10:00-05:00    54.419039
2023-12-21 11:15:00-05:00    56.874171
2023-12-21 11:20:00-05:00    58.069396
2023-12-21 11:25:00-05:00    58.632717
2023-12-21 11:30:00-05:00    54.834703
2023-12-21 11:35:00-05:00    53.340327
2023-12-21 11:40:00-05:00    52.584141
2023-12-21 11:45:00-05:00    53.297159
2023-12-21 11:50:00-05:00    49.229660
2023-12-21 11:55:00-05:00    51.615569
2023-12-21 12:00:00-05:00    50.742362
2023-12-21 12:05:00-05:00    47.374795
2023-12-21 12:10:00-05:00    49.199404
2023-12-21 12:15:00-05:00    51.010137
2023-12-21 12:20:00-05:00    50.058987
2023-12-21 12:25:00-05:00    45.406992
2023-12-21 12:30:00-05:00    47.487957
2023-12-21 12:35:00-05:00    48.133259
2023-12-21 12:40:00-05:00    48.609286
2023-12-21 12:45:00-05:00    48.609286
2023-12-21 12:50:00-05:00    43.162113
2023-12-21 12:55:00-05:00    43.140976
2023-12-21 13:00:00-05:00    43.170947
2023-12-21 13:05:00-05:00    41.968932
2023-12-21 13:10:00-05:00    40.770213
2023-12-21 13:15:00-05:00    37.326680
2023-12-21 13:20:00-05:00    45.577288
2023-12-21 13:25:00-05:00    47.339073
2023-12-21 13:30:00-05:00    48.316583
2023-12-21 13:35:00-05:00    43.166868
2023-12-21 13:40:00-05:00    41.907865
2023-12-21 13:45:00-05:00    41.907865
2023-12-21 13:50:00-05:00    41.907865
2023-12-21 13:55:00-05:00    47.631558
2023-12-21 14:00:00-05:00    51.091466
2023-12-21 14:05:00-05:00    49.336631
2023-12-21 14:10:00-05:00    47.576165
2023-12-21 14:15:00-05:00    54.559504
2023-12-21 14:20:00-05:00    54.442568
2023-12-21 14:25:00-05:00    59.248070
2023-12-21 14:30:00-05:00    65.628345
2023-12-21 14:35:00-05:00    66.684755
2023-12-21 14:40:00-05:00    69.905061
2023-12-21 14:45:00-05:00    61.520069
2023-12-21 14:50:00-05:00    56.061989
2023-12-21 14:55:00-05:00    57.418484
2023-12-21 15:00:00-05:00    62.415461
2023-12-21 15:05:00-05:00    54.404794
2023-12-21 15:10:00-05:00    55.280634
2023-12-21 15:15:00-05:00    52.021120
2023-12-21 15:20:00-05:00    50.420014
2023-12-21 15:25:00-05:00    57.467257
2023-12-21 15:30:00-05:00    58.730978
2023-12-21 15:35:00-05:00    60.010057
2023-12-21 15:40:00-05:00    61.302199
2023-12-21 15:45:00-05:00    61.302199
2023-12-21 15:50:00-05:00    63.999817
2023-12-21 15:55:00-05:00    57.521959
2023-12-22 09:30:00-05:00    78.935245
2023-12-22 09:35:00-05:00    80.195549
2023-12-22 09:40:00-05:00    82.511225
2023-12-22 09:45:00-05:00    78.132355
2023-12-22 09:50:00-05:00    66.696326
2023-12-22 09:55:00-05:00    64.439100
2023-12-22 10:00:00-05:00    66.877459
2023-12-22 10:05:00-05:00    69.610578
2023-12-22 10:10:00-05:00    72.146016
2023-12-22 10:15:00-05:00    66.241552
2023-12-22 10:20:00-05:00    56.314513
2023-12-22 10:25:00-05:00    55.420261
2023-12-22 10:30:00-05:00    52.715442
2023-12-22 10:35:00-05:00    52.715442
2023-12-22 10:40:00-05:00    50.070167
2023-12-22 10:45:00-05:00    43.961074
2023-12-22 10:50:00-05:00    36.611700
2023-12-22 10:55:00-05:00    38.620940
2023-12-22 11:00:00-05:00    31.172502
2023-12-22 11:05:00-05:00    35.009738
2023-12-22 11:10:00-05:00    39.364260
2023-12-22 11:15:00-05:00    38.352571
2023-12-22 11:20:00-05:00    37.170213
2023-12-22 11:25:00-05:00    38.196352
2023-12-22 11:30:00-05:00    41.293231
2023-12-22 11:35:00-05:00    40.563680
2023-12-22 11:40:00-05:00    35.663617
2023-12-22 11:45:00-05:00    25.285191
2023-12-22 11:50:00-05:00    34.321039
2023-12-22 11:55:00-05:00    34.948027
2023-12-22 12:00:00-05:00    39.172925
2023-12-22 12:05:00-05:00    38.242161
2023-12-22 12:10:00-05:00    38.242161
2023-12-22 12:15:00-05:00    41.043330
2023-12-22 12:20:00-05:00    43.806667
2023-12-22 12:25:00-05:00    44.712229
2023-12-22 12:30:00-05:00    42.456451
2023-12-22 12:35:00-05:00    43.480190
2023-12-22 12:40:00-05:00    46.551501
2023-12-22 12:45:00-05:00    48.558547
2023-12-22 12:50:00-05:00    48.558547
2023-12-22 12:55:00-05:00    45.581128
2023-12-22 13:00:00-05:00    45.222666
2023-12-22 13:05:00-05:00    42.578834
2023-12-22 13:10:00-05:00    45.218073
2023-12-22 13:15:00-05:00    41.145212
2023-12-22 13:20:00-05:00    45.124236
2023-12-22 13:25:00-05:00    48.825228
2023-12-22 13:30:00-05:00    42.632018
2023-12-22 13:35:00-05:00    45.130444
2023-12-22 13:40:00-05:00    40.996631
2023-12-22 13:45:00-05:00    39.457963
2023-12-22 13:50:00-05:00    39.457963
2023-12-22 13:55:00-05:00    37.535564
2023-12-22 14:00:00-05:00    34.797139
2023-12-22 14:05:00-05:00    32.262069
2023-12-22 14:10:00-05:00    30.658586
2023-12-22 14:15:00-05:00    29.859620
2023-12-22 14:20:00-05:00    22.815103
2023-12-22 14:25:00-05:00    20.885486
2023-12-22 14:30:00-05:00    20.885486
2023-12-22 14:35:00-05:00    24.584197
2023-12-22 14:40:00-05:00    26.831199
2023-12-22 14:45:00-05:00    31.816966
2023-12-22 14:50:00-05:00    38.298628
2023-12-22 14:55:00-05:00    41.317694
2023-12-22 15:00:00-05:00    39.269347
2023-12-22 15:05:00-05:00    37.259769
2023-12-22 15:10:00-05:00    42.049964
2023-12-22 15:15:00-05:00    40.906296
2023-12-22 15:20:00-05:00    42.587895
2023-12-22 15:25:00-05:00    40.173942
2023-12-22 15:30:00-05:00    40.173942
2023-12-22 15:35:00-05:00    40.173942
2023-12-22 15:40:00-05:00    40.173942
2023-12-22 15:45:00-05:00    40.173942
2023-12-22 15:50:00-05:00    40.173942
2023-12-22 15:55:00-05:00    45.034035
2023-12-26 09:30:00-05:00    64.959724
2023-12-26 09:35:00-05:00    39.116656
2023-12-26 09:40:00-05:00    41.399118
2023-12-26 09:45:00-05:00    40.580107
2023-12-26 09:50:00-05:00    49.233953
2023-12-26 09:55:00-05:00    50.017845
2023-12-26 10:00:00-05:00    53.135468
2023-12-26 10:05:00-05:00    61.926518
2023-12-26 10:10:00-05:00    56.718482
2023-12-26 10:15:00-05:00    59.642446
2023-12-26 10:20:00-05:00    55.597528
2023-12-26 10:25:00-05:00    52.709773
2023-12-26 10:30:00-05:00    51.745215
2023-12-26 10:35:00-05:00    51.745215
2023-12-26 10:40:00-05:00    51.745215
2023-12-26 10:45:00-05:00    56.677155
2023-12-26 10:50:00-05:00    54.300637
2023-12-26 10:55:00-05:00    50.823852
2023-12-26 11:00:00-05:00    50.823852
2023-12-26 11:05:00-05:00    52.011540
2023-12-26 11:10:00-05:00    53.228510
2023-12-26 11:15:00-05:00    55.650453
2023-12-26 11:20:00-05:00    55.650453
2023-12-26 11:25:00-05:00    55.650453
2023-12-26 11:30:00-05:00    60.729599
2023-12-26 11:35:00-05:00    57.201773
2023-12-26 11:40:00-05:00    55.467114
2023-12-26 11:45:00-05:00    50.158523
2023-12-26 11:50:00-05:00    58.413228
2023-12-26 11:55:00-05:00    60.662058
2023-12-26 12:00:00-05:00    55.789034
2023-12-26 12:05:00-05:00    59.309194
2023-12-26 12:10:00-05:00    59.309194
2023-12-26 12:15:00-05:00    60.524589
2023-12-26 12:20:00-05:00    54.781206
2023-12-26 12:25:00-05:00    55.146466
2023-12-26 12:30:00-05:00    48.632901
2023-12-26 12:35:00-05:00    43.144424
2023-12-26 12:40:00-05:00    46.401508
2023-12-26 12:45:00-05:00    46.401508
2023-12-26 12:50:00-05:00    46.401508
2023-12-26 12:55:00-05:00    43.303165
2023-12-26 13:00:00-05:00    39.112525
2023-12-26 13:05:00-05:00    44.859222
2023-12-26 13:10:00-05:00    35.242634
2023-12-26 13:15:00-05:00    31.595519
2023-12-26 13:20:00-05:00    38.454535
2023-12-26 13:25:00-05:00    40.072652
2023-12-26 13:30:00-05:00    51.137815
2023-12-26 13:35:00-05:00    47.589266
2023-12-26 13:40:00-05:00    48.862924
2023-12-26 13:45:00-05:00    47.616754
2023-12-26 13:50:00-05:00    46.343439
2023-12-26 13:55:00-05:00    47.845383
2023-12-26 14:00:00-05:00    55.832450
2023-12-26 14:05:00-05:00    58.133579
2023-12-26 14:10:00-05:00    58.133579
2023-12-26 14:15:00-05:00    59.361802
2023-12-26 14:20:00-05:00    57.543799
2023-12-26 14:25:00-05:00    57.543799
2023-12-26 14:30:00-05:00    53.728522
2023-12-26 14:35:00-05:00    53.728522
2023-12-26 14:40:00-05:00    53.728522
2023-12-26 14:45:00-05:00    58.841644
2023-12-26 14:50:00-05:00    56.596042
2023-12-26 14:55:00-05:00    56.596042
2023-12-26 15:00:00-05:00    60.125139
2023-12-26 15:05:00-05:00    61.797993
2023-12-26 15:10:00-05:00    56.818587
2023-12-26 15:15:00-05:00    52.067734
2023-12-26 15:20:00-05:00    52.067734
2023-12-26 15:25:00-05:00    54.201161
2023-12-26 15:30:00-05:00    56.337225
2023-12-26 15:35:00-05:00    58.424668
2023-12-26 15:40:00-05:00    62.306747
2023-12-26 15:45:00-05:00    67.246792
2023-12-26 15:50:00-05:00    61.464137
2023-12-26 15:55:00-05:00    67.486600
2023-12-27 09:30:00-05:00    43.623747
2023-12-27 09:35:00-05:00    45.227886
2023-12-27 09:40:00-05:00    39.218169
2023-12-27 09:45:00-05:00    51.667626
2023-12-27 09:50:00-05:00    52.665127
2023-12-27 09:55:00-05:00    46.787462
2023-12-27 10:00:00-05:00    41.474400
2023-12-27 10:05:00-05:00    38.885687
2023-12-27 10:10:00-05:00    42.964338
2023-12-27 10:15:00-05:00    47.260446
2023-12-27 10:20:00-05:00    56.239022
2023-12-27 10:25:00-05:00    66.842385
2023-12-27 10:30:00-05:00    69.149992
2023-12-27 10:35:00-05:00    75.442248
2023-12-27 10:40:00-05:00    75.595405
2023-12-27 10:45:00-05:00    65.698589
2023-12-27 10:50:00-05:00    66.695544
2023-12-27 10:55:00-05:00    66.695544
2023-12-27 11:00:00-05:00    57.076276
2023-12-27 11:05:00-05:00    61.285537
2023-12-27 11:10:00-05:00    60.374485
2023-12-27 11:15:00-05:00    60.374485
2023-12-27 11:20:00-05:00    61.948756
2023-12-27 11:25:00-05:00    61.510002
2023-12-27 11:30:00-05:00    61.510002
2023-12-27 11:35:00-05:00    61.009344
2023-12-27 11:40:00-05:00    62.958415
2023-12-27 11:45:00-05:00    63.770975
2023-12-27 11:50:00-05:00    64.607404
2023-12-27 11:55:00-05:00    63.876912
2023-12-27 12:00:00-05:00    53.249961
2023-12-27 12:05:00-05:00    55.370902
2023-12-27 12:10:00-05:00    56.435336
2023-12-27 12:15:00-05:00    57.525881
2023-12-27 12:20:00-05:00    54.610658
2023-12-27 12:25:00-05:00    51.729845
2023-12-27 12:30:00-05:00    54.300062
2023-12-27 12:35:00-05:00    48.713856
2023-12-27 12:40:00-05:00    54.952710
2023-12-27 12:45:00-05:00    57.195828
2023-12-27 12:50:00-05:00    55.643833
2023-12-27 12:55:00-05:00    56.903209
2023-12-27 13:00:00-05:00    65.107675
2023-12-27 13:05:00-05:00    60.459535
2023-12-27 13:10:00-05:00    51.262927
2023-12-27 13:15:00-05:00    51.262927
2023-12-27 13:20:00-05:00    47.726679
2023-12-27 13:25:00-05:00    48.939412
2023-12-27 13:30:00-05:00    36.371199
2023-12-27 13:35:00-05:00    34.189245
2023-12-27 13:40:00-05:00    32.777411
2023-12-27 13:45:00-05:00    32.777411
2023-12-27 13:50:00-05:00    35.849701
2023-12-27 13:55:00-05:00    35.849701
2023-12-27 14:00:00-05:00    30.931184
2023-12-27 14:05:00-05:00    32.591458
2023-12-27 14:10:00-05:00    34.390934
2023-12-27 14:15:00-05:00    33.535802
2023-12-27 14:20:00-05:00    35.161404
2023-12-27 14:25:00-05:00    37.008995
2023-12-27 14:30:00-05:00    44.020796
2023-12-27 14:35:00-05:00    42.468166
2023-12-27 14:40:00-05:00    39.107148
2023-12-27 14:45:00-05:00    40.931392
2023-12-27 14:50:00-05:00    37.764173
2023-12-27 14:55:00-05:00    40.799666
2023-12-27 15:00:00-05:00    38.286139
2023-12-27 15:05:00-05:00    40.267627
2023-12-27 15:10:00-05:00    36.482704
2023-12-27 15:15:00-05:00    37.743246
2023-12-27 15:20:00-05:00    38.617281
2023-12-27 15:25:00-05:00    40.854557
2023-12-27 15:30:00-05:00    47.084087
2023-12-27 15:35:00-05:00    47.084087
2023-12-27 15:40:00-05:00    41.958714
2023-12-27 15:45:00-05:00    49.804332
2023-12-27 15:50:00-05:00    51.430797
2023-12-27 15:55:00-05:00    54.982243
2023-12-28 09:30:00-05:00    27.709180
2023-12-28 09:35:00-05:00    37.914151
2023-12-28 09:40:00-05:00    34.624428
2023-12-28 09:45:00-05:00    41.215769
2023-12-28 09:50:00-05:00    50.223996
2023-12-28 09:55:00-05:00    51.814117
2023-12-28 10:00:00-05:00    54.916699
2023-12-28 10:05:00-05:00    52.202076
2023-12-28 10:10:00-05:00    49.563602
2023-12-28 10:15:00-05:00    52.167209
2023-12-28 10:20:00-05:00    52.167209
2023-12-28 10:25:00-05:00    52.733242
2023-12-28 10:30:00-05:00    45.404556
2023-12-28 10:35:00-05:00    50.529089
2023-12-28 10:40:00-05:00    52.129665
2023-12-28 10:45:00-05:00    49.175445
2023-12-28 10:50:00-05:00    42.277445
2023-12-28 10:55:00-05:00    46.340468
2023-12-28 11:00:00-05:00    40.265996
2023-12-28 11:05:00-05:00    37.611501
2023-12-28 11:10:00-05:00    39.750023
2023-12-28 11:15:00-05:00    33.555668
2023-12-28 11:20:00-05:00    37.735515
2023-12-28 11:25:00-05:00    40.746012
2023-12-28 11:30:00-05:00    43.678632
2023-12-28 11:35:00-05:00    42.194401
2023-12-28 11:40:00-05:00    42.178936
2023-12-28 11:45:00-05:00    43.306842
2023-12-28 11:50:00-05:00    39.189838
2023-12-28 11:55:00-05:00    40.576732
2023-12-28 12:00:00-05:00    44.026569
2023-12-28 12:05:00-05:00    40.486577
2023-12-28 12:10:00-05:00    40.486577
2023-12-28 12:15:00-05:00    43.137825
2023-12-28 12:20:00-05:00    42.127097
2023-12-28 12:25:00-05:00    42.127097
2023-12-28 12:30:00-05:00    46.461610
2023-12-28 12:35:00-05:00    44.098527
2023-12-28 12:40:00-05:00    45.603201
2023-12-28 12:45:00-05:00    45.603201
2023-12-28 12:50:00-05:00    41.697697
2023-12-28 12:55:00-05:00    43.436406
2023-12-28 13:00:00-05:00    35.462602
2023-12-28 13:05:00-05:00    32.692758
2023-12-28 13:10:00-05:00    32.438088
2023-12-28 13:15:00-05:00    41.666002
2023-12-28 13:20:00-05:00    43.246799
2023-12-28 13:25:00-05:00    39.764905
2023-12-28 13:30:00-05:00    33.073479
2023-12-28 13:35:00-05:00    32.650748
2023-12-28 13:40:00-05:00    32.207755
2023-12-28 13:45:00-05:00    29.610241
2023-12-28 13:50:00-05:00    36.915204
2023-12-28 13:55:00-05:00    34.961523
2023-12-28 14:00:00-05:00    38.468482
2023-12-28 14:05:00-05:00    38.246515
2023-12-28 14:10:00-05:00    35.184002
2023-12-28 14:15:00-05:00    32.207976
2023-12-28 14:20:00-05:00    28.720308
2023-12-28 14:25:00-05:00    34.453311
2023-12-28 14:30:00-05:00    30.886088
2023-12-28 14:35:00-05:00    28.502655
2023-12-28 14:40:00-05:00    30.317117
2023-12-28 14:45:00-05:00    34.254964
2023-12-28 14:50:00-05:00    37.923005
2023-12-28 14:55:00-05:00    36.059723
2023-12-28 15:00:00-05:00    35.751777
2023-12-28 15:05:00-05:00    35.751777
2023-12-28 15:10:00-05:00    35.751777
2023-12-28 15:15:00-05:00    40.300216
2023-12-28 15:20:00-05:00    44.529328
2023-12-28 15:25:00-05:00    44.495662
2023-12-28 15:30:00-05:00    46.725414
2023-12-28 15:35:00-05:00    48.894207
2023-12-28 15:40:00-05:00    44.989303
2023-12-28 15:45:00-05:00    41.360692
2023-12-28 15:50:00-05:00    35.949978
2023-12-28 15:55:00-05:00    41.376967
2023-12-29 09:30:00-05:00    10.641291
2023-12-29 09:35:00-05:00    17.845277
2023-12-29 09:40:00-05:00    17.916477
2023-12-29 09:45:00-05:00    29.432369
2023-12-29 09:50:00-05:00    27.551146
2023-12-29 09:55:00-05:00    33.561764
2023-12-29 10:00:00-05:00    39.973909
2023-12-29 10:05:00-05:00    39.923543
2023-12-29 10:10:00-05:00    42.668521
2023-12-29 10:15:00-05:00    46.975956
2023-12-29 10:20:00-05:00    44.409391
2023-12-29 10:25:00-05:00    48.673780
2023-12-29 10:30:00-05:00    50.380713
2023-12-29 10:35:00-05:00    50.380713
2023-12-29 10:40:00-05:00    46.143043
2023-12-29 10:45:00-05:00    46.831184
2023-12-29 10:50:00-05:00    48.938477
2023-12-29 10:55:00-05:00    50.351329
2023-12-29 11:00:00-05:00    51.080322
2023-12-29 11:05:00-05:00    52.448498
2023-12-29 11:10:00-05:00    48.573739
2023-12-29 11:15:00-05:00    49.408944
2023-12-29 11:20:00-05:00    54.212678
2023-12-29 11:25:00-05:00    49.955670
2023-12-29 11:30:00-05:00    51.593134
2023-12-29 11:35:00-05:00    52.431073
2023-12-29 11:40:00-05:00    52.431073
2023-12-29 11:45:00-05:00    55.133937
2023-12-29 11:50:00-05:00    55.261679
2023-12-29 11:55:00-05:00    55.092754
2023-12-29 12:00:00-05:00    56.124279
2023-12-29 12:05:00-05:00    56.340199
2023-12-29 12:10:00-05:00    63.009329
2023-12-29 12:15:00-05:00    64.716472
2023-12-29 12:20:00-05:00    63.177921
2023-12-29 12:25:00-05:00    61.538001
2023-12-29 12:30:00-05:00    62.099041
2023-12-29 12:35:00-05:00    59.469928
2023-12-29 12:40:00-05:00    60.627215
2023-12-29 12:45:00-05:00    51.021848
2023-12-29 12:50:00-05:00    49.583526
2023-12-29 12:55:00-05:00    58.296409
2023-12-29 13:00:00-05:00    41.709414
2023-12-29 13:05:00-05:00    40.923634

In [12]:
rsis_1d = talib.RSI(data_1d['Close'], timeperiod=14)

In [13]:
rsis_1d

Date
2023-11-09          NaN
2023-11-10          NaN
2023-11-13          NaN
2023-11-14          NaN
2023-11-15          NaN
2023-11-16          NaN
2023-11-17          NaN
2023-11-20          NaN
2023-11-21          NaN
2023-11-22          NaN
2023-11-24          NaN
2023-11-27          NaN
2023-11-28          NaN
2023-11-29          NaN
2023-11-30    80.653223
2023-12-01    81.646460
2023-12-04    65.817329
2023-12-05    60.852124
2023-12-06    58.209394
2023-12-07    56.270242
2023-12-08    47.815581
2023-12-11    45.775981
2023-12-12    45.014163
2023-12-13    55.589034
2023-12-14    59.054155
2023-12-15    55.151694
2023-12-18    54.786162
2023-12-19    57.131927
2023-12-20    57.235813
2023-12-21    60.050747
2023-12-22    57.197503
2023-12-26    58.100229
2023-12-27    58.454075
2023-12-28    54.489412
2023-12-29    51.216087
2024-01-02    49.243920
2024-01-03    41.444018
2024-01-04    41.780666
2024-01-05    44.032947
2024-01-08    42.932238
2024-01-09    41.132871
2024-01-10    40.293484
2024-01-11    38.597004
2024-01-12    46.128420
2024-01-16    42.628191
2024-01-17    38.398951
2024-01-18    41.618422
2024-01-19    39.665004
dtype: float64

In [14]:
rsismas_5m = talib.SMA(rsis_5m, timeperiod=14)
rsismas_15m = talib.SMA(rsis_15m, timeperiod=14)
rsismas_30m = talib.SMA(rsis_30m, timeperiod=14)
rsismas_60m = talib.SMA(rsis_60m, timeperiod=14)

In [15]:
rsismas_5m

Datetime
2023-12-20 09:30:00-05:00          NaN
2023-12-20 09:35:00-05:00          NaN
2023-12-20 09:40:00-05:00          NaN
2023-12-20 09:45:00-05:00          NaN
2023-12-20 09:50:00-05:00          NaN
2023-12-20 09:55:00-05:00          NaN
2023-12-20 10:00:00-05:00          NaN
2023-12-20 10:05:00-05:00          NaN
2023-12-20 10:10:00-05:00          NaN
2023-12-20 10:15:00-05:00          NaN
2023-12-20 10:20:00-05:00          NaN
2023-12-20 10:25:00-05:00          NaN
2023-12-20 10:30:00-05:00          NaN
2023-12-20 10:35:00-05:00          NaN
2023-12-20 10:40:00-05:00          NaN
2023-12-20 10:45:00-05:00          NaN
2023-12-20 10:50:00-05:00          NaN
2023-12-20 10:55:00-05:00          NaN
2023-12-20 11:00:00-05:00          NaN
2023-12-20 11:05:00-05:00          NaN
2023-12-20 11:10:00-05:00          NaN
2023-12-20 11:15:00-05:00          NaN
2023-12-20 11:20:00-05:00          NaN
2023-12-20 11:25:00-05:00          NaN
2023-12-20 11:30:00-05:00          NaN
2023-12-20 11:35:00-05:00          NaN
2023-12-20 11:40:00-05:00          NaN
2023-12-20 11:45:00-05:00    53.176053
2023-12-20 11:50:00-05:00    53.111557
2023-12-20 11:55:00-05:00    53.487330
2023-12-20 12:00:00-05:00    53.553107
2023-12-20 12:05:00-05:00    53.857929
2023-12-20 12:10:00-05:00    53.758887
2023-12-20 12:15:00-05:00    53.766912
2023-12-20 12:20:00-05:00    53.359992
2023-12-20 12:25:00-05:00    52.728882
2023-12-20 12:30:00-05:00    52.348278
2023-12-20 12:35:00-05:00    51.384596
2023-12-20 12:40:00-05:00    51.331484
2023-12-20 12:45:00-05:00    51.555663
2023-12-20 12:50:00-05:00    51.493210
2023-12-20 12:55:00-05:00    51.423868
2023-12-20 13:00:00-05:00    51.678943
2023-12-20 13:05:00-05:00    51.361763
2023-12-20 13:10:00-05:00    51.160569
2023-12-20 13:15:00-05:00    51.280769
2023-12-20 13:20:00-05:00    51.197027
2023-12-20 13:25:00-05:00    51.096764
2023-12-20 13:30:00-05:00    51.286192
2023-12-20 13:35:00-05:00    51.546101
2023-12-20 13:40:00-05:00    51.637551
2023-12-20 13:45:00-05:00    52.214789
2023-12-20 13:50:00-05:00    52.194414
2023-12-20 13:55:00-05:00    52.072514
2023-12-20 14:00:00-05:00    51.974142
2023-12-20 14:05:00-05:00    51.712275
2023-12-20 14:10:00-05:00    51.455616
2023-12-20 14:15:00-05:00    51.916735
2023-12-20 14:20:00-05:00    52.069245
2023-12-20 14:25:00-05:00    51.504978
2023-12-20 14:30:00-05:00    51.190539
2023-12-20 14:35:00-05:00    50.448511
2023-12-20 14:40:00-05:00    49.234244
2023-12-20 14:45:00-05:00    47.385473
2023-12-20 14:50:00-05:00    45.361022
2023-12-20 14:55:00-05:00    43.194905
2023-12-20 15:00:00-05:00    40.805673
2023-12-20 15:05:00-05:00    38.431573
2023-12-20 15:10:00-05:00    36.848762
2023-12-20 15:15:00-05:00    36.254188
2023-12-20 15:20:00-05:00    35.042640
2023-12-20 15:25:00-05:00    33.344391
2023-12-20 15:30:00-05:00    31.873163
2023-12-20 15:35:00-05:00    30.521094
2023-12-20 15:40:00-05:00    29.818256
2023-12-20 15:45:00-05:00    29.288317
2023-12-20 15:50:00-05:00    29.031429
2023-12-20 15:55:00-05:00    29.256846
2023-12-21 09:30:00-05:00    32.407853
2023-12-21 09:35:00-05:00    35.547741
2023-12-21 09:40:00-05:00    38.454273
2023-12-21 09:45:00-05:00    41.920396
2023-12-21 09:50:00-05:00    44.225603
2023-12-21 09:55:00-05:00    45.363002
2023-12-21 10:00:00-05:00    46.646178
2023-12-21 10:05:00-05:00    47.974998
2023-12-21 10:10:00-05:00    49.523366
2023-12-21 10:15:00-05:00    51.377142
2023-12-21 10:20:00-05:00    52.916484
2023-12-21 10:25:00-05:00    54.546728
2023-12-21 10:30:00-05:00    56.354918
2023-12-21 10:35:00-05:00    58.185686
2023-12-21 10:40:00-05:00    57.398033
2023-12-21 10:45:00-05:00    56.425778
2023-12-21 10:50:00-05:00    55.648214
2023-12-21 10:55:00-05:00    54.181358
2023-12-21 11:00:00-05:00    53.768407
2023-12-21 11:05:00-05:00    53.528235
2023-12-21 11:10:00-05:00    53.659760
2023-12-21 11:15:00-05:00    54.058395
2023-12-21 11:20:00-05:00    54.368511
2023-12-21 11:25:00-05:00    54.549513
2023-12-21 11:30:00-05:00    54.247990
2023-12-21 11:35:00-05:00    54.021800
2023-12-21 11:40:00-05:00    53.655634
2023-12-21 11:45:00-05:00    53.572256
2023-12-21 11:50:00-05:00    53.170990
2023-12-21 11:55:00-05:00    53.172210
2023-12-21 12:00:00-05:00    53.372838
2023-12-21 12:05:00-05:00    53.332925
2023-12-21 12:10:00-05:00    53.031761
2023-12-21 12:15:00-05:00    52.944541
2023-12-21 12:20:00-05:00    52.633109
2023-12-21 12:25:00-05:00    51.814025
2023-12-21 12:30:00-05:00    51.058208
2023-12-21 12:35:00-05:00    50.308247
2023-12-21 12:40:00-05:00    49.863574
2023-12-21 12:45:00-05:00    49.525643
2023-12-21 12:50:00-05:00    48.852641
2023-12-21 12:55:00-05:00    48.127199
2023-12-21 13:00:00-05:00    47.694434
2023-12-21 13:05:00-05:00    47.005388
2023-12-21 13:10:00-05:00    46.293092
2023-12-21 13:15:00-05:00    45.575369
2023-12-21 13:20:00-05:00    45.316647
2023-12-21 13:25:00-05:00    45.054428
2023-12-21 13:30:00-05:00    44.929970
2023-12-21 13:35:00-05:00    44.769962
2023-12-21 13:40:00-05:00    44.371384
2023-12-21 13:45:00-05:00    43.926713
2023-12-21 13:50:00-05:00    43.448040
2023-12-21 13:55:00-05:00    43.378202
2023-12-21 14:00:00-05:00    43.944584
2023-12-21 14:05:00-05:00    44.387131
2023-12-21 14:10:00-05:00    44.701789
2023-12-21 14:15:00-05:00    45.601116
2023-12-21 14:20:00-05:00    46.577713
2023-12-21 14:25:00-05:00    48.143526
2023-12-21 14:30:00-05:00    49.575745
2023-12-21 14:35:00-05:00    50.957579
2023-12-21 14:40:00-05:00    52.499613
2023-12-21 14:45:00-05:00    53.810556
2023-12-21 14:50:00-05:00    54.821565
2023-12-21 14:55:00-05:00    55.929466
2023-12-21 15:00:00-05:00    57.394295
2023-12-21 15:05:00-05:00    57.878097
2023-12-21 15:10:00-05:00    58.177324
2023-12-21 15:15:00-05:00    58.369073
2023-12-21 15:20:00-05:00    58.572205
2023-12-21 15:25:00-05:00    58.779902
2023-12-21 15:30:00-05:00    59.086217
2023-12-21 15:35:00-05:00    59.140644
2023-12-21 15:40:00-05:00    58.831634
2023-12-21 15:45:00-05:00    58.447165
2023-12-21 15:50:00-05:00    58.025362
2023-12-21 15:55:00-05:00    57.739783
2023-12-22 09:30:00-05:00    59.373587
2023-12-22 09:35:00-05:00    61.000520
2023-12-22 09:40:00-05:00    62.435932
2023-12-22 09:45:00-05:00    64.130758
2023-12-22 09:50:00-05:00    64.946164
2023-12-22 09:55:00-05:00    65.833163
2023-12-22 10:00:00-05:00    67.008695
2023-12-22 10:05:00-05:00    67.876075
2023-12-22 10:10:00-05:00    68.834292
2023-12-22 10:15:00-05:00    69.279398
2023-12-22 10:20:00-05:00    68.923135
2023-12-22 10:25:00-05:00    68.502997
2023-12-22 10:30:00-05:00    67.696970
2023-12-22 10:35:00-05:00    67.353647
2023-12-22 10:40:00-05:00    65.291856
2023-12-22 10:45:00-05:00    62.703679
2023-12-22 10:50:00-05:00    59.425142
2023-12-22 10:55:00-05:00    56.602898
2023-12-22 11:00:00-05:00    54.065482
2023-12-22 11:05:00-05:00    51.963384
2023-12-22 11:10:00-05:00    49.998156
2023-12-22 11:15:00-05:00    47.765441
2023-12-22 11:20:00-05:00    45.267170
2023-12-22 11:25:00-05:00    43.263941
2023-12-22 11:30:00-05:00    42.190992
2023-12-22 11:35:00-05:00    41.129808
2023-12-22 11:40:00-05:00    39.911820
2023-12-22 11:45:00-05:00    37.952517
2023-12-22 11:50:00-05:00    36.827579
2023-12-22 11:55:00-05:00    36.183790
2023-12-22 12:00:00-05:00    36.366735
2023-12-22 12:05:00-05:00    36.339679
2023-12-22 12:10:00-05:00    36.844655
2023-12-22 12:15:00-05:00    37.275626
2023-12-22 12:20:00-05:00    37.592940
2023-12-22 12:25:00-05:00    38.047202
2023-12-22 12:30:00-05:00    38.424790
2023-12-22 12:35:00-05:00    38.802207
2023-12-22 12:40:00-05:00    39.177798
2023-12-22 12:45:00-05:00    39.748860
2023-12-22 12:50:00-05:00    40.669926
2023-12-22 12:55:00-05:00    42.119636
2023-12-22 13:00:00-05:00    42.898323
2023-12-22 13:05:00-05:00    43.443381
2023-12-22 13:10:00-05:00    43.875177
2023-12-22 13:15:00-05:00    44.082538
2023-12-22 13:20:00-05:00    44.574115
2023-12-22 13:25:00-05:00    45.129965
2023-12-22 13:30:00-05:00    45.046061
2023-12-22 13:35:00-05:00    45.075934
2023-12-22 13:40:00-05:00    44.971661
2023-12-22 13:45:00-05:00    44.684359
2023-12-22 13:50:00-05:00    44.177678
2023-12-22 13:55:00-05:00    43.390322
2023-12-22 14:00:00-05:00    42.407364
2023-12-22 14:05:00-05:00    41.456003
2023-12-22 14:10:00-05:00    40.415712
2023-12-22 14:15:00-05:00    39.507196
2023-12-22 14:20:00-05:00    37.906984
2023-12-22 14:25:00-05:00    36.459861
2023-12-22 14:30:00-05:00    34.728521
2023-12-22 14:35:00-05:00    32.997019
2023-12-22 14:40:00-05:00    31.868389
2023-12-22 14:45:00-05:00    30.917427
2023-12-22 14:50:00-05:00    30.724712
2023-12-22 14:55:00-05:00    30.857550
2023-12-22 15:00:00-05:00    30.844077
2023-12-22 15:05:00-05:00    30.824378
2023-12-22 15:10:00-05:00    31.342437
2023-12-22 15:15:00-05:00    31.959881
2023-12-22 15:20:00-05:00    32.811975
2023-12-22 15:25:00-05:00    33.548712
2023-12-22 15:30:00-05:00    34.788629
2023-12-22 15:35:00-05:00    36.166376
2023-12-22 15:40:00-05:00    37.544123
2023-12-22 15:45:00-05:00    38.657676
2023-12-22 15:50:00-05:00    39.610730
2023-12-22 15:55:00-05:00    40.554806
2023-12-26 09:30:00-05:00    42.459170
2023-12-26 09:35:00-05:00    42.301953
2023-12-26 09:40:00-05:00    42.454079
2023-12-26 09:45:00-05:00    42.691246
2023-12-26 09:50:00-05:00    43.204389
2023-12-26 09:55:00-05:00    43.855213
2023-12-26 10:00:00-05:00    44.608611
2023-12-26 10:05:00-05:00    46.162367
2023-12-26 10:10:00-05:00    47.344120
2023-12-26 10:15:00-05:00    48.734727
2023-12-26 10:20:00-05:00    49.836412
2023-12-26 10:25:00-05:00    50.731828
2023-12-26 10:30:00-05:00    51.558348
2023-12-26 10:35:00-05:00    52.037718
2023-12-26 10:40:00-05:00    51.093824
2023-12-26 10:45:00-05:00    52.348146
2023-12-26 10:50:00-05:00    53.269683
2023-12-26 10:55:00-05:00    54.001379
2023-12-26 11:00:00-05:00    54.114943
2023-12-26 11:05:00-05:00    54.257350
2023-12-26 11:10:00-05:00    54.263996
2023-12-26 11:15:00-05:00    53.815705
2023-12-26 11:20:00-05:00    53.739417
2023-12-26 11:25:00-05:00    53.454275
2023-12-26 11:30:00-05:00    53.820852
2023-12-26 11:35:00-05:00    54.141709
2023-12-26 11:40:00-05:00    54.407559
2023-12-26 11:45:00-05:00    54.294224
2023-12-26 11:50:00-05:00    54.770510
2023-12-26 11:55:00-05:00    55.055146
2023-12-26 12:00:00-05:00    55.161460
2023-12-26 12:05:00-05:00    55.767556
2023-12-26 12:10:00-05:00    56.373652
2023-12-26 12:15:00-05:00    56.981727
2023-12-26 12:20:00-05:00    57.092634
2023-12-26 12:25:00-05:00    57.056634
2023-12-26 12:30:00-05:00    56.555381
2023-12-26 12:35:00-05:00    55.662093
2023-12-26 12:40:00-05:00    54.638658
2023-12-26 12:45:00-05:00    53.867210
2023-12-26 12:50:00-05:00    53.219667
2023-12-26 12:55:00-05:00    52.729999
2023-12-26 13:00:00-05:00    51.351377
2023-12-26 13:05:00-05:00    50.222603
2023-12-26 13:10:00-05:00    48.755003
2023-12-26 13:15:00-05:00    46.775455
2023-12-26 13:20:00-05:00    45.285836
2023-12-26 13:25:00-05:00    43.824984
2023-12-26 13:30:00-05:00    43.564742
2023-12-26 13:35:00-05:00    43.024942
2023-12-26 13:40:00-05:00    43.041372
2023-12-26 13:45:00-05:00    43.360824
2023-12-26 13:50:00-05:00    43.356676
2023-12-26 13:55:00-05:00    43.459810
2023-12-26 14:00:00-05:00    44.133449
2023-12-26 14:05:00-05:00    45.192764
2023-12-26 14:10:00-05:00    46.551411
2023-12-26 14:15:00-05:00    47.587309
2023-12-26 14:20:00-05:00    49.180250
2023-12-26 14:25:00-05:00    51.033698
2023-12-26 14:30:00-05:00    52.124697
2023-12-26 14:35:00-05:00    53.100117
2023-12-26 14:40:00-05:00    53.285167
2023-12-26 14:45:00-05:00    54.088909
2023-12-26 14:50:00-05:00    54.641274
2023-12-26 14:55:00-05:00    55.282652
2023-12-26 15:00:00-05:00    56.267059
2023-12-26 15:05:00-05:00    57.263674
2023-12-26 15:10:00-05:00    57.334113
2023-12-26 15:15:00-05:00    56.900838
2023-12-26 15:20:00-05:00    56.467563
2023-12-26 15:25:00-05:00    56.098946
2023-12-26 15:30:00-05:00    56.012762
2023-12-26 15:35:00-05:00    56.075681
2023-12-26 15:40:00-05:00    56.688412
2023-12-26 15:45:00-05:00    57.654002
2023-12-26 15:50:00-05:00    58.206546
2023-12-26 15:55:00-05:00    58.824043
2023-12-27 09:30:00-05:00    57.897450
2023-12-27 09:35:00-05:00    57.085439
2023-12-27 09:40:00-05:00    55.592084
2023-12-27 09:45:00-05:00    54.868487
2023-12-27 09:50:00-05:00    54.571811
2023-12-27 09:55:00-05:00    54.194649
2023-12-27 10:00:00-05:00    53.437982
2023-12-27 10:05:00-05:00    52.344019
2023-12-27 10:10:00-05:00    51.388813
2023-12-27 10:15:00-05:00    50.591369
2023-12-27 10:20:00-05:00    50.157960
2023-12-27 10:25:00-05:00    50.129074
2023-12-27 10:30:00-05:00    50.678063
2023-12-27 10:35:00-05:00    51.246324
2023-12-27 10:40:00-05:00    53.530014
2023-12-27 10:45:00-05:00    54.992207
2023-12-27 10:50:00-05:00    56.954876
2023-12-27 10:55:00-05:00    58.028299
2023-12-27 11:00:00-05:00    58.343381
2023-12-27 11:05:00-05:00    59.378958
2023-12-27 11:10:00-05:00    60.728964
2023-12-27 11:15:00-05:00    62.263878
2023-12-27 11:20:00-05:00    63.619908
2023-12-27 11:25:00-05:00    64.637734
2023-12-27 11:30:00-05:00    65.014232
2023-12-27 11:35:00-05:00    64.597586
2023-12-27 11:40:00-05:00    64.155331
2023-12-27 11:45:00-05:00    63.321669
2023-12-27 11:50:00-05:00    62.536811
2023-12-27 11:55:00-05:00    62.406692
2023-12-27 12:00:00-05:00    61.446293
2023-12-27 12:05:00-05:00    60.637390
2023-12-27 12:10:00-05:00    60.591608
2023-12-27 12:15:00-05:00    60.323061
2023-12-27 12:20:00-05:00    59.911359
2023-12-27 12:25:00-05:00    59.293885
2023-12-27 12:30:00-05:00    58.747550
2023-12-27 12:35:00-05:00    57.833539
2023-12-27 12:40:00-05:00    57.365162
2023-12-27 12:45:00-05:00    57.092768
2023-12-27 12:50:00-05:00    56.570297
2023-12-27 12:55:00-05:00    56.079743
2023-12-27 13:00:00-05:00    56.115476
2023-12-27 13:05:00-05:00    55.871378
2023-12-27 13:10:00-05:00    55.729447
2023-12-27 13:15:00-05:00    55.436020
2023-12-27 13:20:00-05:00    54.813973
2023-12-27 13:25:00-05:00    54.200654
2023-12-27 13:30:00-05:00    52.897835
2023-12-27 13:35:00-05:00    51.644935
2023-12-27 13:40:00-05:00    50.107603
2023-12-27 13:45:00-05:00    48.969286
2023-12-27 13:50:00-05:00    47.604785
2023-12-27 13:55:00-05:00    46.080062
2023-12-27 14:00:00-05:00    44.314873
2023-12-27 14:05:00-05:00    42.578319
2023-12-27 14:10:00-05:00    40.384266
2023-12-27 14:15:00-05:00    38.461142
2023-12-27 14:20:00-05:00    37.311033
2023-12-27 14:25:00-05:00    36.292895
2023-12-27 14:30:00-05:00    36.028189
2023-12-27 14:35:00-05:00    35.565958
2023-12-27 14:40:00-05:00    35.761383
2023-12-27 14:45:00-05:00    36.242964
2023-12-27 14:50:00-05:00    36.599162
2023-12-27 14:55:00-05:00    37.172180
2023-12-27 15:00:00-05:00    37.346211
2023-12-27 15:05:00-05:00    37.661777
2023-12-27 15:10:00-05:00    38.058315
2023-12-27 15:15:00-05:00    38.426299
2023-12-27 15:20:00-05:00    38.728181
2023-12-27 15:25:00-05:00    39.250950
2023-12-27 15:30:00-05:00    40.102570
2023-12-27 15:35:00-05:00    40.822219
2023-12-27 15:40:00-05:00    40.674928
2023-12-27 15:45:00-05:00    41.198940
2023-12-27 15:50:00-05:00    42.079200
2023-12-27 15:55:00-05:00    43.082832
2023-12-28 09:30:00-05:00    42.364619
2023-12-28 09:35:00-05:00    42.158510
2023-12-28 09:40:00-05:00    41.896960
2023-12-28 09:45:00-05:00    41.964684
2023-12-28 09:50:00-05:00    42.946205
2023-12-28 09:55:00-05:00    43.951267
2023-12-28 10:00:00-05:00    45.115511
2023-12-28 10:05:00-05:00    45.926048
2023-12-28 10:10:00-05:00    46.103156
2023-12-28 10:15:00-05:00    46.466237
2023-12-28 10:20:00-05:00    47.195415
2023-12-28 10:25:00-05:00    47.404623
2023-12-28 10:30:00-05:00    46.974177
2023-12-28 10:35:00-05:00    46.656094
2023-12-28 10:40:00-05:00    48.400415
2023-12-28 10:45:00-05:00    49.204793
2023-12-28 10:50:00-05:00    49.751437
2023-12-28 10:55:00-05:00    50.117487
2023-12-28 11:00:00-05:00    49.406201
2023-12-28 11:05:00-05:00    48.391729
2023-12-28 11:10:00-05:00    47.308395
2023-12-28 11:15:00-05:00    45.976508
2023-12-28 11:20:00-05:00    45.131645
2023-12-28 11:25:00-05:00    44.315845
2023-12-28 11:30:00-05:00    43.709518
2023-12-28 11:35:00-05:00    42.956744
2023-12-28 11:40:00-05:00    42.726342
2023-12-28 11:45:00-05:00    42.210468
2023-12-28 11:50:00-05:00    41.286194
2023-12-28 11:55:00-05:00    40.672001
2023-12-28 12:00:00-05:00    40.796938
2023-12-28 12:05:00-05:00    40.378803
2023-12-28 12:10:00-05:00    40.394559
2023-12-28 12:15:00-05:00    40.789296
2023-12-28 12:20:00-05:00    40.959087
2023-12-28 12:25:00-05:00    41.571332
2023-12-28 12:30:00-05:00    42.194625
2023-12-28 12:35:00-05:00    42.434090
2023-12-28 12:40:00-05:00    42.571559
2023-12-28 12:45:00-05:00    42.815045
2023-12-28 12:50:00-05:00    42.780671
2023-12-28 12:55:00-05:00    42.789925
2023-12-28 13:00:00-05:00    42.523694
2023-12-28 13:05:00-05:00    41.960553
2023-12-28 13:10:00-05:00    41.132805
2023-12-28 13:15:00-05:00    41.217049
2023-12-28 13:20:00-05:00    41.414208
2023-12-28 13:25:00-05:00    41.173285
2023-12-28 13:30:00-05:00    40.526598
2023-12-28 13:35:00-05:00    39.849716
2023-12-28 13:40:00-05:00    38.831584
2023-12-28 13:45:00-05:00    37.796706
2023-12-28 13:50:00-05:00    37.176135
2023-12-28 13:55:00-05:00    36.416015
2023-12-28 14:00:00-05:00    36.185357
2023-12-28 14:05:00-05:00    35.814650
2023-12-28 14:10:00-05:00    35.794750
2023-12-28 14:15:00-05:00    35.760123
2023-12-28 14:20:00-05:00    35.494567
2023-12-28 14:25:00-05:00    34.979375
2023-12-28 14:30:00-05:00    34.096467
2023-12-28 14:35:00-05:00    33.292020
2023-12-28 14:40:00-05:00    33.095138
2023-12-28 14:45:00-05:00    33.209724
2023-12-28 14:50:00-05:00    33.617957
2023-12-28 14:55:00-05:00    34.078634
2023-12-28 15:00:00-05:00    33.995532
2023-12-28 15:05:00-05:00    34.051979
2023-12-28 15:10:00-05:00    33.857928
2023-12-28 15:15:00-05:00    34.004621
2023-12-28 15:20:00-05:00    34.672145
2023-12-28 15:25:00-05:00    35.549836
2023-12-28 15:30:00-05:00    36.835915
2023-12-28 15:35:00-05:00    37.867408
2023-12-28 15:40:00-05:00    38.874781
2023-12-28 15:45:00-05:00    39.793212
2023-12-28 15:50:00-05:00    40.195559
2023-12-28 15:55:00-05:00    40.704273
2023-12-29 09:30:00-05:00    38.755579
2023-12-29 09:35:00-05:00    37.454548
2023-12-29 09:40:00-05:00    36.180598
2023-12-29 09:45:00-05:00    35.729211
2023-12-29 09:50:00-05:00    35.143452
2023-12-29 09:55:00-05:00    34.662134
2023-12-29 10:00:00-05:00    34.336747
2023-12-29 10:05:00-05:00    34.010167
2023-12-29 10:10:00-05:00    33.720389
2023-12-29 10:15:00-05:00    33.583371
2023-12-29 10:20:00-05:00    33.541949
2023-12-29 10:25:00-05:00    34.064312
2023-12-29 10:30:00-05:00    35.095079
2023-12-29 10:35:00-05:00    35.738204
2023-12-29 10:40:00-05:00    38.274043
2023-12-29 10:45:00-05:00    40.344465
2023-12-29 10:50:00-05:00    42.560322
2023-12-29 10:55:00-05:00    44.054533
2023-12-29 11:00:00-05:00    45.735189
2023-12-29 11:05:00-05:00    47.084241
2023-12-29 11:10:00-05:00    47.698515
2023-12-29 11:15:00-05:00    48.376044
2023-12-29 11:20:00-05:00    49.200626
2023-12-29 11:25:00-05:00    49.413463
2023-12-29 11:30:00-05:00    49.926587
2023-12-29 11:35:00-05:00    50.194965
2023-12-29 11:40:00-05:00    50.341420
2023-12-29 11:45:00-05:00    50.680936
2023-12-29 11:50:00-05:00    51.332267
2023-12-29 11:55:00-05:00    51.922379
2023-12-29 12:00:00-05:00    52.435651
2023-12-29 12:05:00-05:00    52.863427
2023-12-29 12:10:00-05:00    53.715499
2023-12-29 12:15:00-05:00    54.591783
2023-12-29 12:20:00-05:00    55.634939
2023-12-29 12:25:00-05:00    56.501300
2023-12-29 12:30:00-05:00    57.064612
2023-12-29 12:35:00-05:00    57.744201
2023-12-29 12:40:00-05:00    58.389493
2023-12-29 12:45:00-05:00    58.288834
2023-12-29 12:50:00-05:00    58.085438
2023-12-29 12:55:00-05:00    58.311329
2023-12-29 13:00:00-05:00    57.343310
2023-12-29 13:05:00-05:00    56.331230

In [16]:
rsismas_60m

Datetime
2023-12-20 09:30:00          NaN
2023-12-20 10:30:00          NaN
2023-12-20 11:30:00          NaN
2023-12-20 12:30:00          NaN
2023-12-20 13:30:00          NaN
2023-12-20 14:30:00          NaN
2023-12-20 15:30:00          NaN
2023-12-21 09:30:00          NaN
2023-12-21 10:30:00          NaN
2023-12-21 11:30:00          NaN
2023-12-21 12:30:00          NaN
2023-12-21 13:30:00          NaN
2023-12-21 14:30:00          NaN
2023-12-21 15:30:00          NaN
2023-12-22 09:30:00          NaN
2023-12-22 10:30:00          NaN
2023-12-22 11:30:00          NaN
2023-12-22 12:30:00          NaN
2023-12-22 13:30:00          NaN
2023-12-22 14:30:00          NaN
2023-12-22 15:30:00          NaN
2023-12-26 09:30:00          NaN
2023-12-26 10:30:00          NaN
2023-12-26 11:30:00          NaN
2023-12-26 12:30:00          NaN
2023-12-26 13:30:00          NaN
2023-12-26 14:30:00          NaN
2023-12-26 15:30:00    48.934039
2023-12-27 09:30:00    48.485936
2023-12-27 10:30:00    48.916962
2023-12-27 11:30:00    49.368431
2023-12-27 12:30:00    49.823137
2023-12-27 13:30:00    50.383466
2023-12-27 14:30:00    50.700681
2023-12-27 15:30:00    51.168288
2023-12-28 09:30:00    51.382275
2023-12-28 10:30:00    50.995127
2023-12-28 11:30:00    50.468539
2023-12-28 12:30:00    50.100267
2023-12-28 13:30:00    49.122885
2023-12-28 14:30:00    48.145096
2023-12-28 15:30:00    46.882822
2023-12-29 09:30:00    44.923852
2023-12-29 10:30:00    42.830404
2023-12-29 11:30:00    41.390620
2023-12-29 12:30:00    39.472837
2023-12-29 13:30:00    38.163685
2023-12-29 14:30:00    36.842825
2023-12-29 15:30:00    35.274465
2024-01-02 09:30:00    34.371891
2024-01-02 10:30:00    33.840826
2024-01-02 11:30:00    33.019191
2024-01-02 12:30:00    32.399113
2024-01-02 13:30:00    31.895670
2024-01-02 14:30:00    31.314503
2024-01-02 15:30:00    30.844682
2024-01-03 09:30:00    29.775816
2024-01-03 10:30:00    28.789930
2024-01-03 11:30:00    27.227762
2024-01-03 12:30:00    26.236239
2024-01-03 13:30:00    25.731031
2024-01-03 14:30:00    25.239326
2024-01-03 15:30:00    24.775793
2024-01-04 09:30:00    23.701075
2024-01-04 10:30:00    22.820549
2024-01-04 11:30:00    22.218791
2024-01-04 12:30:00    21.847679
2024-01-04 13:30:00    21.636424
2024-01-04 14:30:00    21.684997
2024-01-04 15:30:00    21.764137
2024-01-05 09:30:00    24.681655
2024-01-05 10:30:00    27.026654
2024-01-05 11:30:00    29.130188
2024-01-05 12:30:00    31.085665
2024-01-05 13:30:00    32.716833
2024-01-05 14:30:00    34.203187
2024-01-05 15:30:00    35.715702
2024-01-08 09:30:00    37.073469
2024-01-08 10:30:00    38.548906
2024-01-08 11:30:00    40.108629
2024-01-08 12:30:00    41.236414
2024-01-08 13:30:00    42.267801
2024-01-08 14:30:00    43.096606
2024-01-08 15:30:00    43.917750
2024-01-09 09:30:00    42.855176
2024-01-09 10:30:00    41.952053
2024-01-09 11:30:00    41.203939
2024-01-09 12:30:00    40.324259
2024-01-09 13:30:00    39.320711
2024-01-09 14:30:00    38.757788
2024-01-09 15:30:00    38.102509
2024-01-10 09:30:00    37.279635
2024-01-10 10:30:00    36.394400
2024-01-10 11:30:00    35.913343
2024-01-10 12:30:00    35.541039
2024-01-10 13:30:00    35.373168
2024-01-10 14:30:00    35.271132
2024-01-10 15:30:00    34.936802
2024-01-11 09:30:00    34.355167
2024-01-11 10:30:00    33.314277
2024-01-11 11:30:00    32.606574
2024-01-11 12:30:00    32.012346
2024-01-11 13:30:00    32.289158
2024-01-11 14:30:00    32.320112
2024-01-11 15:30:00    32.793350
2024-01-12 09:30:00    35.743174
2024-01-12 10:30:00    38.174965
2024-01-12 11:30:00    39.457503
2024-01-12 12:30:00    40.885208
2024-01-12 13:30:00    42.307670
2024-01-12 14:30:00    43.558658
2024-01-12 15:30:00    44.989224
2024-01-16 09:30:00    46.190979
2024-01-16 10:30:00    48.178517
2024-01-16 11:30:00    49.682557
2024-01-16 12:30:00    51.474679
2024-01-16 13:30:00    52.320972
2024-01-16 14:30:00    53.104366
2024-01-16 15:30:00    53.456219
2024-01-17 09:30:00    50.945607
2024-01-17 10:30:00    48.866907
2024-01-17 11:30:00    47.361609
2024-01-17 12:30:00    45.915645
2024-01-17 13:30:00    44.343317
2024-01-17 14:30:00    42.830157
2024-01-17 15:30:00    41.498022
2024-01-18 09:30:00    40.947443
2024-01-18 10:30:00    40.642644
2024-01-18 11:30:00    40.508172
2024-01-18 12:30:00    40.344087
2024-01-18 13:30:00    40.263294
2024-01-18 14:30:00    40.244963
2024-01-18 15:30:00    40.408232
2024-01-19 09:30:00    40.654677
2024-01-19 10:30:00    40.781267
2024-01-19 11:30:00    41.220180
2024-01-19 12:30:00    41.593808
2024-01-19 13:30:00    42.090526
2024-01-19 14:30:00    42.639733
2024-01-19 15:30:00    42.924141
dtype: float64

In [17]:
rsismas_1d = talib.SMA(rsis_1d, timeperiod=14)

In [18]:
rsismas_1d

Date
2023-11-09          NaN
2023-11-10          NaN
2023-11-13          NaN
2023-11-14          NaN
2023-11-15          NaN
2023-11-16          NaN
2023-11-17          NaN
2023-11-20          NaN
2023-11-21          NaN
2023-11-22          NaN
2023-11-24          NaN
2023-11-27          NaN
2023-11-28          NaN
2023-11-29          NaN
2023-11-30          NaN
2023-12-01          NaN
2023-12-04          NaN
2023-12-05          NaN
2023-12-06          NaN
2023-12-07          NaN
2023-12-08          NaN
2023-12-11          NaN
2023-12-12          NaN
2023-12-13          NaN
2023-12-14          NaN
2023-12-15          NaN
2023-12-18          NaN
2023-12-19    58.840533
2023-12-20    57.167861
2023-12-21    55.625310
2023-12-22    55.009609
2023-12-26    54.813045
2023-12-27    54.830522
2023-12-28    54.703320
2023-12-29    54.946213
2024-01-02    55.193923
2024-01-03    54.938912
2024-01-04    53.952600
2024-01-05    52.879657
2024-01-08    52.006839
2024-01-09    51.031604
2024-01-10    49.828858
2024-01-11    48.497514
2024-01-12    47.503062
2024-01-16    46.462397
2024-01-17    45.055163
2024-01-18    43.852616
2024-01-19    42.793730
dtype: float64

In [19]:
datetime_list = data_5m.index.tolist()

In [20]:
print(datetime_list[28])
print(rsis_1d[28])
print(rsismas_1d[28])

2023-12-20 11:50:00-05:00
57.235812621390004
57.16786131035931

In [21]:
print(len(rsis_5m))
print(len(rsis_15m))
print(len(rsis_30m))
print(len(rsis_60m))
print(len(rsis_1d))

1560
520
260
140
48

In [22]:
class Event:
    def __init__(self, date, close, rsi_5m, rsisma_5m, rsi_15m, rsisma_15m, 
                 rsi_30m, rsisma_30m, rsi_60m, rsisma_60m, rsi_1d, rsisma_1d):
        self.date = date
        self.close = close
        self.rsi_5m = rsi_5m
        self.rsisma_5m = rsisma_5m
        self.ratio_5m = rsi_5m / rsisma_5m
        self.rsi_15m = rsi_15m
        self.rsisma_15m = rsisma_15m
        self.ratio_15m = rsi_15m / rsisma_15m
        self.rsi_30m = rsi_30m
        self.rsisma_30m = rsisma_30m
        self.ratio_30m = rsi_30m / rsisma_30m
        self.rsi_60m = rsi_60m
        self.rsisma_60m = rsisma_60m
        self.ratio_60m = rsi_60m / rsisma_60m
        self.rsi_1d = rsi_1d
        self.rsisma_1d = rsisma_1d
        self.ratio_1d = rsi_1d / rsisma_1d

events = [Event(datetime_list[0], data_5m['Close'].get(0), rsis_5m.iloc[0], rsismas_5m.iloc[0], rsis_15m.iloc[0], 
                rsismas_15m.iloc[0], rsis_30m.iloc[0], rsismas_30m.iloc[0], rsis_60m.iloc[0], rsismas_60m.iloc[0],
               rsis_1d.iloc[27], rsismas_1d.iloc[27])]

#rsis_5m: rsi at 15:45 means rsi value at 15:50
#rsis_15m: rsi at 14:45 means rsi value at 15:00
#rsis_30m: rsi at 14:30 means rsi value at 15:00
#rsis_60m: rsi at 14:30 means rsi value at 15:30

rsi_15_counter = -2
rsi_30_counter = -5
rsi_1h_counter = -11
rsi_1d_counter = 1

for num in range(1, data_5m.shape[0]):
    current_rsi_15m = rsis_15m[int((rsi_15_counter / 3))]
    current_rsisma_15m = rsismas_15m[int((rsi_15_counter / 3))]
    current_rsi_30m = rsis_30m[int((rsi_30_counter / 6))]
    current_rsisma_30m = rsismas_30m[int((rsi_30_counter / 6))]
    current_rsi_60m = rsis_60m[int((rsi_1h_counter / 12)) + 1]
    current_rsisma_60m = rsismas_60m[int((rsi_1h_counter / 12)) + 2]
    current_rsi_1d = rsis_1d[int((rsi_1d_counter / 78)) + 27]
    current_rsisma_1d = rsismas_1d[int((rsi_1d_counter / 78)) + 27]
    
    currentEvent = Event(datetime_list[num], data_5m['Close'].get(num), rsis_5m.iloc[num - 1], 
                         rsismas_5m.iloc[num - 1], current_rsi_15m, current_rsisma_15m, current_rsi_30m,
                        current_rsisma_30m, current_rsi_60m, current_rsisma_60m, current_rsi_1d,
                        current_rsisma_1d)
    
    rsi_15_counter += 1
    rsi_30_counter += 1
    rsi_1h_counter += 1
    rsi_1d_counter += 1
    events.append(currentEvent)

#note to self: rsisma_60m starts at index 312

In [23]:
print(events[0].date)
print(events[0].rsi_1d)

2023-12-20 09:30:00-05:00
57.131926541429245

In [24]:
print(events[42].date)
print(events[42].close)
print(events[42].rsi_5m)
print(events[42].rsi_15m)
print(events[42].rsi_30m)
print(events[168].rsi_60m)
print(events[42].rsi_1d)

2023-12-20 13:00:00-05:00
22.280000686645508
51.66019249460615
nan
nan
61.59707431961289
57.131926541429245

In [25]:
print(events[data_5m.shape[0] - 1].date)
print(events[data_5m.shape[0] - 1].rsi_5m)

2024-01-19 15:55:00-05:00
41.84839372688084

In [26]:
def calculate_average(lst):
    if len(lst) == 0:
        return 0  # Handle the case where the list is empty to avoid division by zero error
    total = sum(lst)
    average = total / len(lst)
    return average

In [27]:
class ratio_profit:
    def __init__(self, entry_ratio, ratio, profit, num_trades, win_rate, average_profit, average_loss,
                greatest_profit, greatest_loss):
        self.entry_ratio = entry_ratio
        self.ratio = ratio
        self.profit = profit
        self.num_trades = num_trades
        self.win_rate = win_rate
        self.average_profit = average_profit
        self.average_loss = average_loss
        self.greatest_profit = greatest_profit
        self.greatest_loss = greatest_loss

ratio_profits = []

entry_ratio_values = np.arange(0.900, 1.100, 0.001)
ratio_values = np.arange(1.000, 1.200, 0.001)

for entry_ratio in entry_ratio_values:
    for ratio in ratio_values:
        entryIndices = []
        exitIndices = []
        trade_counter = 0
        holding_position = False
        all_profits = []
        all_losses = []
        
        for i in range(313, data_5m.shape[0]):
            min_ratio_prev = min([events[i-1].ratio_5m, events[i-1].ratio_15m, 
                                         events[i-1].ratio_30m, events[i-1].ratio_60m, events[i-1].ratio_1d])
            if holding_position == False:
                if min_ratio_prev >= entry_ratio:
                    entryIndices.append(i)
                    holding_position = True
            elif holding_position == True:
                if min_ratio_prev < ratio and events[i - 1].ratio_60m < events[i - 2].ratio_60m:
                    exitIndices.append(i)
                    trade_counter += 1
                    holding_position = False
        
        profit_multiplier = 1.00
        wins = 0
        win_rate = 0
        
        for date in range(0, len(exitIndices)):
            profit = events[exitIndices[date]].close / events[entryIndices[date]].close
            profit_multiplier *= profit
            if profit > 1.00:
                wins += 1
                all_profits.append(profit)
            else:
                all_losses.append(profit)
        if trade_counter != 0:
            win_rate = wins / trade_counter
        elif trade_counter == 0:
            win_rate = 0
        
        average_profit = 0
        average_loss = 0
        greatest_profit = 0
        greatest_loss = 0
        
        if len(all_profits) == 0:
            average_profit = 0
            greatest_profit = 0
        else:
            average_profit = calculate_average(all_profits)
            greatest_profit = max(all_profits)
        
        if len(all_losses) == 0:
            average_loss = 0
            greatest_loss = 0
        else:
            average_loss = calculate_average(all_losses)
            greatest_loss = min(all_losses)
        
        rp = ratio_profit(entry_ratio, ratio, profit_multiplier, trade_counter, win_rate,
                         average_profit, average_loss, greatest_profit, greatest_loss)
        
        if (trade_counter < 25):
            ratio_profits.append(rp)

max_profit_index = 0
for i in range(1, len(ratio_profits)):
    if ratio_profits[i].profit > ratio_profits[max_profit_index].profit:
        max_profit_index = i

print("entry ratio: ", ratio_profits[max_profit_index].entry_ratio)
print("ratio: ", ratio_profits[max_profit_index].ratio)
print("profit: ", ratio_profits[max_profit_index].profit)
print("num_trades: ", ratio_profits[max_profit_index].num_trades)
print("win_rate: ", ratio_profits[max_profit_index].win_rate)
print("average_profit: ", ratio_profits[max_profit_index].average_profit)
print("average_loss: ", ratio_profits[max_profit_index].average_loss)
print("greatest_profit: ", ratio_profits[max_profit_index].greatest_profit)
print("greatest_loss: ", ratio_profits[max_profit_index].greatest_loss)

entry ratio:  0.9720000000000001
ratio:  1.0
profit:  1.0029332371166604
num_trades:  1
win_rate:  1.0
average_profit:  1.0029332371166604
average_loss:  0
greatest_profit:  1.0029332371166604
greatest_loss:  0